# Generated by Django 5.0.14 on 2026-06-17 20:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_gastos', '0022_add_sede_to_documentosoporte'),
        ('tenant_proveedores', '0018_representante_and_more'),
        ('tenant_proyectos', '0019_proyecto_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('consecutivo', models.IntegerField(db_index=True, verbose_name='Consecutivo')),
                ('fecha', models.DateField(verbose_name='Fecha de Emision')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Pactada')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente por Aprobar'), ('APROBADA', 'Aprobada'), ('RECIBIDA', 'Recibida/Completada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento_soporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='tenant_gastos.documentosoporte', verbose_name='Documento Soporte / Gasto')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='tenant_proveedores.proveedor', verbose_name='Proveedor')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'ordering': ['-fecha', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('item_inventario_uuid', models.UUIDField(blank=True, db_index=True, help_text='Soft reference a Producto o Servicio del catalogo de inventario', null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitario')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_compras.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Item Orden de Compra',
                'verbose_name_plural': 'Items Orden de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'fecha'], name='tenant_comp_empresa_2a3fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_comp_empresa_d2f976_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'consecutivo'), name='unique_orden_compra_consecutivo'),
        ),
    ]
