# Generated by Django 5.2.13 on 2026-06-18 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_compras", "0001_init_compras"),
        ("tenant_gastos", "0022_add_sede_to_documentosoporte"),
        ("tenant_proveedores", "0018_representante_and_more"),
        ("tenant_proyectos", "0019_proyecto_sede"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Plantilla"
                    ),
                ),
                (
                    "prefijo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: OC, COM. Dejar vacio si no aplica.",
                        max_length=10,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "rango_desde",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rango Desde",
                    ),
                ),
                (
                    "rango_hasta",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rango Hasta",
                    ),
                ),
                (
                    "consecutivo_actual",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Proximo numero a asignar. Se incrementa automaticamente.",
                        verbose_name="Consecutivo Actual",
                    ),
                ),
                (
                    "vigente",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Vigente (Activa)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Orden de Compra",
                "verbose_name_plural": "Plantillas de Orden de Compra",
                "ordering": ["-vigente", "-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="ordencompra",
            name="unique_orden_compra_consecutivo",
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="numero_documento",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Numero de Documento",
            ),
        ),
        migrations.AddField(
            model_name="plantillaordencompra",
            name="empresa",
            field=models.ForeignKey(
                help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="empresa.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="plantilla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="tenant_compras.plantillaordencompra",
                verbose_name="Plantilla de Orden de Compra",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordencompra",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero_documento"),
                name="unique_orden_compra_numero_documento",
            ),
        ),
        migrations.AddIndex(
            model_name="plantillaordencompra",
            index=models.Index(
                fields=["empresa", "vigente"], name="tenant_comp_empresa_d009f6_idx"
            ),
        ),
    ]
