# Generated by Django 5.0.14 on 2026-06-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_compras', '0002_plantillaordencompra_and_more'),
        ('tenant_gastos', '0022_add_sede_to_documentosoporte'),
        ('tenant_proveedores', '0018_representante_and_more'),
        ('tenant_proyectos', '0019_proyecto_sede'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(check=models.Q(('fecha_entrega__isnull', True), ('fecha_entrega__gte', models.F('fecha')), _connector='OR'), name='orden_compra_fecha_entrega_gte_fecha'),
        ),
        migrations.AddConstraint(
            model_name='plantillaordencompra',
            constraint=models.CheckConstraint(check=models.Q(('rango_hasta__gte', models.F('rango_desde'))), name='plantilla_oc_rango_hasta_gte_rango_desde'),
        ),
        migrations.AddConstraint(
            model_name='plantillaordencompra',
            constraint=models.CheckConstraint(check=models.Q(('consecutivo_actual__gte', models.F('rango_desde'))), name='plantilla_oc_consecutivo_gte_rango_desde'),
        ),
    ]
