# Generated by Django 5.0.14 on 2026-08-07 17:31
"""
Data migration (Fase 10 del pedido original / ADR-003): asigna la Sede
"Principal" de cada empresa a toda OrdenCompra existente sin sede_id.

Requiere que la empresa ya tenga al menos una Sede - normalmente ya
garantizado por `python manage.py backfill_sede_area` (ver
apps/tenant/empresa/management/commands/backfill_sede_area.py), que debe
correrse ANTES de aplicar esta migracion en cualquier tenant real. Si una
empresa aun no tiene ninguna Sede, sus OrdenCompra quedan con sede_id NULL
(la migracion 0007, que endurece la columna a NOT NULL, falla ruidosamente
en ese caso en vez de continuar en un estado inconsistente).
"""
from django.db import migrations


def backfill_sede(apps, schema_editor):
    OrdenCompra = apps.get_model('tenant_compras', 'OrdenCompra')
    Sede = apps.get_model('empresa', 'Sede')

    empresa_ids = OrdenCompra.objects.filter(sede__isnull=True).values_list(
        'empresa_id', flat=True
    ).distinct()

    for empresa_id in empresa_ids:
        sede = Sede.objects.filter(empresa_id=empresa_id, nombre='Principal').first()
        if sede is None:
            sede = Sede.objects.filter(empresa_id=empresa_id).order_by('id').first()
        if sede is None:
            # Sin ninguna Sede para esta empresa: no hay nada razonable que
            # asignar. Se deja sede_id NULL a proposito - la migracion de
            # endurecimiento (0007) debe fallar ruidosamente en este caso,
            # no asumir una sede.
            continue
        OrdenCompra.objects.filter(empresa_id=empresa_id, sede__isnull=True).update(sede_id=sede.id)


def noop_reverse(apps, schema_editor):
    # Deliberadamente no reversible: no hay forma de distinguir "sede
    # asignada por este backfill" de "sede asignada manualmente despues" una
    # vez aplicada, y revertir a NULL perderia informacion real.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_compras', '0005_add_empresa_sede_composite_index'),
    ]

    operations = [
        migrations.RunPython(backfill_sede, noop_reverse),
    ]
