# Generated by Django 5.0.14 on 2026-08-07 17:32
"""
Endurecimiento (Fase 10 del pedido original / ADR-003): una vez el backfill
(0006) garantiza que toda OrdenCompra existente tiene sede_id, esta migracion
hace la columna NOT NULL a nivel de BD.

Verifica explicitamente antes de alterar la columna para dar un error claro
y accionable si algun tenant llega aqui sin haber corrido el backfill
primero (en vez del error generico de Postgres "column contains null
values").
"""
import django.db.models.deletion
from django.db import migrations, models


def check_no_null_sede(apps, schema_editor):
    OrdenCompra = apps.get_model('tenant_compras', 'OrdenCompra')
    huerfanas = OrdenCompra.objects.filter(sede__isnull=True)
    count = huerfanas.count()
    if count:
        ids = list(huerfanas.values_list('id', flat=True)[:10])
        raise RuntimeError(
            f"No se puede endurecer OrdenCompra.sede a NOT NULL: {count} orden(es) "
            f"sin sede_id (ids de ejemplo: {ids}). Corra "
            f"'python manage.py backfill_sede_area' y la migracion 0006 de "
            f"tenant_compras en este tenant antes de reintentar."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_compras', '0006_backfill_orden_compra_sede'),
    ]

    operations = [
        migrations.RunPython(check_no_null_sede, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordencompra',
            name='sede',
            field=models.ForeignKey(
                help_text='Sede propietaria del registro (Contexto Organizacional). Obligatoria para nuevos registros.',
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(app_label)s_%(class)s_related',
                to='empresa.sede',
                verbose_name='Sede',
            ),
        ),
    ]
