# Generated by Django 5.0.14 on 2026-08-09 21:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_compras', '0007_harden_orden_compra_sede_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateField(verbose_name='Fecha de Recepcion')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Recepcion de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Recibida en este Evento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Item de Recepcion de Compra',
                'verbose_name_plural': 'Items de Recepcion de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='itemordencompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Acumulado de recepciones CONFIRMADA para este item (F21). cantidad_recibida <= cantidad siempre; actualizado transaccionalmente por RecepcionCompraBusinessService bajo select_for_update, mismo patron que Producto.stock_actual en KardexService.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente por Aprobar'), ('APROBADA', 'Aprobada'), ('PARCIAL', 'Recepcion Parcial'), ('RECIBIDA', 'Recibida/Completada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='itemordencompra',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_recibida__lte', models.F('cantidad'))), name='item_orden_compra_recibida_lte_cantidad'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area ejecutora/solicitante del registro (Contexto Organizacional). Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='empresa.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='tenant_compras.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='sede',
            field=models.ForeignKey(help_text='Sede que recibe la mercancia. Por defecto, la sede de la orden de compra.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_compra', to='perfil.tenantprofile', verbose_name='Usuario que Recibe'),
        ),
        migrations.AddField(
            model_name='recepcioncompraitem',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='recepcioncompraitem',
            name='item_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_item', to='tenant_compras.itemordencompra', verbose_name='Item de Orden de Compra'),
        ),
        migrations.AddField(
            model_name='recepcioncompraitem',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_compras.recepcioncompra', verbose_name='Recepcion'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['empresa', 'orden_compra'], name='tenant_comp_empresa_9c89fa_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_comp_empresa_43ec98_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompra',
            index=models.Index(fields=['empresa', 'sede'], name='tenant_comp_empresa_9c95bf_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcioncompraitem',
            index=models.Index(fields=['empresa', 'item_orden_compra'], name='tenant_comp_empresa_ad58f0_idx'),
        ),
    ]
