# Generated by Django 5.0.14 on 2026-09-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0041_factura_uniq_factura_numero_por_empresa'),
        ('tenant_compras', '0008_recepcioncompra_recepcioncompraitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='factura_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_compra_origen', to='facturas.factura', verbose_name='Factura electronica DIAN'),
        ),
    ]
