# Generated by Django 5.0.14 on 2026-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_compras", "0009_ordencompra_factura_asociada"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="es_excepcional",
            field=models.BooleanField(
                default=False,
                help_text="Solo True si la orden se aprueba sin requisicion de origen. Requiere motivo_excepcion.",
                verbose_name="Compra Excepcional (sin Requisicion)",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="motivo_excepcion",
            field=models.TextField(blank=True, default="", verbose_name="Motivo de la Excepcion"),
        ),
    ]
