# Generated by Django 5.0.14 on 2026-09-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("facturas", "0042_factura_fecha_pago"),
        ("tenant_compras", "0010_requisiciones_compra"),
        ("tenant_compras_requisiciones", "0001_requisiciones_compra"),
        ("tenant_gastos", "0023_documentosoporte_proyecto_uuid_and_more"),
        ("tenant_proveedores", "0019_cuentaspagar_orden_compra_uuid_and_more"),
        ("tenant_proyectos", "0022_proyecto_costo_gastos_real"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="requisicion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="tenant_compras_requisiciones.requisicioncompra",
                verbose_name="Requisicion de Origen",
            ),
        ),
        migrations.AddIndex(
            model_name="ordencompra",
            index=models.Index(
                fields=["empresa", "requisicion"], name="tenant_comp_empresa_1ffc29_idx"
            ),
        ),
    ]
