# Generated by Django 5.0.14 on 2026-09-26 20:01

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_compras", "0011_requisiciones_compra"),
        ("tenant_compras_requisiciones", "0001_requisiciones_compra"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompraRequisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "monto_asignado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cuanto del total_estimado de la Requisicion consume esta Orden de Compra.",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Monto Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisicion Vinculada a Orden de Compra",
                "verbose_name_plural": "Requisiciones Vinculadas a Orden de Compra",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="ordencompra",
            name="tenant_comp_empresa_1ffc29_idx",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="es_excepcional",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="motivo_excepcion",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="requisicion",
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="requisicion_item_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Soft reference al RequisicionCompraItem que origino esta linea, si aplica.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordencomprarequisicion",
            name="empresa",
            field=models.ForeignKey(
                help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="empresa.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="ordencomprarequisicion",
            name="orden_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisiciones_vinculadas",
                to="tenant_compras.ordencompra",
                verbose_name="Orden de Compra",
            ),
        ),
        migrations.AddField(
            model_name="ordencomprarequisicion",
            name="requisicion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra_vinculadas",
                to="tenant_compras_requisiciones.requisicioncompra",
                verbose_name="Requisicion",
            ),
        ),
        migrations.AddIndex(
            model_name="ordencomprarequisicion",
            index=models.Index(
                fields=["empresa", "orden_compra"], name="tenant_comp_empresa_13fc6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordencomprarequisicion",
            index=models.Index(
                fields=["empresa", "requisicion"], name="tenant_comp_empresa_d251d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordencomprarequisicion",
            constraint=models.UniqueConstraint(
                fields=("orden_compra", "requisicion"), name="unique_orden_compra_requisicion"
            ),
        ),
    ]
