# Generated by Django 5.0.14 on 2026-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_compras", "0012_ordencomprarequisicion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantillaordencompra",
            options={
                "ordering": ["-vigente", "-created_at"],
                "verbose_name": "Plantilla de Numeración",
                "verbose_name_plural": "Plantillas de Numeración",
            },
        ),
        migrations.AddField(
            model_name="plantillaordencompra",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("ORDEN_COMPRA", "Orden de Compra"),
                    ("REQUISICION", "Requisición de Compra"),
                ],
                db_index=True,
                default="ORDEN_COMPRA",
                help_text="Documento que numera esta plantilla: Orden de Compra o Requisición de Compra.",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddIndex(
            model_name="plantillaordencompra",
            index=models.Index(
                fields=["empresa", "tipo_documento", "vigente"],
                name="tenant_comp_empresa_33d11d_idx",
            ),
        ),
    ]
