# Generated by Django 5.0 on 2026-03-06 15:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta contable', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la cuenta contable', max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Débito')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédito')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del movimiento', null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=1, help_text='Orden del movimiento en el asiento', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['asiento', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2024-01)', max_length=7, verbose_name='Periodo (YYYY-MM)')),
                ('fecha_inicio', models.DateField(help_text='Primer día del periodo', verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(help_text='Último día del periodo', verbose_name='Fecha Fin')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', help_text='ABIERTO: Permite ediciones. CERRADO: Bloquea ediciones/anulaciones.', max_length=20, verbose_name='Estado')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró el periodo', null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el cierre del periodo', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha del Asiento')),
                ('descripcion', models.TextField(help_text='Descripción del asiento contable', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('total_debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Débito')),
                ('total_haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria del asiento contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
    ]
