# Generated by Django 5.0.14 on 2026-03-23 18:36

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('facturas', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha del Asiento')),
                ('descripcion', models.TextField(help_text='Descripción del asiento contable', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('tipo_comprobante', models.CharField(blank=True, choices=[('FVE', 'Factura de Venta Electrónica'), ('CE', 'Comprobante de Egreso'), ('RC', 'Recibo de Caja'), ('GN', 'Nota General'), ('ND', 'Nota Débito'), ('NC', 'Nota Crédito')], help_text='Tipo de documento que originó el asiento (FVE, CE, RC, GN, ND, NC)', max_length=5, null=True, verbose_name='Tipo de Comprobante')),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número del comprobante que originó el asiento', max_length=50, null=True, verbose_name='Número de Comprobante')),
                ('total_debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Débito')),
                ('total_haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria del asiento contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura relacionada con este asiento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='facturas.factura', verbose_name='Factura Relacionada')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoMaestroNIIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código oficial de la cuenta según NIIF Colombia', max_length=20, unique=True, verbose_name='Código NIIF')),
                ('nombre', models.CharField(editable=False, help_text='Nombre oficial de la cuenta según NIIF Colombia (auto-seteado desde catálogo)', max_length=200, verbose_name='Nombre Oficial')),
                ('nivel', models.IntegerField(editable=False, help_text='Nivel de la cuenta: 1 (Clase), 2 (Grupo), 4 (Cuenta), 6 (Subcuenta) (auto-seteado desde catálogo)', verbose_name='Nivel')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito/Deudora'), ('C', 'Crédito/Acreedora')], editable=False, help_text='Naturaleza de la cuenta: D (Débito/Deudora), C (Crédito/Acreedora) (auto-seteado desde catálogo)', max_length=1, verbose_name='Naturaleza')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la cuenta está activa en el catálogo', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Catálogo Maestro NIIF',
                'verbose_name_plural': 'Catálogo Maestro NIIF',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='contabilida_codigo_772198_idx'), models.Index(fields=['nivel'], name='contabilida_nivel_7e037a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta contable', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la cuenta contable', max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.IntegerField(default=6, help_text='Nivel de la cuenta según NIIF. Solo nivel 6 (Subcuenta) permite registros contables.', verbose_name='Nivel')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('catalogo_referencia', models.ForeignKey(blank=True, help_text='Cuenta oficial del catálogo NIIF Colombia a la que está anclada esta cuenta personalizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_vinculadas', to='contabilidad.catalogomaestroniif', verbose_name='Referencia Catálogo NIIF')),
                ('cuenta_padre', models.ForeignKey(blank=True, help_text='Cuenta contable padre (para jerarquía)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_hijas', to='contabilidad.cuentacontable', verbose_name='Cuenta Padre')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria de la cuenta contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tercero', models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('OTRO', 'Otro Tercero')], help_text='Tipo de tercero asociado al movimiento (obligatorio para medios magnéticos)', max_length=20, null=True, verbose_name='Tipo de Tercero')),
                ('tercero_id', models.PositiveIntegerField(blank=True, help_text='ID del tercero (Cliente, Proveedor, Empleado u otro)', null=True, verbose_name='ID del Tercero')),
                ('tercero_nit', models.CharField(blank=True, help_text='Número de identificación del tercero (NIT, CC, CE, etc.)', max_length=32, null=True, verbose_name='NIT/CC del Tercero')),
                ('tercero_razon_social', models.CharField(blank=True, help_text='Nombre o razón social del tercero', max_length=200, null=True, verbose_name='Razón Social del Tercero')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Débito')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédito')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del movimiento', null=True, verbose_name='Descripción')),
                ('base_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base gravable para cálculo de IVA', max_digits=15, verbose_name='Base IVA')),
                ('iva_generado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA generado (cuenta 240805)', max_digits=15, verbose_name='IVA Generado')),
                ('iva_descontable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA descontable (cuenta 240810)', max_digits=15, verbose_name='IVA Descontable')),
                ('retefuente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente (cuenta 2365)', max_digits=15, verbose_name='Retención en la Fuente')),
                ('reteica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención ICA (cuenta 2368)', max_digits=15, verbose_name='Retención ICA')),
                ('orden', models.IntegerField(default=1, help_text='Orden del movimiento en el asiento', verbose_name='Orden')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable', verbose_name='Asiento')),
                ('cuenta', models.ForeignKey(help_text='Cuenta contable (debe ser de nivel 6 según normativa)', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['asiento', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2024-01)', max_length=7, verbose_name='Periodo (YYYY-MM)')),
                ('fecha_inicio', models.DateField(help_text='Primer día del periodo', verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(help_text='Último día del periodo', verbose_name='Fecha Fin')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', help_text='ABIERTO: Permite ediciones. CERRADO: Bloquea ediciones/anulaciones.', max_length=20, verbose_name='Estado')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró el periodo', null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el cierre del periodo', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cerrado_por', models.ForeignKey(blank=True, help_text='Usuario del tenant que cerró el periodo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_cerrados', to='perfil.tenantprofile', verbose_name='Cerrado Por')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria del periodo contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='periodos_contables', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'ordering': ['-periodo'],
            },
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_9882f4_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado'], name='contabilida_estado_d78a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_28480f_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['tipo_comprobante', 'numero_comprobante'], name='contabilida_tipo_co_7d4775_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_869d62_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['nivel'], name='contabilida_nivel_fa2e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['asiento', 'orden'], name='contabilida_asiento_b6f18b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__9bc9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['tipo_tercero', 'tercero_id'], name='contabilida_tipo_te_601e11_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['tercero_nit'], name='contabilida_tercero_df58fb_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa', 'periodo'], name='contabilida_empresa_2223d6_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_d7fac8_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='contabilida_fecha_i_e8e24d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodocontable',
            unique_together={('empresa', 'periodo')},
        ),
    ]
