# Generated by Django 5.0 on 2026-03-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('empresa', '0001_initial'),
        ('facturas', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura relacionada con este asiento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='facturas.factura', verbose_name='Factura Relacionada'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable padre (para jerarquía)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_hijas', to='contabilidad.cuentacontable', verbose_name='Cuenta Padre'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria de la cuenta contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del tenant que cerró el periodo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_cerrados', to='perfil.tenantprofile', verbose_name='Cerrado Por'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria del periodo contable (SSoT por tenant).', on_delete=django.db.models.deletion.PROTECT, related_name='periodos_contables', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_9882f4_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado'], name='contabilida_estado_d78a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_28480f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_869d62_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa', 'periodo'], name='contabilida_empresa_2223d6_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_d7fac8_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='contabilida_fecha_i_e8e24d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodocontable',
            unique_together={('empresa', 'periodo')},
        ),
    ]
