# Generated by Django 5.0.14 on 2026-03-29 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('empresa', '0006_alter_empresa_empresa'),
        ('facturas', '0004_remove_factura_facturas_fa_empresa_ae2718_idx_and_more'),
        ('perfil', '0004_alter_tenantprofile_user_cascade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='periodocontable',
            name='contabilida_empresa_2223d6_idx',
        ),
        migrations.AddField(
            model_name='catalogomaestroniif',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogomaestroniif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está habilitada para registros', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='catalogo_referencia',
            field=models.ForeignKey(blank=True, help_text='Vínculo con el catálogo maestro oficial NIIF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_vinculadas', to='contabilidad.catalogomaestroniif', verbose_name='Referencia Catálogo NIIF'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nivel jerárquico de la cuenta (1-6)', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_ca251b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogomaestroniif',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_8f46bf_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogomaestroniif',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_39f6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_661d91_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_f3ae8c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_8a8d52_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_10ebd7_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocontable',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_ca928e_idx'),
        ),
    ]
