# Generated by Django 5.0.14 on 2026-05-03 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_remove_periodocontable_contabilida_empresa_2223d6_idx_and_more'),
        ('empresa', '0007_empresa_owner_email'),
        ('facturas', '0004_remove_factura_facturas_fa_empresa_ae2718_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('tipo_transaccion', models.CharField(help_text='Tipo de transacción (VENTA_FACTURA, COMPRA_GASTO, NOMINA_LIQUIDACION, etc.)', max_length=50, verbose_name='Tipo de Transacción')),
                ('concepto', models.CharField(help_text='Concepto económico (INGRESO_PRINCIPAL, AUXILIO_TRANSPORTE, etc.)', max_length=50, verbose_name='Concepto Económico')),
                ('cuenta_codigo', models.CharField(help_text='Código PUC de 6 dígitos (ej: 130505)', max_length=20, verbose_name='Código de Cuenta PUC')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la regla (para auditoría)', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta regla es vigente', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Regla Contable',
                'verbose_name_plural': 'Reglas Contables',
                'ordering': ['tipo_transaccion', 'concepto'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TarifaImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEICA', 'Retención ICA'), ('RETEIVA', 'Retención IVA'), ('SALUD_EMPLEADO', 'Aporte Salud Empleado'), ('PENSION_EMPLEADO', 'Aporte Pensión Empleado'), ('SALUD_PATRONAL', 'Aporte Salud Patronal'), ('PENSION_PATRONAL', 'Aporte Pensión Patronal'), ('ARL', 'Seguro ARL'), ('CAJA', 'Caja de Compensación'), ('ICBF', 'ICBF'), ('SENA', 'SENA'), ('CESANTIAS', 'Cesantías'), ('PRIMA_SERVICIOS', 'Prima de Servicios'), ('VACACIONES', 'Vacaciones'), ('INTERESES_CESANTIAS', 'Intereses sobre Cesantías')], help_text='Clasificación del impuesto o deducción', max_length=50, verbose_name='Tipo de Impuesto/Deducción')),
                ('valor_porcentaje', models.DecimalField(decimal_places=2, help_text='Tasa en porcentaje (ej: 19.00 para 19% IVA)', max_digits=5, verbose_name='Valor %')),
                ('fecha_inicio', models.DateField(help_text='Desde cuándo rige esta tarifa', verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin', models.DateField(blank=True, help_text='Hasta cuándo rige. NULL = abierta (vigente indefinidamente)', null=True, verbose_name='Fecha Fin Vigencia')),
                ('vigente', models.BooleanField(default=True, help_text='Indica si esta tarifa está activa', verbose_name='Vigente')),
                ('exonerado', models.BooleanField(default=False, help_text='Si aplica art. 114-1 ET (parafiscales <10 SMMLV)', verbose_name='Puede ser Exonerado')),
                ('base_minima_uvt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Umbral UVT para exoneración (ej: 10 para <10 SMMLV). 0 = no aplica exoneración.', max_digits=10, verbose_name='Base Mínima en UVT')),
            ],
            options={
                'verbose_name': 'Tarifa de Impuesto',
                'verbose_name_plural': 'Tarifas de Impuesto',
                'ordering': ['tipo', '-fecha_inicio'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='asiento_reversado',
            field=models.ForeignKey(blank=True, help_text='Asiento original que fue reversado por este', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversales', to='contabilidad.asientocontable', verbose_name='Asiento Reversado'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='debe_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Débito'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_origen_app',
            field=models.CharField(blank=True, help_text='App que generó el asiento: facturas, gastos, empleados, inventario', max_length=30, null=True, verbose_name='App de Origen'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_origen_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK en la app de origen', null=True, verbose_name='ID del Documento Origen'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_origen_modelo',
            field=models.CharField(blank=True, help_text='Modelo que generó el asiento: Factura, DocumentoSoporte, Devengo', max_length=50, null=True, verbose_name='Modelo de Origen'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_origen_numero',
            field=models.CharField(blank=True, help_text='Número visible del documento origen (factura, recibo, etc.)', max_length=50, null=True, verbose_name='Número del Documento Origen'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_origen_reversado',
            field=models.BooleanField(default=False, help_text='Indica si este asiento es reversal de otro', verbose_name='Es Reversal'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='haber_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Crédito'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo_contable',
            field=models.ForeignKey(blank=True, help_text='Período contable al que pertenece el asiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.periodocontable', verbose_name='Periodo Contable'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='centro_costo_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del proyecto/centro de costo (sin FK — referencia desacoplada)', null=True, verbose_name='ID del Centro de Costo'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='cuenta_codigo',
            field=models.CharField(blank=True, help_text='Código PUC de la cuenta (ej: 130505). Si se completa, se usa en lugar de FK.', max_length=20, null=True, verbose_name='Código de Cuenta'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='numero',
            field=models.CharField(help_text='Número único del asiento (auto-generado)', max_length=50, unique=True, verbose_name='Número de Asiento'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_debe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Débito (legado)'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_haber',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Crédito (legado)'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable (debe ser de nivel 6 según normativa). Legado si cuenta_codigo está presente.', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['documento_origen_app', 'documento_origen_modelo', 'documento_origen_id'], name='contabilida_documen_972c32_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['cuenta_codigo'], name='contabilida_cuenta__ddfb86_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['centro_costo_id'], name='contabilida_centro__b8d7a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_origen_reversado', False)), fields=('empresa', 'documento_origen_app', 'documento_origen_modelo', 'documento_origen_id'), name='asientocontable_unique_documento_origen', violation_error_message='Ya existe asiento para este documento origen'),
        ),
        migrations.AddField(
            model_name='reglacontable',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tarifaimpuesto',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='reglacontable',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_2e21a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reglacontable',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_bf47fc_idx'),
        ),
        migrations.AddIndex(
            model_name='reglacontable',
            index=models.Index(fields=['tipo_transaccion', 'concepto', 'activo'], name='contabilida_tipo_tr_ff6e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='reglacontable',
            index=models.Index(fields=['cuenta_codigo'], name='contabilida_cuenta__be32f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reglacontable',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'tipo_transaccion', 'concepto'), name='reglacontable_unique_tipo_concepto_activo', violation_error_message='Ya existe regla activa para este tipo + concepto'),
        ),
        migrations.AddIndex(
            model_name='tarifaimpuesto',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_ae5177_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifaimpuesto',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_182e72_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifaimpuesto',
            index=models.Index(fields=['tipo', 'fecha_inicio', 'vigente'], name='contabilida_tipo_f29c58_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifaimpuesto',
            index=models.Index(fields=['tipo', 'fecha_inicio', 'fecha_fin'], name='contabilida_tipo_b17ae9_idx'),
        ),
    ]
