# Generated by Django 5.0.14 on 2026-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaestroNIIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Cuenta')),
                ('nombre', models.CharField(editable=False, max_length=255)),
                ('nivel', models.IntegerField(editable=False)),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], editable=False, max_length=1)),
            ],
            options={
                'verbose_name': 'Catálogo Maestro NIIF',
                'ordering': ['codigo'],
            },
        ),
    ]
