# Generated by Django 5.2.13 on 2026-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_integracion_v3_preparacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asientocontable',
            name='asientocontable_unique_documento_origen',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='factura',
        ),
    ]
