# Generated by Django 5.0.14 on 2026-03-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_catalogomaestroniif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomaestroniif',
            options={'ordering': ['codigo'], 'verbose_name': 'Catálogo Maestro NIIF', 'verbose_name_plural': 'Catálogo Maestro NIIF'},
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='catalogo_referencia',
            field=models.ForeignKey(blank=True, help_text='Cuenta oficial del catálogo NIIF a la que está anclada esta cuenta personalizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_vinculadas', to='contabilidad.catalogomaestroniif', verbose_name='Catálogo de Referencia'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='codigo',
            field=models.CharField(help_text='Código de cuenta según PUC Colombia (ej: 110505, 2408, 4135)', max_length=20, unique=True, verbose_name='Código Cuenta'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='naturaleza',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], editable=False, max_length=1, verbose_name='Naturaleza'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='nivel',
            field=models.IntegerField(editable=False, help_text='Nivel jerárquico: 1=Clase, 2=Grupo, 4=Cuenta, 6=Subcuenta', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='nombre',
            field=models.CharField(editable=False, max_length=255, verbose_name='Nombre Cuenta'),
        ),
        migrations.AlterModelTable(
            name='catalogomaestroniif',
            table='catalogo_maestro_niif',
        ),
    ]
