# Generated by Django 5.0.14 on 2026-05-08 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_remove_asientocontable_asientocontable_unique_documento_origen_and_more'),
        ('empresa', '0007_empresa_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo_comprobante',
            field=models.CharField(blank=True, choices=[('FVE', 'Factura de Venta Electrónica'), ('CE', 'Comprobante de Egreso'), ('RC', 'Recibo de Caja'), ('GN', 'Nota General'), ('ND', 'Nota Débito'), ('NC', 'Nota Crédito')], help_text='Tipo de documento que originó el asiento (FVE, CE, RC, GN, ND, NC)', max_length=5, null=True, verbose_name='Tipo de Comprobante (Legado)'),
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código/Sigla')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Comprobante')),
                ('prefijo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prefijo')),
                ('consecutivo_actual', models.PositiveIntegerField(default=1, verbose_name='Consecutivo Actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobante',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='tipo_comprobante_ref',
            field=models.ForeignKey(blank=True, help_text='Vínculo dinámico a la plantilla de comprobante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddIndex(
            model_name='tipocomprobante',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_928a38_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocomprobante',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_9b9e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipocomprobante',
            unique_together={('empresa', 'codigo')},
        ),
    ]
