# Generated by Django 5.0.14 on 2026-03-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_catalogomaestroniif_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontable',
            name='catalogo_referencia',
        ),
        migrations.DeleteModel(
            name='CatalogoMaestroNIIF',
        ),
    ]
