# Generated by Django 5.0.14 on 2026-03-09 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_remove_cuentacontable_catalogo_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaestroNIIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código oficial de la cuenta según NIIF Colombia', max_length=20, unique=True, verbose_name='Código NIIF')),
                ('nombre', models.CharField(help_text='Nombre oficial de la cuenta según NIIF Colombia', max_length=200, verbose_name='Nombre Oficial')),
                ('nivel', models.IntegerField(help_text='Nivel de la cuenta: 1 (Clase), 2 (Grupo), 4 (Cuenta), 6 (Subcuenta)', verbose_name='Nivel')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito/Deudora'), ('C', 'Crédito/Acreedora')], help_text='Naturaleza de la cuenta: D (Débito/Deudora), C (Crédito/Acreedora)', max_length=1, verbose_name='Naturaleza')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la cuenta está activa en el catálogo', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Catálogo Maestro NIIF',
                'verbose_name_plural': 'Catálogo Maestro NIIF',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='contabilida_codigo_772198_idx'), models.Index(fields=['nivel'], name='contabilida_nivel_7e037a_idx')],
            },
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='catalogo_referencia',
            field=models.ForeignKey(blank=True, help_text='Cuenta oficial del catálogo NIIF Colombia a la que está anclada esta cuenta personalizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_vinculadas', to='contabilidad.catalogomaestroniif', verbose_name='Referencia Catálogo NIIF'),
        ),
    ]
