# Generated by Django 5.0.14 on 2026-05-13 17:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_asientocontable_tipo_comprobante_and_more'),
        ('empresa', '0007_empresa_owner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRetenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('tipo_tercero', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado')], help_text='Clasificación del tercero (cliente, proveedor, empleado)', max_length=20, verbose_name='Tipo de Tercero')),
                ('nit_tercero', models.CharField(blank=True, help_text='Si está definido, aplica solo a este tercero. Si es nulo, es el default.', max_length=20, null=True, verbose_name='NIT del Tercero')),
                ('tipo_retencion', models.CharField(choices=[('RETEFUENTE', 'Retención en la Fuente'), ('RETEICA', 'Retención ICA'), ('RETEIVA', 'Retención IVA')], help_text='Tipo de retención a aplicar (Retefuente, ReteICA, ReteIVA)', max_length=20, verbose_name='Tipo de Retención')),
                ('porcentaje_por_defecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención a aplicar (0.00 para no retener)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje por Defecto')),
                ('activa', models.BooleanField(default=True, help_text='Si está inactiva, no se aplica en nuevas transacciones', verbose_name='Activa')),
                ('naturaleza', models.CharField(choices=[('VENTA', 'Venta (Invoice)'), ('COMPRA', 'Compra (PO)')], default='VENTA', help_text='Contexto de la transacción (venta o compra)', max_length=20, verbose_name='Naturaleza de Transacción')),
                ('cuenta_retencion', models.ForeignKey(blank=True, help_text='Cuenta contable donde se registra esta retención (ej: Retenciones por Pagar)', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta de Retención')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Retención',
                'verbose_name_plural': 'Configuraciones de Retención',
                'ordering': ['tipo_tercero', 'nit_tercero', 'tipo_retencion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la retención', unique=True, verbose_name='UUID')),
                ('tipo', models.CharField(choices=[('RETEFUENTE', 'Retención en la Fuente'), ('RETEICA', 'Retención ICA'), ('RETEIVA', 'Retención IVA')], help_text='RETEFUENTE, RETEICA o RETEIVA', max_length=20, verbose_name='Tipo de Retención')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje usado para calcular el monto', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje Aplicado')),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base sobre la cual se calculó la retención', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Base de Cálculo')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total retenido', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto de Retención')),
                ('documento_origen_app', models.CharField(help_text='Nombre de la app donde se originó (ej: facturas, gastos, inventario)', max_length=50, verbose_name='Aplicación Origen')),
                ('documento_origen_modelo', models.CharField(help_text='Nombre del modelo (ej: Factura, NotaCredito, ItemFactura, DocumentoSoporte)', max_length=50, verbose_name='Modelo Origen')),
                ('documento_origen_id', models.PositiveIntegerField(help_text='ID del documento en la tabla origen', verbose_name='ID del Documento Origen')),
                ('aplicada_por_cliente', models.BooleanField(default=False, help_text='Si True, la retención es requerida por el cliente (VENTA). Si False, es requerida por el proveedor (COMPRA)', verbose_name='Aplicada por Cliente')),
                ('aplicada_por_proveedor', models.BooleanField(default=False, help_text='Si True, la retención es requerida por el proveedor (COMPRA). Si False, es requerida por la empresa (VENTA)', verbose_name='Aplicada por Proveedor')),
                ('reversada', models.BooleanField(default=False, help_text='Si True, esta retención fue reversada por nota de crédito', verbose_name='Reversada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó el registro de retención', verbose_name='Fecha de Creación')),
                ('notas', models.TextField(blank=True, default='', help_text='Notas sobre la retención (auditoría)', verbose_name='Notas')),
                ('asiento_contable', models.ForeignKey(blank=True, help_text='Asiento contable donde se registró esta retención', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retenciones', to='contabilidad.asientocontable', verbose_name='Asiento Contable')),
                ('configuracion', models.ForeignKey(blank=True, help_text='Configuración de retención que se usó para este cálculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.configuracionretenciones', verbose_name='Configuración Aplicada')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('retencion_reversada_por', models.ForeignKey(blank=True, help_text='Si está reversada, apunta a la retención que la reversa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversales', to='contabilidad.retencion', verbose_name='Retención Reversada Por')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='configuracionretenciones',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_9ae782_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionretenciones',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_8f51c5_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionretenciones',
            index=models.Index(fields=['tipo_tercero', 'nit_tercero', 'tipo_retencion'], name='contabilida_tipo_te_82fecb_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionretenciones',
            index=models.Index(fields=['activa', 'tipo_retencion'], name='contabilida_activa_75162b_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionretenciones',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('tipo_tercero', 'nit_tercero', 'tipo_retencion', 'naturaleza'), name='unique_config_retencion'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['empresa'], name='contabilida_empresa_007d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['empresa', '-created_at'], name='contabilida_empresa_a892b1_idx'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['documento_origen_app', 'documento_origen_modelo', 'documento_origen_id'], name='contabilida_documen_110c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['tipo', 'reversada'], name='contabilida_tipo_a9aabc_idx'),
        ),
        migrations.AddIndex(
            model_name='retencion',
            index=models.Index(fields=['asiento_contable'], name='contabilida_asiento_6ccf56_idx'),
        ),
    ]
