# Generated by Django 5.0.14 on 2026-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_catalogomaestroniif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='naturaleza',
            field=models.CharField(choices=[('D', 'Débito/Deudora'), ('C', 'Crédito/Acreedora')], editable=False, help_text='Naturaleza de la cuenta: D (Débito/Deudora), C (Crédito/Acreedora) (auto-seteado desde catálogo)', max_length=1, verbose_name='Naturaleza'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='nivel',
            field=models.IntegerField(editable=False, help_text='Nivel de la cuenta: 1 (Clase), 2 (Grupo), 4 (Cuenta), 6 (Subcuenta) (auto-seteado desde catálogo)', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='catalogomaestroniif',
            name='nombre',
            field=models.CharField(editable=False, help_text='Nombre oficial de la cuenta según NIIF Colombia (auto-seteado desde catálogo)', max_length=200, verbose_name='Nombre Oficial'),
        ),
    ]
