# Generated by Django 5.0.14 on 2026-03-11 16:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_catalogomaestroniif_naturaleza_and_more'),
        ('empresa', '0001_initial'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Número del comprobante que originó el asiento', max_length=50, null=True, verbose_name='Número de Comprobante'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='tipo_comprobante',
            field=models.CharField(blank=True, choices=[('FVE', 'Factura de Venta Electrónica'), ('CE', 'Comprobante de Egreso'), ('RC', 'Recibo de Caja'), ('GN', 'Nota General'), ('ND', 'Nota Débito'), ('NC', 'Nota Crédito')], help_text='Tipo de documento que originó el asiento (FVE, CE, RC, GN, ND, NC)', max_length=5, null=True, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='nivel',
            field=models.IntegerField(default=6, help_text='Nivel de la cuenta según NIIF. Solo nivel 6 (Subcuenta) permite registros contables.', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='base_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base gravable para cálculo de IVA', max_digits=15, verbose_name='Base IVA'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='iva_descontable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA descontable (cuenta 240810)', max_digits=15, verbose_name='IVA Descontable'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='iva_generado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA generado (cuenta 240805)', max_digits=15, verbose_name='IVA Generado'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='retefuente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente (cuenta 2365)', max_digits=15, verbose_name='Retención en la Fuente'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='reteica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención ICA (cuenta 2368)', max_digits=15, verbose_name='Retención ICA'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='tercero_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del tercero (Cliente, Proveedor, Empleado u otro)', null=True, verbose_name='ID del Tercero'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='tercero_nit',
            field=models.CharField(blank=True, help_text='Número de identificación del tercero (NIT, CC, CE, etc.)', max_length=32, null=True, verbose_name='NIT/CC del Tercero'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='tercero_razon_social',
            field=models.CharField(blank=True, help_text='Nombre o razón social del tercero', max_length=200, null=True, verbose_name='Razón Social del Tercero'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='tipo_tercero',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('OTRO', 'Otro Tercero')], help_text='Tipo de tercero asociado al movimiento (obligatorio para medios magnéticos)', max_length=20, null=True, verbose_name='Tipo de Tercero'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.ForeignKey(help_text='Cuenta contable (debe ser de nivel 6 según normativa)', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['tipo_comprobante', 'numero_comprobante'], name='contabilida_tipo_co_7d4775_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacontable',
            index=models.Index(fields=['nivel'], name='contabilida_nivel_fa2e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['asiento', 'orden'], name='contabilida_asiento_b6f18b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__9bc9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['tipo_tercero', 'tercero_id'], name='contabilida_tipo_te_601e11_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['tercero_nit'], name='contabilida_tercero_df58fb_idx'),
        ),
    ]
