# Generated by Django 5.2.13 on 2026-06-05 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0007_migrate_retenciones_from_facturas"),
        ("empresa", "0009_sedes_areas_explicit_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpuestoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Tipo de impuesto (ej. IVA, RETEFUENTE)",
                        max_length=50,
                        verbose_name="Tipo de Impuesto",
                    ),
                ),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Base sobre la cual se calcula el impuesto",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Base Imponible",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje aplicado",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor calculado del impuesto",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "cuenta_codigo",
                    models.CharField(
                        blank=True,
                        help_text="Codigo de la cuenta contable de impuesto",
                        max_length=20,
                        null=True,
                        verbose_name="Codigo Cuenta",
                    ),
                ),
                (
                    "documento_origen_app",
                    models.CharField(
                        help_text="Nombre de la app donde se origino",
                        max_length=50,
                        verbose_name="Aplicacion Origen",
                    ),
                ),
                (
                    "documento_origen_modelo",
                    models.CharField(
                        help_text="Nombre del modelo origen",
                        max_length=50,
                        verbose_name="Modelo Origen",
                    ),
                ),
                (
                    "documento_origen_id",
                    models.PositiveIntegerField(
                        help_text="ID del documento origen",
                        verbose_name="ID del Documento Origen",
                    ),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        help_text="Asiento contable asociado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos_documento",
                        to="contabilidad.asientocontable",
                        verbose_name="Asiento Contable",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto de Documento",
                "verbose_name_plural": "Impuestos de Documento",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["empresa"], name="contabilida_empresa_e70eb0_idx"
                    ),
                    models.Index(
                        fields=["empresa", "-created_at"],
                        name="contabilida_empresa_7e54dd_idx",
                    ),
                    models.Index(
                        fields=[
                            "documento_origen_app",
                            "documento_origen_modelo",
                            "documento_origen_id",
                        ],
                        name="contabilida_documen_3938ba_idx",
                    ),
                    models.Index(
                        fields=["asiento"], name="contabilida_asiento_a02edb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlantillaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "cuenta_debe_codigo",
                    models.CharField(
                        help_text="Codigo de la cuenta contable para el DEBE",
                        max_length=20,
                        verbose_name="Codigo Cuenta Debito",
                    ),
                ),
                (
                    "cuenta_credito_codigo",
                    models.CharField(
                        help_text="Codigo de la cuenta contable para el HABER",
                        max_length=20,
                        verbose_name="Codigo Cuenta Credito",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta plantilla esta activa",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "regla",
                    models.ForeignKey(
                        help_text="Regla contable asociada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas",
                        to="contabilidad.reglacontable",
                        verbose_name="Regla Contable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla Contable",
                "verbose_name_plural": "Plantillas Contables",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["empresa"], name="contabilida_empresa_15f83b_idx"
                    ),
                    models.Index(
                        fields=["empresa", "-created_at"],
                        name="contabilida_empresa_3ccb24_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("empresa", "regla"),
                        name="plantillacontable_unique_regla_activo",
                    )
                ],
            },
        ),
    ]
