# Generated by Django 5.0.14 on 2026-03-11 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_asientocontable_numero_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocontable',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID'),
        ),
    ]
