# Generated by Django 5.0.14 on 2026-06-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_motor_plantillas_fase3'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lineaplantilla',
            new_name='contabilida_empresa_9ff884_idx',
            old_name='contabilida_empresa_lp001_idx',
        ),
        migrations.RenameIndex(
            model_name='lineaplantilla',
            new_name='contabilida_empresa_4f9729_idx',
            old_name='contabilida_empresa_lp002_idx',
        ),
        migrations.RenameIndex(
            model_name='retencion',
            new_name='contabilida_natural_4d1ef0_idx',
            old_name='retencion_naturaleza_idx',
        ),
    ]
