# Generated by Django 5.0.14 on 2026-06-05 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_rename_contabilida_empresa_lp001_idx_contabilida_empresa_9ff884_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaplantilla',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='plantillacontable',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
