# Generated by Django 5.0.14 on 2026-06-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_plantilla_linea_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineaplantilla',
            name='lineaplantilla_unique_plantilla_origen_valor',
        ),
    ]
