# Generated by Django 5.0.14 on 2026-08-05 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_configuracionretenciones_uuid'),
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asientocontable',
            name='uniq_asiento_documento_origen_no_reversado',
        ),
        migrations.AlterField(
            model_name='configuracionretenciones',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único público para la API', unique=True, verbose_name='UUID'),
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_origen_id__isnull', False), ('documento_origen_reversado', False)), fields=('empresa', 'documento_origen_app', 'documento_origen_modelo', 'documento_origen_id'), name='uniq_asiento_documento_origen_no_reversado'),
        ),
    ]
