# Generated by Django 5.0.14 on 2026-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_remove_asientocontable_uniq_asiento_documento_origen_no_reversado_and_more'),
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retencion',
            constraint=models.UniqueConstraint(condition=models.Q(('reversada', False), models.Q(('documento_origen_id', 0), _negated=True)), fields=('empresa', 'documento_origen_app', 'documento_origen_modelo', 'documento_origen_id', 'tipo'), name='uniq_retencion_documento_origen_tipo_activa'),
        ),
    ]
