# Generated by Django 5.0 on 2026-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailInboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Alias legible para identificar esta configuración', max_length=100, verbose_name='Nombre')),
                ('email_address', models.EmailField(blank=True, help_text='Dirección de correo principal (usado como username por defecto)', max_length=254, null=True, verbose_name='Email principal')),
                ('provider', models.CharField(choices=[('custom', 'Personalizado'), ('gmail', 'Gmail')], db_index=True, default='custom', help_text='Proveedor de correo: Gmail (autocompletado) o Personalizado', max_length=16, verbose_name='Proveedor')),
                ('host', models.CharField(blank=True, help_text='⚠️ DEPRECADO: Usar imap_host. Se mantiene para compatibilidad.', max_length=255, null=True, verbose_name='Servidor (Legacy)')),
                ('port', models.PositiveIntegerField(blank=True, default=993, help_text='⚠️ DEPRECADO: Usar imap_port. Se mantiene para compatibilidad.', null=True, verbose_name='Puerto (Legacy)')),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', help_text='⚠️ DEPRECADO: Siempre IMAP. Se mantiene para compatibilidad.', max_length=10, verbose_name='Protocolo (Legacy)')),
                ('ssl', models.BooleanField(default=True, help_text='⚠️ DEPRECADO: Usar imap_ssl. Se mantiene para compatibilidad.', verbose_name='SSL (Legacy)')),
                ('username', models.CharField(blank=True, help_text='⚠️ DEPRECADO: Usar imap_username. Se mantiene para compatibilidad.', max_length=255, null=True, verbose_name='Usuario (Legacy)')),
                ('password', models.CharField(blank=True, help_text='⚠️ DEPRECADO: Usar imap_password. Se mantiene para compatibilidad.', max_length=255, null=True, verbose_name='Contraseña (Legacy)')),
                ('mailbox', models.CharField(blank=True, default='INBOX', help_text='⚠️ DEPRECADO: Usar imap_mailbox. Se mantiene para compatibilidad.', max_length=255, null=True, verbose_name='Carpeta (Legacy)')),
                ('mark_as_seen', models.BooleanField(default=True, help_text='⚠️ DEPRECADO: Usar imap_mark_as_seen. Se mantiene para compatibilidad.', verbose_name='Marcar como leído (Legacy)')),
                ('move_processed_to', models.CharField(blank=True, help_text='⚠️ DEPRECADO: Usar imap_move_processed_to. Se mantiene para compatibilidad.', max_length=255, null=True, verbose_name='Mover procesados a (Legacy)')),
                ('max_attachment_mb', models.PositiveIntegerField(default=50, help_text='⚠️ DEPRECADO: Usar imap_max_attachment_mb. Se mantiene para compatibilidad.', verbose_name='Límite adjuntos (MB) (Legacy)')),
                ('imap_host', models.CharField(blank=True, default='imap.gmail.com', help_text='Hostname del servidor IMAP (Gmail: imap.gmail.com)', max_length=255, verbose_name='Servidor IMAP')),
                ('imap_port', models.PositiveIntegerField(blank=True, default=993, help_text='Puerto IMAP (Gmail: 993 para SSL, 143 para STARTTLS)', null=True, verbose_name='Puerto IMAP')),
                ('imap_ssl', models.BooleanField(default=True, help_text='Usar SSL/TLS implícito (puerto 993) o STARTTLS (puerto 143)', verbose_name='IMAP SSL/TLS')),
                ('imap_starttls', models.BooleanField(default=False, help_text='Usar STARTTLS en lugar de SSL implícito (solo si puerto 143)', verbose_name='IMAP STARTTLS')),
                ('imap_username', models.CharField(blank=True, help_text='Usuario para autenticación IMAP (por defecto: email_address)', max_length=255, verbose_name='Usuario IMAP')),
                ('imap_password', models.CharField(blank=True, help_text='Contraseña o App Password para IMAP (Gmail: requiere App Password si 2FA activo)', max_length=255, verbose_name='Contraseña IMAP')),
                ('imap_mailbox', models.CharField(blank=True, default='INBOX', help_text='Carpeta IMAP a monitorear (por defecto: INBOX)', max_length=120, verbose_name='Carpeta IMAP')),
                ('imap_mark_as_seen', models.BooleanField(default=True, help_text='Marcar mensajes como leídos tras procesarlos', verbose_name='Marcar como leído')),
                ('imap_move_processed_to', models.CharField(blank=True, help_text='Carpeta destino para mensajes procesados (opcional)', max_length=120, null=True, verbose_name='Mover procesados a')),
                ('imap_max_attachment_mb', models.PositiveIntegerField(blank=True, default=50, help_text='Límite máximo de tamaño de adjuntos en MB (1-50)', null=True, verbose_name='Límite adjuntos IMAP (MB)')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', help_text='Hostname del servidor SMTP (Gmail: smtp.gmail.com)', max_length=255, null=True, verbose_name='Servidor SMTP')),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, help_text='Puerto SMTP (Gmail: 587 para TLS, 465 para SSL)', null=True, verbose_name='Puerto SMTP')),
                ('smtp_ssl', models.BooleanField(default=False, help_text='Usar SSL implícito (puerto 465) o STARTTLS (puerto 587)', verbose_name='SMTP SSL')),
                ('smtp_starttls', models.BooleanField(default=True, help_text='Usar STARTTLS en lugar de SSL implícito (recomendado para puerto 587)', verbose_name='SMTP STARTTLS')),
                ('smtp_username', models.CharField(blank=True, help_text='Usuario para autenticación SMTP (por defecto: email_address)', max_length=255, null=True, verbose_name='Usuario SMTP')),
                ('smtp_password', models.CharField(blank=True, help_text='Contraseña o App Password para SMTP (Gmail: requiere App Password si 2FA activo)', max_length=255, null=True, verbose_name='Contraseña SMTP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Buzón de Correo',
                'verbose_name_plural': 'Configuraciones de Buzones de Correo',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, help_text='Campo técnico para garantizar singleton por tenant (siempre 1)', verbose_name='Clave Singleton')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=255, verbose_name='Razón Social')),
                ('nit', models.CharField(db_index=True, help_text='Número de Identificación Tributaria (sin DV)', max_length=20, unique=True, verbose_name='NIT')),
                ('dv', models.CharField(blank=True, help_text='Dígito verificador del NIT (calculado automáticamente)', max_length=2, null=True, verbose_name='Dígito de Verificación')),
                ('direccion', models.CharField(default='', help_text='Dirección completa de la empresa', max_length=500, verbose_name='Dirección')),
                ('telefono', models.CharField(default='', help_text='Teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, default='', help_text='Email de contacto de la empresa', max_length=254, verbose_name='Email de Contacto')),
                ('regimen_tributario', models.CharField(blank=True, default='NO_RESPONDE', help_text='Régimen tributario de la empresa', max_length=50, verbose_name='Régimen Tributario')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, default='', help_text='URL del sitio web de la empresa', verbose_name='Sitio Web')),
                ('moneda', models.CharField(default='COP', help_text='Código de moneda (ISO 4217)', max_length=8, verbose_name='Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa_empresa',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['nit'], name='empresa_emp_nit_06ed4b_idx'), models.Index(fields=['created_at'], name='empresa_emp_created_163253_idx'), models.Index(fields=['updated_at'], name='empresa_emp_updated_c412e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('singleton_key',), name='unique_singleton_empresa_per_schema', violation_error_message='Solo se permite una empresa por tenant.'),
        ),
        migrations.AddIndex(
            model_name='mailinboxconfig',
            index=models.Index(fields=['provider'], name='empresa_mai_provide_d3b28f_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinboxconfig',
            index=models.Index(fields=['email_address'], name='empresa_mai_email_a_bfe4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinboxconfig',
            index=models.Index(fields=['is_active'], name='empresa_mai_is_acti_c11b87_idx'),
        ),
    ]
