# Generated by Django 5.0.14 on 2026-03-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['empresa'], name='empresa_emp_empresa_80fd82_idx'),
        ),
    ]
