# Generated by Django 5.0.14 on 2026-03-26 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_empresa_alter_empresa_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinboxconfig',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
