# Generated by Django 5.0.14 on 2026-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_mailinboxconfig_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la empresa está activa', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad principal de la empresa', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(blank=True, default='', help_text='Departamento o estado de la empresa', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email principal de la empresa (alias de email_contacto)', max_length=254, verbose_name='Email'),
        ),
    ]
