# Generated by Django 5.0.14 on 2026-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_activa_empresa_ciudad_empresa_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono de contacto', max_length=20, verbose_name='Teléfono'),
        ),
    ]
