# Generated by Django 5.0.14 on 2026-03-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria (SSoT por tenant). Puede ser NULL durante creación inicial.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
