# Generated by Django 5.2.13 on 2026-05-21 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0007_empresa_owner_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "direccion",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Direccion"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Telefono"
                    ),
                ),
                (
                    "encargado_nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Nombre del Encargado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "empresa_sede",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "codigo_funcionamiento",
                    models.CharField(
                        help_text="Codigo unico identificador del area dentro de la sede",
                        max_length=50,
                        verbose_name="Codigo de Funcionamiento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        help_text="Sede a la que pertenece esta area",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="empresa.sede",
                        verbose_name="Sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "db_table": "empresa_area",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(
                fields=["empresa"], name="empresa_sed_empresa_fd6025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(fields=["uuid"], name="empresa_sed_uuid_787dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(fields=["nombre"], name="empresa_sed_nombre_863c4a_idx"),
        ),
        migrations.AddConstraint(
            model_name="sede",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nombre"), name="unique_sede_nombre_per_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["empresa"], name="empresa_are_empresa_71933d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["uuid"], name="empresa_are_uuid_d246a5_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["nombre"], name="empresa_are_nombre_f97a98_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["codigo_funcionamiento"], name="empresa_are_codigo__280b26_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("sede", "nombre"), name="unique_area_nombre_per_sede"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("sede", "codigo_funcionamiento"),
                name="unique_area_codigo_per_sede",
            ),
        ),
    ]
