# Generated by Django 5.0.14 on 2026-05-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_sede_area_sede_empresa_sed_empresa_fd6025_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
