# Generated by Django 5.0.14 on 2026-03-23 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aplicacion', models.CharField(choices=[('TODO', 'Todos'), ('PRODUCTO', 'Solo Productos'), ('SERVICIO', 'Solo Servicios'), ('ACTIVO', 'Activos Fijos')], default='TODO', help_text='Define si esta categoría agrupa productos, servicios o activos.', max_length=16)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/categorias/')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria de esta categoría.', on_delete=django.db.models.deletion.PROTECT, related_name='categorias_inventario', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Placa, Serial o Identificador único.', max_length=64, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/activos/')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo / En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'De Baja / Desechado'), ('VENDIDO', 'Vendido')], default='ACTIVO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos', to='empresa.empresa')),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'aplicacion__in': ['ACTIVO', 'TODO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='tenant_inventario.categoriaitem')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='SKU único', max_length=64, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(default='UND', max_length=16)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/productos/')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del producto. Puede quedar sin categoría si se elimina la categoría asociada.', limit_choices_to={'aplicacion__in': ['PRODUCTO', 'TODO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tenant_inventario.categoriaitem')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria del producto.', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Compra'), ('ENTRADA_AJUSTE', 'Ajuste (+)'), ('ENTRADA_DEVOLUCION', 'Devolución Cliente'), ('SALIDA_VENTA', 'Venta'), ('SALIDA_BAJA', 'Baja / Deterioro'), ('SALIDA_CONSUMO', 'Consumo Interno')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origen_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece el movimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='empresa.empresa')),
                ('producto', models.ForeignKey(help_text='Producto del movimiento. Si se elimina el producto, se eliminan todos sus movimientos.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tenant_inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento Inventario',
                'verbose_name_plural': 'Movimientos Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/servicios/')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del servicio. Puede quedar sin categoría si se elimina la categoría asociada.', limit_choices_to={'aplicacion__in': ['SERVICIO', 'TODO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='tenant_inventario.categoriaitem')),
                ('empresa', models.ForeignKey(help_text='Empresa que presta el servicio.', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_venta', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origen_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa que registra la transacción.', on_delete=django.db.models.deletion.PROTECT, related_name='historial_servicios', to='empresa.empresa')),
                ('servicio', models.ForeignKey(help_text='Servicio del historial. Si se elimina el servicio, se eliminan todos sus historiales.', on_delete=django.db.models.deletion.CASCADE, related_name='historial_ventas', to='tenant_inventario.servicio')),
            ],
            options={
                'verbose_name': 'Historial Servicio',
                'verbose_name_plural': 'Historial Servicios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriaitem',
            index=models.Index(fields=['empresa', 'nombre'], name='tenant_inve_empresa_3ab199_idx'),
        ),
        migrations.AddIndex(
            model_name='activofijo',
            index=models.Index(fields=['codigo'], name='tenant_inve_codigo_27b4be_idx'),
        ),
        migrations.AddIndex(
            model_name='activofijo',
            index=models.Index(fields=['empresa'], name='tenant_inve_empresa_bf4a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='tenant_inve_codigo_eda0be_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'nombre'], name='tenant_inve_empresa_2ac3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'created_at'], name='tenant_inve_empresa_0c7441_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'created_at'], name='tenant_inve_product_5b1e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['empresa', 'nombre'], name='tenant_inve_empresa_9d8948_idx'),
        ),
        migrations.AddIndex(
            model_name='historialservicio',
            index=models.Index(fields=['empresa', 'fecha_registro'], name='tenant_inve_empresa_ecd345_idx'),
        ),
    ]
