# Generated by Django 5.0.14 on 2026-03-30 13:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_empresa_empresa'),
        ('tenant_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoriaitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('empresa'), name='unique_categoria_nombre_per_empresa'),
        ),
    ]
