# Generated by Django 5.0.14 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventario', '0002_categoriaitem_unique_categoria_nombre_per_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='cuenta_contable_uuid',
            field=models.UUIDField(blank=True, help_text='Cuenta PUC nivel 6 (Control Activo)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_contable_uuid',
            field=models.UUIDField(blank=True, help_text='Cuenta PUC nivel 6 (Inventario/Costo)', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cuenta_contable_uuid',
            field=models.UUIDField(blank=True, help_text='Cuenta PUC nivel 6 (Ingreso)', null=True),
        ),
    ]
