# Generated by Django 5.2.13 on 2026-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_inventario", "0003_activofijo_cuenta_contable_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activofijo",
            old_name="cuenta_contable_uuid",
            new_name="cuenta_activo_uuid",
        ),
        migrations.RenameField(
            model_name="servicio",
            old_name="cuenta_contable_uuid",
            new_name="cuenta_ingreso_uuid",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="cuenta_contable_uuid",
        ),
        migrations.AddField(
            model_name="activofijo",
            name="cuenta_depreciacion_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Depreciación Acumulada/Gasto)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categoriaitem",
            name="cuenta_costo_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Costo de Ventas/Depreciación)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categoriaitem",
            name="cuenta_ingreso_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Ingreso por Ventas)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categoriaitem",
            name="cuenta_inventario_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Inventario/Activo)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="cuenta_costo_uuid",
            field=models.UUIDField(
                blank=True, help_text="Cuenta PUC nivel 6 (Costo de Ventas)", null=True
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="cuenta_inventario_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Activo de Inventario)",
                null=True,
            ),
        ),
    ]
