# Generated by Django 5.2.13 on 2026-05-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0007_empresa_owner_email"),
        ("tenant_inventario", "0005_uuid_lookup_and_tenant_code_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="activo_fijo",
            field=models.ForeignKey(
                blank=True,
                help_text="Activo fijo del movimiento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="tenant_inventario.activofijo",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                help_text="Producto del movimiento. Si se elimina el producto, se eliminan todos sus movimientos.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="tenant_inventario.producto",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA_COMPRA", "Compra"),
                    ("ENTRADA_AJUSTE", "Ajuste (+)"),
                    ("ENTRADA_DEVOLUCION", "Devolucion Cliente"),
                    ("SALIDA_VENTA", "Venta"),
                    ("SALIDA_BAJA", "Baja / Deterioro"),
                    ("SALIDA_CONSUMO", "Consumo Interno"),
                    ("ASIGNACION_RESPONSABLE", "Asignacion de Responsable"),
                    ("TRASLADO_MANTENIMIENTO", "Traslado a Mantenimiento"),
                    ("RETORNO_MANTENIMIENTO", "Retorno de Mantenimiento"),
                    ("SALIDA_BAJA_ACTIVO", "Baja de Activo"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["activo_fijo", "created_at"],
                name="tenant_inve_activo__1b45f7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("activo_fijo__isnull", True), ("producto__isnull", False)
                    ),
                    models.Q(
                        ("activo_fijo__isnull", False), ("producto__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="exactly_one_product_or_asset",
            ),
        ),
    ]
