# Generated by Django 5.2.13 on 2026-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_inventario", "0006_movimientoinventario_activo_fijo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="factura_numero",
            field=models.CharField(
                blank=True,
                help_text="Snapshot del número de factura al momento del movimiento.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="factura_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID de la factura asociada. Referencia soft, sin FK.",
                null=True,
            ),
        ),
    ]
