# Generated by Django 5.0.14 on 2026-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventario', '0007_add_factura_vinculacion_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialservicio',
            name='proyecto_nombre',
            field=models.CharField(blank=True, help_text='Nombre snapshot del proyecto vinculado.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialservicio',
            name='proyecto_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID snapshot del proyecto vinculado (Soft Reference).', null=True),
        ),
    ]
