# Generated by Django 5.0.14 on 2026-05-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventario', '0008_historialservicio_proyecto_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activofijo',
            name='cuenta_activo_uuid',
        ),
        migrations.RemoveField(
            model_name='activofijo',
            name='cuenta_depreciacion_uuid',
        ),
        migrations.RemoveField(
            model_name='categoriaitem',
            name='cuenta_costo_uuid',
        ),
        migrations.RemoveField(
            model_name='categoriaitem',
            name='cuenta_ingreso_uuid',
        ),
        migrations.RemoveField(
            model_name='categoriaitem',
            name='cuenta_inventario_uuid',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cuenta_costo_uuid',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cuenta_inventario_uuid',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cuenta_ingreso_uuid',
        ),
    ]
