# Generated by Django 5.0.14 on 2026-06-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_inventario', '0009_remove_activofijo_cuenta_activo_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede de la empresa donde ocurre el movimiento de inventario. Opcional — si no se asigna aplica a toda la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='empresa.sede', verbose_name='Sede'),
        ),
    ]
