# Generated by Django 5.0.14 on 2026-08-09 21:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_inventario', '0010_add_sede_to_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_TRANSITO', 'En Transito'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Traslado de Inventario',
                'verbose_name_plural': 'Traslados de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='documento_origen_app',
            field=models.CharField(blank=True, help_text='App que origino el movimiento: compras, inventario.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='documento_origen_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK en la app de origen.', null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='documento_origen_modelo',
            field=models.CharField(blank=True, help_text='Modelo que origino el movimiento: RecepcionCompraItem, TrasladoInventario.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Compra'), ('ENTRADA_AJUSTE', 'Ajuste (+)'), ('ENTRADA_DEVOLUCION', 'Devolucion Cliente'), ('SALIDA_VENTA', 'Venta'), ('SALIDA_BAJA', 'Baja / Deterioro'), ('SALIDA_CONSUMO', 'Consumo Interno'), ('TRASLADO_SALIDA', 'Traslado - Salida de Sede'), ('TRASLADO_ENTRADA', 'Traslado - Entrada a Sede'), ('ASIGNACION_RESPONSABLE', 'Asignacion de Responsable'), ('TRASLADO_MANTENIMIENTO', 'Traslado a Mantenimiento'), ('RETORNO_MANTENIMIENTO', 'Retorno de Mantenimiento'), ('SALIDA_BAJA_ACTIVO', 'Baja de Activo')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['empresa', 'sede', 'producto'], name='tenant_inve_empresa_e438ea_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['documento_origen_app', 'documento_origen_modelo', 'documento_origen_id'], name='tenant_inve_documen_5273e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_origen_id__isnull', False)), fields=('empresa', 'documento_origen_app', 'documento_origen_modelo', 'documento_origen_id', 'tipo'), name='uniq_movimiento_documento_origen_tipo'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_entrada', to='empresa.area', verbose_name='Area Destino'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='area_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_salida', to='empresa.area', verbose_name='Area Origen'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria del traslado.', on_delete=django.db.models.deletion.PROTECT, related_name='traslados_inventario', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='producto',
            field=models.ForeignKey(help_text='Producto trasladado.', on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='tenant_inventario.producto'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='sede_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='empresa.sede', verbose_name='Sede Destino'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='sede_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='empresa.sede', verbose_name='Sede Origen'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_aprobados', to='perfil.tenantprofile'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibidos', to='perfil.tenantprofile'),
        ),
        migrations.AddField(
            model_name='trasladoinventario',
            name='usuario_solicita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to='perfil.tenantprofile'),
        ),
        migrations.AddIndex(
            model_name='trasladoinventario',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_inve_empresa_a989ef_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladoinventario',
            index=models.Index(fields=['empresa', 'producto'], name='tenant_inve_empresa_8e3f39_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladoinventario',
            index=models.Index(fields=['sede_origen', 'estado'], name='tenant_inve_sede_or_ebaad9_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladoinventario',
            index=models.Index(fields=['sede_destino', 'estado'], name='tenant_inve_sede_de_30a8b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='trasladoinventario',
            constraint=models.CheckConstraint(check=models.Q(('sede_origen', models.F('sede_destino')), _negated=True), name='traslado_sede_origen_distinta_destino'),
        ),
        migrations.AddConstraint(
            model_name='trasladoinventario',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='traslado_cantidad_positiva'),
        ),
    ]
