# Generated by Django 5.0.14 on 2026-08-27 23:37

import apps.tenant.inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventario', '0011_trasladoinventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialservicio',
            name='fecha_registro',
            field=models.DateField(default=apps.tenant.inventario.models._hoy),
        ),
    ]
