# Generated by Django 5.0.14 on 2026-03-23 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsoleActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TENANT_CREATE", "Creación de tenant"),
                            ("TENANT_UPDATE", "Actualización de tenant"),
                            ("TENANT_DELETE", "Eliminación de tenant"),
                            ("USER_CREATE", "Creación de usuario"),
                            ("USER_UPDATE", "Actualización de usuario"),
                            ("USER_DELETE", "Eliminación de usuario"),
                        ],
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales de la acción (URLs, tokens, etc.)",
                        verbose_name="Metadatos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="console_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="console_action_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario objetivo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="console_action_logs",
                        to="tenants.client",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acción de Consola",
                "verbose_name_plural": "Logs de Acciones de Consola",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="console_con_action_5d67d0_idx"
                    ),
                    models.Index(
                        fields=["tenant", "created_at"], name="console_con_tenant__5f3e9e_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="console_con_actor_i_8876e3_idx"
                    ),
                    models.Index(
                        fields=["target_user", "created_at"], name="console_con_target__b0e75d_idx"
                    ),
                ],
            },
        ),
    ]
