# Generated by Django 5.0.14 on 2026-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_alter_consoleactionlog_actor_target_user_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleactionlog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATE', 'Creación de tenant'), ('TENANT_UPDATE', 'Actualización de tenant'), ('TENANT_DELETE', 'Eliminación de tenant'), ('USER_CREATE', 'Creación de usuario'), ('USER_UPDATE', 'Actualización de usuario'), ('USER_DELETE', 'Eliminación de usuario'), ('USER_ACTIVATE', 'Activación de cuenta')], max_length=50, verbose_name='Acción'),
        ),
    ]
