# Generated by Django 5.0.14 on 2026-09-24 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0004_alter_consoleactionlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(max_length=200, verbose_name="Identificador del modelo"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Nombre visible"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Habilitado")),
                (
                    "context_window",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ventana de contexto"
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Máx. tokens de salida"
                    ),
                ),
                ("supports_tools", models.BooleanField(default=False, verbose_name="Tool calling")),
                (
                    "supports_streaming",
                    models.BooleanField(default=False, verbose_name="Streaming"),
                ),
                (
                    "supports_structured_output",
                    models.BooleanField(default=False, verbose_name="Structured output"),
                ),
                ("supports_vision", models.BooleanField(default=False, verbose_name="Visión")),
                (
                    "supports_reasoning",
                    models.BooleanField(default=False, verbose_name="Reasoning"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Capacidades verificadas"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modelo LLM",
                "verbose_name_plural": "Modelos LLM",
                "db_table": "console_llm_model",
                "ordering": ["provider__name", "model_identifier"],
            },
        ),
        migrations.CreateModel(
            name="LLMProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic"),
                            ("ollama", "Ollama"),
                            ("openai_compatible", "OpenAI-compatible REST"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Descripción"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Habilitado")),
                ("is_local", models.BooleanField(default=False, verbose_name="Local/self-hosted")),
                (
                    "base_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Base URL"
                    ),
                ),
                (
                    "secret_encrypted",
                    models.TextField(blank=True, default="", verbose_name="Secreto (cifrado)"),
                ),
                (
                    "default_timeout_s",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Timeout por defecto (s)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proveedor LLM",
                "verbose_name_plural": "Proveedores LLM",
                "db_table": "console_llm_provider",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LLMActiveConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Motivo"),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Activado por",
                    ),
                ),
                (
                    "model_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="console.llmmodelconfig",
                        verbose_name="Modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración LLM activa",
                "verbose_name_plural": "Historial de configuración LLM activa",
                "db_table": "console_llm_active_config",
                "ordering": ["-activated_at"],
            },
        ),
        migrations.AddField(
            model_name="llmmodelconfig",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models_config",
                to="console.llmproviderconfig",
                verbose_name="Proveedor",
            ),
        ),
        migrations.CreateModel(
            name="LLMProviderAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PROVIDER_CREATE", "Creación de provider"),
                            ("PROVIDER_UPDATE", "Actualización de provider"),
                            ("PROVIDER_DELETE", "Eliminación de provider"),
                            ("PROVIDER_TEST", "Prueba de conexión"),
                            ("MODEL_ACTIVATE", "Activación de modelo"),
                            ("MODEL_ROLLBACK", "Rollback a configuración anterior"),
                        ],
                        max_length=30,
                        verbose_name="Acción",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("detail", models.JSONField(blank=True, default=dict, verbose_name="Detalle")),
                ("result", models.CharField(default="OK", max_length=20, verbose_name="Resultado")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="console.llmproviderconfig",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría LLM",
                "verbose_name_plural": "Auditoría LLM",
                "db_table": "console_llm_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"], name="console_llm_action_402f61_idx"
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="llmmodelconfig",
            unique_together={("provider", "model_identifier")},
        ),
    ]
