# Generated by Django 5.0.14 on 2026-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0005_llmmodelconfig_llmproviderconfig_llmactiveconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodelconfig",
            name="fallback_priority",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Prioridad de fallback (menor = primero)"
            ),
        ),
        migrations.AddField(
            model_name="llmmodelconfig",
            name="last_health_check_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ultimo health check"),
        ),
        migrations.AddField(
            model_name="llmmodelconfig",
            name="last_health_reachable",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Alcanzable (ultimo check)"
            ),
        ),
    ]
