# Generated by Django 5.0.14 on 2026-09-03 19:13

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(help_text="Origen logico del texto, ej. 'cliente_observaciones', 'producto_descripcion'.", max_length=50)),
                ('source_id', models.CharField(help_text='PK/UUID del registro de origen (trazabilidad, no es una FK).', max_length=64)),
                ('source_version', models.CharField(blank=True, help_text='Hash o updated_at del origen. Clave de idempotencia: si no cambia, no se vuelve a chunkear/embeber (AI-VECTOR-08).', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto adicional no sensible (sede, area, tipo de documento, ...).')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'AI Knowledge Document',
                'verbose_name_plural': 'AI Knowledge Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chunk_index', models.PositiveIntegerField(help_text='Posicion del chunk dentro del documento (0-based).')),
                ('content', models.TextField(help_text='Texto del fragmento. NUNCA debe contener campos FORBIDDEN/MASKED (la exclusion se aplica en el ChunkingService, AI-VECTOR-06).')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, help_text='Vector de embedding del `content`. NULL hasta que se genere.', null=True)),
                ('embedding_model', models.CharField(blank=True, help_text="Identificador del modelo que genero el embedding (ej. 'voyage-3').", max_length=100)),
                ('embedding_version', models.PositiveIntegerField(default=0, help_text='0 = sin embeber. Se incrementa al reindexar con otro modelo/version.')),
                ('embedding_dimension', models.PositiveIntegerField(blank=True, help_text='Dimension real del vector guardado (redundante con el modelo, explicito para validacion y reindexado).', null=True)),
                ('embedded_at', models.DateTimeField(blank=True, help_text='Momento en que se genero el embedding actual.', null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('document', models.ForeignKey(help_text='Documento de conocimiento al que pertenece este chunk.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenant_ai_knowledge.aiknowledgedocument')),
            ],
            options={
                'verbose_name': 'AI Knowledge Chunk',
                'verbose_name_plural': 'AI Knowledge Chunks',
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['empresa'], name='tenant_ai_k_empresa_dff4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['empresa', '-created_at'], name='tenant_ai_k_empresa_137eec_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['empresa', 'source_type', 'source_id'], name='tenant_ai_k_empresa_6fac87_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['empresa', 'source_type'], name='tenant_ai_k_empresa_e787c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgedocument',
            constraint=models.UniqueConstraint(fields=('empresa', 'source_type', 'source_id'), name='uniq_aikdoc_empresa_source'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['empresa'], name='tenant_ai_k_empresa_3359c2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['empresa', '-created_at'], name='tenant_ai_k_empresa_5ea432_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['empresa', 'document'], name='tenant_ai_k_empresa_8753d0_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['empresa', 'embedding_version'], name='tenant_ai_k_empresa_baa4b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_aikchunk_document_index'),
        ),
    ]
