# Generated by Django 5.0.14 on 2026-09-03 20:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_ai_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector de embedding del `content` (768d, jina-v2-es). NULL hasta que se genere.', null=True),
        ),
    ]
