# Generated by Django 5.0.14 on 2026-09-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_ai_knowledge', '0002_pin_embedding_dimension_768'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('retrieval_enabled', models.BooleanField(default=False, help_text='Si la tool buscar_conocimiento esta habilitada para este tenant.')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'AI Knowledge Settings',
                'verbose_name_plural': 'AI Knowledge Settings',
                'indexes': [models.Index(fields=['empresa'], name='tenant_ai_k_empresa_5c80f2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aiknowledgesettings',
            constraint=models.UniqueConstraint(fields=('empresa',), name='uniq_aikset_empresa'),
        ),
    ]
