# Generated by Django 5.0 on 2026-02-25 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('tenant_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_configuracion', models.CharField(max_length=100)),
                ('tipo_plantilla', models.CharField(choices=[('EQUIPO', 'Equipos'), ('MATERIAL', 'Materiales'), ('SERVICIO', 'Servicios'), ('MIXTO', 'Mixto')], default='MIXTO', max_length=20)),
                ('es_activo', models.BooleanField(default=True)),
                ('iva_porcentaje_default', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('porcentaje_utilidad_default', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('aiu_admin_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aiu_imprevistos_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aiu_utilidad_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('permitir_modelo_equipos', models.BooleanField(default=True)),
                ('permitir_modelo_materiales', models.BooleanField(default=True)),
                ('permitir_modelo_servicios', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Configuración',
                'db_table': 'tenant_cotizaciones_configuracion',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_cotizacion', models.CharField(max_length=20, unique=True)),
                ('cliente_nombre_manual', models.CharField(blank=True, help_text='Se usa si el cliente no existe en la base de datos o hay fallo de app.', max_length=255)),
                ('tipo_cotizacion', models.CharField(default='MIXTO', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada')], default='BORRADOR', max_length=20)),
                ('porcentaje_aiu_admin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_aiu_imprevistos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_aiu_utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('total_con_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_clientes.cliente')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_cotizaciones.configuracioncotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_documento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_servicio',
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('PRODUCTO', 'Equipo'), ('MATERIAL', 'Material'), ('SERVICIO', 'Servicio')], max_length=20)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_cotizaciones.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_cotizaciones.servicio')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_item',
                'ordering': ['orden'],
            },
        ),
    ]
