# Generated by Django 5.0.14 on 2026-03-27 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
    ]
