# Generated by Django 5.0 on 2026-02-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0001_initial_v2_60'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='usa_aiu',
            field=models.BooleanField(default=False, help_text='Si está activado, se aplicarán los porcentajes de Administración, Imprevistos y Utilidad en los cálculos de la cotización.', verbose_name='Usar Modo AIU'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='tenant_cotizaciones.configuracioncotizacion'),
        ),
    ]
