# Generated by Django 5.0 on 2026-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
    ]
