# Generated by Django 5.0.14 on 2026-05-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('tenant_cotizaciones', '0002_configuracioncotizacion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='dias_configuracion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='dias_infraestructura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='dias_instalacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='dias_pruebas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='dias_totales',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracioncotizacion',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
