# Generated by Django 5.0 on 2026-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('tenant_clientes', '0001_initial'),
        ('tenant_cotizaciones', '0002_add_usa_aiu_to_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='prefijo_secuencia',
            field=models.CharField(blank=True, default='', help_text='Prefijo para la numeración (ej: "Cot-", "Fact-")', max_length=20, verbose_name='Prefijo de Secuencia'),
        ),
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='semilla_inicial',
            field=models.IntegerField(default=1, help_text='Número desde el cual empezar la secuencia (ej: 1, 100, 1000)', verbose_name='Semilla Inicial'),
        ),
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='sufijo_secuencia',
            field=models.CharField(blank=True, default='', help_text='Sufijo para la numeración (ej: "-2026", "-BOG")', max_length=20, verbose_name='Sufijo de Secuencia'),
        ),
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='ultimo_numero',
            field=models.IntegerField(default=0, help_text='Último número de secuencia generado para este perfil', verbose_name='Último Número Generado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'configuracion', 'numero_cotizacion'), name='unique_numero_cotizacion_por_perfil'),
        ),
    ]
