# Generated by Django 5.0.14 on 2026-02-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0003_add_folios_dinamicos_to_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_nombre_manual',
            field=models.CharField(blank=True, help_text='Se usa si el cliente no existe en la base de datos o hay fallo de app. Opcional.', max_length=255, null=True),
        ),
    ]
