# Generated by Django 5.0.14 on 2026-02-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0004_alter_cotizacion_cliente_nombre_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_nombre_manual',
        ),
    ]
