# Generated by Django 5.0.14 on 2026-06-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_cotizaciones', '0004_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede de la empresa que emite la cotizacion. Opcional — si no se asigna aplica a toda la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='empresa.sede', verbose_name='Sede'),
        ),
    ]
