# Generated by Django 5.0.14 on 2026-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0005_remove_cotizacion_cliente_nombre_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='tipo_cotizacion_default',
            field=models.CharField(choices=[('MIXTO', 'Mixto'), ('PRODUCTOS', 'Productos'), ('SERVICIOS', 'Servicios'), ('MATERIALES', 'Materiales')], default='MIXTO', help_text='Tipo de cotización que se aplicará por defecto cuando se use este perfil', max_length=20, verbose_name='Tipo de Cotización por Defecto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='codigo_unico',
            field=models.CharField(blank=True, db_index=True, help_text='Código único generado automáticamente desde el perfil de configuración (ej: "STS. 0422-2026")', max_length=100, null=True, unique=True, verbose_name='Código Único'),
        ),
    ]
