# Generated by Django 5.0.14 on 2026-08-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0005_cotizacion_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(),
        ),
    ]
