# Generated by Django 5.0.14 on 2026-03-04 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0006_configuracioncotizacion_tipo_cotizacion_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracioncotizacion',
            options={'verbose_name': 'Perfil de Configuración', 'verbose_name_plural': 'Perfiles de Configuración'},
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='aiu_admin_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='aiu_imprevistos_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='aiu_utilidad_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='iva_porcentaje_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='permitir_modelo_equipos',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='permitir_modelo_materiales',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='permitir_modelo_servicios',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='porcentaje_utilidad_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='tipo_cotizacion_default',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='tipo_plantilla',
        ),
        migrations.RemoveField(
            model_name='configuracioncotizacion',
            name='usa_aiu',
        ),
        migrations.AddField(
            model_name='configuracioncotizacion',
            name='dias_validez',
            field=models.IntegerField(default=15, help_text='Días de validez de la cotización (1 a 30 días). Se usa para calcular automáticamente la fecha de vencimiento.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Días de Validez'),
        ),
        migrations.AlterField(
            model_name='configuracioncotizacion',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Indica si este perfil está activo y disponible para uso', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='configuracioncotizacion',
            name='nombre_configuracion',
            field=models.CharField(help_text='Nombre descriptivo del perfil de configuración', max_length=100, verbose_name='Nombre de Configuración'),
        ),
    ]
