# Generated by Django 5.0.14 on 2026-08-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_cotizaciones', '0006_alter_cotizacion_fecha_emision'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__gt', '')), fields=('empresa', 'codigo'), name='uniq_producto_codigo_por_empresa'),
        ),
    ]
