# Generated by Django 5.0.14 on 2026-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0007_alter_configuracioncotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
