# Generated by Django 5.0.14 on 2026-08-27 01:03

import apps.tenant.cotizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0007_producto_uniq_producto_codigo_por_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=apps.tenant.cotizaciones.models._hoy),
        ),
    ]
