# Generated by Django 5.0.14 on 2026-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_cotizaciones', '0008_alter_cotizacionitem_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
    ]
