# Generated by Django 5.0.14 on 2026-09-09 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _renombrar_estados_legacy(apps, schema_editor):
    """COTIZACIONES-02: ACEPTADA->APROBADA, CANCELADA->RECHAZADA.
    Verificado antes de escribir esta migracion: 0 filas reales en
    ACEPTADA/CANCELADA en los 3 tenants existentes (home/admin/aipoc) --
    este RunPython es una red de seguridad idempotente para cualquier
    entorno/backup que si tenga datos en esos valores viejos, no una
    migracion de datos real conocida."""
    Cotizacion = apps.get_model('tenant_cotizaciones', 'Cotizacion')
    Cotizacion.objects.filter(estado='ACEPTADA').update(estado='APROBADA')
    Cotizacion.objects.filter(estado='CANCELADA').update(estado='RECHAZADA')


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_cotizaciones', '0009_configuracioncotizacion_uniq_configuracion_nombre_por_empresa'),
    ]

    operations = [
        migrations.RunPython(_renombrar_estados_legacy, _noop_reverse),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='CotizacionEstadoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ARCHIVADA', 'Archivada')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, default='secondary', max_length=20)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_estado_config',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tenant_cotizaciones.cotizacion')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.tenantprofile')),
            ],
            options={
                'db_table': 'tenant_cotizaciones_historial_estado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cotizacionestadoconfig',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_cot_estado_config_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='cotizacionhistorialestado',
            index=models.Index(fields=['empresa', 'cotizacion', '-created_at'], name='tenant_coti_empresa_b3d2ea_idx'),
        ),
    ]
