# Generated by Django 5.0 on 2026-03-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, help_text='Cargo del colaborador en esta empresa (ej: "Contador Senior", "Auxiliar Administrativo")', max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, help_text='Departamento al que pertenece el colaborador (opcional)', max_length=100, null=True, verbose_name='Departamento')),
                ('telefono_corporativo', models.CharField(blank=True, help_text='Teléfono corporativo del colaborador (diferente al teléfono personal del User global)', max_length=20, null=True, verbose_name='Teléfono Corporativo')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del colaborador (opcional)', null=True, upload_to='perfiles/avatars/', verbose_name='Avatar')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Preferencias de UI y configuración personalizada del colaborador (JSON). Si es NULL, se normaliza a {} en la aplicación.', null=True, verbose_name='Configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(help_text='Usuario global al que pertenece este perfil (reside en esquema public)', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil del Colaborador',
                'verbose_name_plural': 'Perfiles de Colaboradores',
                'indexes': [models.Index(fields=['user'], name='perfil_tena_user_id_406b46_idx')],
            },
        ),
    ]
