# Generated by Django 5.0.14 on 2026-03-26 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del colaborador', null=True, upload_to='perfiles/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo del colaborador en esta empresa', max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict, help_text='Preferencias de UI y configuracion personalizada del colaborador (JSON).', null=True, verbose_name='Configuracion'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento al que pertenece el colaborador', max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='telefono_corporativo',
            field=models.CharField(blank=True, help_text='Telefono corporativo del colaborador (diferente al personal)', max_length=20, null=True, verbose_name='Telefono Corporativo'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantprofile',
            unique_together={('user', 'empresa')},
        ),
        migrations.AlterModelTable(
            name='tenantprofile',
            table='perfil_tenantprofile',
        ),
    ]
