# Generated by Django 5.0.14 on 2026-03-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_tenantprofile_avatar_alter_tenantprofile_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario global al que pertenece este perfil (reside en esquema public)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
