# Generated by Django 5.2.13 on 2026-05-25 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


def conditionally_add_uuid_to_tenantprofile(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = current_schema()
                  AND table_name='perfil_tenantprofile' 
                  AND column_name='uuid'
            );
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            # 1. Add column as nullable UUID
            cursor.execute('ALTER TABLE perfil_tenantprofile ADD COLUMN uuid UUID;')
            
            # 2. Populate existing rows with unique UUIDs
            import uuid as uuid_pkg
            TenantProfile = apps.get_model("perfil", "TenantProfile")
            for profile in TenantProfile.objects.all():
                cursor.execute(
                    'UPDATE perfil_tenantprofile SET uuid = %s WHERE id = %s;',
                    [str(uuid_pkg.uuid4()), profile.id]
                )
            
            # 3. Alter column to NOT NULL and add UNIQUE constraint
            cursor.execute('ALTER TABLE perfil_tenantprofile ALTER COLUMN uuid SET NOT NULL;')
            cursor.execute('ALTER TABLE perfil_tenantprofile ADD CONSTRAINT perfil_tenantprofile_uuid_key UNIQUE (uuid);')
            # 4. Create index
            cursor.execute('CREATE INDEX IF NOT EXISTS perfil_tenantprofile_uuid_idx ON perfil_tenantprofile (uuid);')


def reverse_conditionally_add_uuid_to_tenantprofile(apps, schema_editor):
    pass


def migrate_departments_data(apps, schema_editor):
    TenantProfile = apps.get_model("perfil", "TenantProfile")
    Departamento = apps.get_model("perfil", "Departamento")
    
    profiles = TenantProfile.objects.all()
    for profile in profiles:
        legacy_name = getattr(profile, "departamento_legacy", None)
        if legacy_name and legacy_name.strip():
            legacy_name = legacy_name.strip()
            dept, created = Departamento.objects.get_or_create(
                nombre=legacy_name,
                empresa=profile.empresa,
                defaults={
                    "activo": True,
                    "descripcion": f"Departamento de {legacy_name} (Migrado)",
                },
            )
            profile.departamento = dept
            profile.save(update_fields=["departamento"])


def reverse_migrate_departments_data(apps, schema_editor):
    TenantProfile = apps.get_model("perfil", "TenantProfile")
    profiles = TenantProfile.objects.all()
    for profile in profiles:
        if profile.departamento:
            profile.departamento_legacy = profile.departamento.nombre
            profile.save(update_fields=["departamento_legacy"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("perfil", "0005_tenantprofile_rol"),
    ]

    operations = [
        # 1. Conditionally add column uuid to database
        migrations.RunPython(
            conditionally_add_uuid_to_tenantprofile,
            reverse_conditionally_add_uuid_to_tenantprofile,
        ),
        # 2. Add field uuid to Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="tenantprofile",
                    name="uuid",
                    field=models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        # 3. Create model Departamento
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del departamento",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion del departamento",
                        null=True,
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Determina si el departamento esta activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "perfil_departamento",
                "unique_together": {("nombre", "empresa")},
            },
        ),
        # 4. Rename old departamento CharField to departamento_legacy
        migrations.RenameField(
            model_name="tenantprofile",
            old_name="departamento",
            new_name="departamento_legacy",
        ),
        # 5. Add new ForeignKey field departamento to tenantprofile
        migrations.AddField(
            model_name="tenantprofile",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Departamento al que pertenece el colaborador",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfiles",
                to="perfil.departamento",
                verbose_name="Departamento",
            ),
        ),
        # 6. Run Python code to migrate strings to ForeignKey associations
        migrations.RunPython(
            migrate_departments_data,
            reverse_migrate_departments_data,
        ),
        # 7. Remove the legacy CharField
        migrations.RemoveField(
            model_name="tenantprofile",
            name="departamento_legacy",
        ),
    ]
