# Generated by Django 5.2.13 on 2026-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("perfil", "0006_tenantprofile_uuid_departamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantprofile",
            name="areas_asignadas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Areas a las que el colaborador tiene acceso asignado",
                related_name="perfiles_asignados",
                to="empresa.area",
                verbose_name="Areas Asignadas",
            ),
        ),
        migrations.AddField(
            model_name="tenantprofile",
            name="sedes_asignadas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sedes a las que el colaborador tiene acceso asignado",
                related_name="perfiles_asignados",
                to="empresa.sede",
                verbose_name="Sedes Asignadas",
            ),
        ),
    ]
