# Generated by Django 5.0.14 on 2026-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_tenantprofile_areas_asignadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='alcance',
            field=models.CharField(choices=[('EMPRESA', 'Empresa completa'), ('SEDE', 'Sede(s) asignada(s)'), ('AREA', 'Area(s) asignada(s)')], db_index=True, default='EMPRESA', help_text='Ambito en el que este colaborador puede operar: EMPRESA (todas las sedes/areas), SEDE (solo sedes_asignadas) o AREA (solo areas_asignadas).', max_length=10, verbose_name='Alcance Organizacional'),
        ),
    ]
