# Generated by Django 5.0.14 on 2026-09-25 19:05

import uuid
from decimal import Decimal

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models

import apps.tenant.compras.requisiciones.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("facturas", "0042_factura_fecha_pago"),
        ("perfil", "0008_add_alcance_and_sede_area_context"),
        ("tenant_cotizaciones", "0010_alter_cotizacion_estado_cotizacionestadoconfig_and_more"),
        ("tenant_proyectos", "0022_proyecto_costo_gastos_real"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisicionCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="Formato REQ-000001, autoasignado.",
                        max_length=50,
                        verbose_name="Numero de Documento",
                    ),
                ),
                ("consecutivo", models.IntegerField(db_index=True, verbose_name="Consecutivo")),
                (
                    "fecha_solicitud",
                    models.DateField(
                        default=apps.tenant.compras.requisiciones.models._hoy,
                        verbose_name="Fecha de Solicitud",
                    ),
                ),
                ("fecha_necesidad", models.DateField(verbose_name="Fecha en que se Necesita")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BIEN", "Bien"), ("SERVICIO", "Servicio"), ("MIXTO", "Mixto")],
                        default="MIXTO",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        db_index=True,
                        default="MEDIA",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_APROBACION", "Pendiente de Aprobacion"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                            ("EN_PROCESO_COMPRA", "En Proceso de Compra"),
                            ("PARCIALMENTE_ATENDIDA", "Parcialmente Atendida"),
                            ("ATENDIDA", "Atendida"),
                        ],
                        db_index=True,
                        default="BORRADOR",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "justificacion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Obligatoria para salir de BORRADOR (validado en el Service Layer).",
                        verbose_name="Justificacion",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, default="", verbose_name="Observaciones"),
                ),
                ("moneda", models.CharField(default="COP", max_length=3, verbose_name="Moneda")),
                (
                    "subtotal_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Subtotal Estimado",
                    ),
                ),
                (
                    "impuestos_estimados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Impuestos Estimados",
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total Estimado",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area ejecutora/solicitante del registro (Contexto Organizacional). Opcional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisiciones_compra",
                        to="tenant_proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "responsable_aprobacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asignado al enviar a aprobacion. Opcional: puede aprobar cualquier admin del tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisiciones_por_aprobar",
                        to="perfil.tenantprofile",
                        verbose_name="Responsable de Aprobacion",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        help_text="Sede solicitante (Contexto Organizacional). Obligatoria.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.sede",
                        verbose_name="Sede",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisiciones_solicitadas",
                        to="perfil.tenantprofile",
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisicion de Compra",
                "verbose_name_plural": "Requisiciones de Compra",
                "ordering": ["-fecha_solicitud", "-consecutivo"],
            },
        ),
        migrations.CreateModel(
            name="RequisicionCompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("descripcion", models.CharField(max_length=255, verbose_name="Descripcion")),
                (
                    "item_inventario_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Soft reference a Producto o Servicio del catalogo de inventario, opcional.",
                        null=True,
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        choices=[("BIEN", "Bien"), ("SERVICIO", "Servicio")],
                        max_length=20,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "cantidad_solicitada",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Cantidad Solicitada",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(default="UND", max_length=20, verbose_name="Unidad de Medida"),
                ),
                (
                    "valor_unitario_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Valor Unitario Estimado",
                    ),
                ),
                (
                    "porcentaje_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Porcentaje IVA",
                    ),
                ),
                (
                    "valor_iva_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Valor IVA Estimado",
                    ),
                ),
                (
                    "subtotal_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Subtotal Estimado",
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Total Estimado",
                    ),
                ),
                (
                    "cantidad_aprobada",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Igual a cantidad_solicitada al aprobar la requisicion, salvo ajuste explicito.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Cantidad Aprobada",
                    ),
                ),
                (
                    "cantidad_ordenada",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Acumulado desde ItemOrdenCompra generados a partir de este item.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Cantidad Ordenada",
                    ),
                ),
                (
                    "cantidad_cancelada",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Cantidad Cancelada",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, default="", verbose_name="Observaciones"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "requisicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tenant_compras_requisiciones.requisicioncompra",
                        verbose_name="Requisicion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Requisicion de Compra",
                "verbose_name_plural": "Items de Requisicion de Compra",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RequisicionCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo_relacion",
                    models.CharField(
                        blank=True,
                        default="CONTEXTO",
                        max_length=30,
                        verbose_name="Tipo de Relacion",
                    ),
                ),
                ("es_principal", models.BooleanField(default=False, verbose_name="Es Principal")),
                (
                    "observacion",
                    models.TextField(blank=True, default="", verbose_name="Observacion"),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisiciones_vinculadas",
                        to="tenant_cotizaciones.cotizacion",
                        verbose_name="Cotizacion",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "requisicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones_vinculadas",
                        to="tenant_compras_requisiciones.requisicioncompra",
                        verbose_name="Requisicion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotizacion Vinculada a Requisicion",
                "verbose_name_plural": "Cotizaciones Vinculadas a Requisicion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisicionDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COTIZACION", "Cotizacion"),
                            ("FACTURA", "Factura"),
                            ("PROYECTO", "Proyecto"),
                            ("ORDEN_INTERNA", "Orden Interna"),
                            ("DOCUMENTO_SOPORTE", "Documento Soporte"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "numero_referencia",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ej: numero de factura externa aun no reconciliada (FE-12345).",
                        max_length=100,
                        verbose_name="Numero de Referencia",
                    ),
                ),
                (
                    "documento_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Soft reference al UUID real (Cotizacion/Factura/Proyecto/OrdenCompra) una vez reconciliado.",
                        null=True,
                        verbose_name="UUID del Documento Real",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/app/media_private"
                        ),
                        upload_to=apps.tenant.compras.requisiciones.models._requisicion_adjunto_upload_path,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, default="", verbose_name="Descripcion"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "requisicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="tenant_compras_requisiciones.requisicioncompra",
                        verbose_name="Requisicion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Requisicion",
                "verbose_name_plural": "Documentos de Requisicion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisicionFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo_relacion",
                    models.CharField(
                        blank=True,
                        default="EVIDENCIA",
                        max_length=30,
                        verbose_name="Tipo de Relacion",
                    ),
                ),
                ("es_principal", models.BooleanField(default=False, verbose_name="Es Principal")),
                (
                    "observacion",
                    models.TextField(blank=True, default="", verbose_name="Observacion"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisiciones_vinculadas",
                        to="facturas.factura",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "requisicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_vinculadas",
                        to="tenant_compras_requisiciones.requisicioncompra",
                        verbose_name="Requisicion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Vinculada a Requisicion",
                "verbose_name_plural": "Facturas Vinculadas a Requisicion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisicionHistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("estado_anterior", models.CharField(blank=True, default="", max_length=30)),
                ("estado_nuevo", models.CharField(max_length=30)),
                ("comentario", models.TextField(blank=True, default="")),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "requisicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="tenant_compras_requisiciones.requisicioncompra",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="perfil.tenantprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado de Requisicion",
                "verbose_name_plural": "Historiales de Estado de Requisicion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="requisicioncompra",
            index=models.Index(fields=["empresa", "estado"], name="tenant_comp_empresa_6f4f72_idx"),
        ),
        migrations.AddIndex(
            model_name="requisicioncompra",
            index=models.Index(
                fields=["empresa", "fecha_solicitud"], name="tenant_comp_empresa_348904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requisicioncompra",
            index=models.Index(fields=["empresa", "sede"], name="tenant_comp_empresa_02aa55_idx"),
        ),
        migrations.AddConstraint(
            model_name="requisicioncompra",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero_documento"),
                name="unique_requisicion_compra_numero_documento",
            ),
        ),
        migrations.AddConstraint(
            model_name="requisicioncompra",
            constraint=models.CheckConstraint(
                check=models.Q(("fecha_necesidad__gte", models.F("fecha_solicitud"))),
                name="requisicion_compra_fecha_necesidad_gte_solicitud",
            ),
        ),
        migrations.AddConstraint(
            model_name="requisicioncompraitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "cantidad_aprobada__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("cantidad_ordenada"), "+", models.F("cantidad_cancelada")
                        ),
                    )
                ),
                name="req_item_ordenada_mas_cancelada_lte_aprobada",
            ),
        ),
        migrations.AddConstraint(
            model_name="requisicioncotizacion",
            constraint=models.UniqueConstraint(
                fields=("requisicion", "cotizacion"), name="unique_requisicion_cotizacion"
            ),
        ),
        migrations.AddIndex(
            model_name="requisiciondocumento",
            index=models.Index(
                fields=["empresa", "requisicion"], name="tenant_comp_empresa_26d93c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="requisicionfactura",
            constraint=models.UniqueConstraint(
                fields=("requisicion", "factura"), name="unique_requisicion_factura"
            ),
        ),
        migrations.AddIndex(
            model_name="requisicionhistorialestado",
            index=models.Index(
                fields=["empresa", "requisicion", "-created_at"],
                name="tenant_comp_empresa_d0574a_idx",
            ),
        ),
    ]
