# Generated by Django 5.0.14 on 2026-09-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_clientes", "0010_carteranota"),
        ("tenant_compras", "0013_plantilla_tipo_documento"),
        ("tenant_compras_requisiciones", "0001_requisiciones_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicioncompra",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisiciones_compra",
                to="tenant_clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="requisicioncompra",
            name="plantilla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisiciones_compra",
                to="tenant_compras.plantillaordencompra",
                verbose_name="Plantilla de Numeración",
            ),
        ),
        migrations.AlterField(
            model_name="requisicioncompra",
            name="numero_documento",
            field=models.CharField(
                db_index=True,
                help_text="Formato definido por la Plantilla de Numeración, autoasignado.",
                max_length=50,
                verbose_name="Numero de Documento",
            ),
        ),
    ]
