# Generated by Django 5.0.14 on 2026-06-17 19:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0030_facturaimpuesto'),
        ('tenant_clientes', '0008_cartera'),
        ('tenant_inventario', '0010_add_sede_to_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emision')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('FACTURADA', 'Facturada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_venta', to='tenant_clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_venta', to='facturas.factura', verbose_name='Factura generada')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Precio unitario')),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa IVA (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Subtotal linea')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_orden_venta', to='tenant_inventario.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_orden_venta', to='tenant_inventario.servicio', verbose_name='Servicio')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_ventas.ordenventa', verbose_name='Orden de venta')),
            ],
            options={
                'verbose_name': 'Item de Orden de Venta',
                'verbose_name_plural': 'Items de Orden de Venta',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_vent_empresa_28dc76_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['empresa', 'cliente'], name='tenant_vent_empresa_6ff689_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenventa',
            index=models.Index(fields=['empresa', '-created_at'], name='tenant_vent_empresa_52580f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordenventa',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', Decimal('0.00'))), name='ventas_orden_subtotal_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ordenventa',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', Decimal('0.00'))), name='ventas_orden_total_positivo'),
        ),
        migrations.AddIndex(
            model_name='itemordenventa',
            index=models.Index(fields=['empresa', 'orden'], name='tenant_vent_empresa_d5b0f6_idx'),
        ),
    ]
