# Generated by Django 5.0.14 on 2026-06-17 20:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0030_facturaimpuesto'),
        ('tenant_clientes', '0008_cartera'),
        ('tenant_inventario', '0010_add_sede_to_movimiento'),
        ('tenant_proyectos', '0019_proyecto_sede'),
        ('tenant_ventas', '0001_init_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenventa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='factura',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emision')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FACTURADA_DIAN', 'Facturada DIAN'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=16)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tenant_clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_origen', to='facturas.factura', verbose_name='Factura electronica DIAN')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=16)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='tenant_inventario.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='tenant_inventario.servicio', verbose_name='Servicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_ventas.venta', verbose_name='Venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ItemOrdenVenta',
        ),
        migrations.DeleteModel(
            name='OrdenVenta',
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_vent_empresa_0ebcea_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'cliente'], name='tenant_vent_empresa_770668_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', '-created_at'], name='tenant_vent_empresa_4ee3bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', Decimal('0.00'))), name='ventas_venta_subtotal_gte_cero'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('total_neto__gte', Decimal('0.00'))), name='ventas_venta_total_neto_gte_cero'),
        ),
        migrations.AddIndex(
            model_name='itemventa',
            index=models.Index(fields=['empresa', 'venta'], name='tenant_vent_empresa_72b30b_idx'),
        ),
    ]
