# Generated by Django 5.0.14 on 2026-06-17 21:17

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0030_facturaimpuesto'),
        ('tenant_clientes', '0008_cartera'),
        ('tenant_proyectos', '0019_proyecto_sede'),
        ('tenant_ventas', '0002_rewrite_venta_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, db_index=True, help_text='Numero asignado por la resolucion. Ej: FE1001', max_length=50, null=True, verbose_name='Numero de Factura'),
        ),
        migrations.CreateModel(
            name='ResolucionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_resolucion', models.CharField(db_index=True, max_length=50, verbose_name='Numero de Resolucion DIAN')),
                ('prefijo', models.CharField(blank=True, help_text='Ej: SETP, FE, PV. Dejar vacio si no aplica.', max_length=10, verbose_name='Prefijo')),
                ('tipo', models.CharField(choices=[('FE', 'Electronica'), ('POS', 'Punto de Venta POS'), ('PAPEL', 'Papel')], db_index=True, default='FE', max_length=10, verbose_name='Tipo de Documento')),
                ('fecha_resolucion', models.DateField(help_text='Fecha en la que la DIAN emitio la resolucion', verbose_name='Fecha de Emision DIAN')),
                ('fecha_desde', models.DateField(default=datetime.date.today, help_text='Fecha de inicio de vigencia', verbose_name='Vigencia Desde')),
                ('fecha_hasta', models.DateField(help_text='Fecha de vencimiento de la resolucion', verbose_name='Vigencia Hasta')),
                ('rango_desde', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rango Desde')),
                ('rango_hasta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rango Hasta')),
                ('consecutivo_actual', models.IntegerField(db_index=True, default=1, help_text='Proximo numero a asignar. Se incrementa automaticamente.', verbose_name='Consecutivo Actual')),
                ('vigente', models.BooleanField(db_index=True, default=True, help_text='Solo una resolucion por tipo puede estar marcada como vigente.', verbose_name='Vigente (Activa)')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Resolucion de Facturacion',
                'verbose_name_plural': 'Resoluciones de Facturacion',
                'ordering': ['-vigente', '-fecha_resolucion'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asociadas', to='tenant_ventas.resolucionfacturacion', verbose_name='Resolucion de Facturacion'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'resolucion'], name='tenant_vent_empresa_b56cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucionfacturacion',
            index=models.Index(fields=['empresa', 'vigente'], name='tenant_vent_empresa_e546d1_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucionfacturacion',
            index=models.Index(fields=['empresa', 'tipo'], name='tenant_vent_empresa_84e19c_idx'),
        ),
    ]
