# Generated by Django 5.0.14 on 2026-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_ventas', '0003_venta_numero_factura_resolucionfacturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cotizacion_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Soft-reference (sin FK) a la Cotizacion desde la que se convirtio esta Venta -- COTIZACIONES-01. unique=True garantiza idempotencia: una Cotizacion solo puede generar una Venta.', null=True, unique=True, verbose_name='Cotizacion de origen'),
        ),
    ]
