# Generated by Django 5.0.14 on 2026-02-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona jurídica')], max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PA', 'Pasaporte')], max_length=5)),
                ('numero_documento', models.CharField(max_length=32)),
                ('razon_social', models.CharField(max_length=180)),
                ('nombre_comercial', models.CharField(blank=True, max_length=180)),
                ('regimen_tributario', models.CharField(choices=[('SIMPLE', 'Régimen Simple'), ('ORDINARIO', 'Régimen Ordinario'), ('NO_RESP', 'No responsable de IVA')], max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='SSoT', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['empresa', 'activo'], name='tenant_clie_empresa_39ba10_idx'), models.Index(fields=['numero_documento'], name='tenant_clie_numero__21ed8f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='uniq_doc_cliente_empresa'),
        ),
    ]
