# Generated by Django 5.0 on 2026-03-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona jurídica')], max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PA', 'Pasaporte')], max_length=5)),
                ('numero_documento', models.CharField(max_length=32)),
                ('razon_social', models.CharField(max_length=180)),
                ('nombre_comercial', models.CharField(blank=True, max_length=180)),
                ('regimen_tributario', models.CharField(choices=[('SIMPLE', 'Régimen Simple'), ('ORDINARIO', 'Régimen Ordinario'), ('NO_RESP', 'No responsable de IVA')], max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='SSoT', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del contacto', max_length=180)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición del contacto', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=32)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el contacto está activo')),
                ('is_principal', models.BooleanField(default=False, help_text='Indica si este es el contacto principal del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece este contacto', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='tenant_clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
                'ordering': ['-is_principal', 'nombre_completo'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'activo'], name='tenant_clie_empresa_39ba10_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_documento'], name='tenant_clie_numero__21ed8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='uniq_doc_cliente_empresa'),
        ),
        migrations.AddIndex(
            model_name='contactocliente',
            index=models.Index(fields=['cliente', 'activo'], name='tenant_clie_cliente_8d2c60_idx'),
        ),
        migrations.AddIndex(
            model_name='contactocliente',
            index=models.Index(fields=['cliente', 'is_principal'], name='tenant_clie_cliente_fdc784_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactocliente',
            unique_together={('cliente', 'email')},
        ),
    ]
