# Generated by Django 5.0 on 2026-03-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del contacto', max_length=180)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición del contacto', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=32)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el contacto está activo')),
                ('is_principal', models.BooleanField(default=False, help_text='Indica si este es el contacto principal del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece este contacto', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='tenant_clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
                'ordering': ['-is_principal', 'nombre_completo'],
                'indexes': [models.Index(fields=['cliente', 'activo'], name='tenant_clie_cliente_8d2c60_idx'), models.Index(fields=['cliente', 'is_principal'], name='tenant_clie_cliente_fdc784_idx')],
                'unique_together': {('cliente', 'email')},
            },
        ),
    ]
