# Generated by Django 5.0.14 on 2026-05-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0002_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aplica_retefuente',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención en la Fuente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aplica_reteica',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención de ICA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aplica_reteiva',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención de IVA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_retenedor',
            field=models.BooleanField(default=False, verbose_name='Es Agente Retenedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='retefuente_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje Retefuente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reteica_porcentaje',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Porcentaje ReteICA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reteiva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje ReteIVA'),
        ),
    ]
