# Generated by Django 5.2.13 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenant_clientes",
            "0003_cliente_aplica_retefuente_cliente_aplica_reteica_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cuenta_contable_uuid",
            field=models.UUIDField(
                blank=True, help_text="Cuenta PUC nivel 6 (Cartera)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="observaciones",
            field=models.TextField(blank=True, help_text="Observaciones adicionales"),
        ),
    ]
