# Generated by Django 5.0.14 on 2026-05-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0004_cliente_cuenta_contable_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aplica_retefuente',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion en la Fuente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='aplica_reteica',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion de ICA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='aplica_reteiva',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion de IVA'),
        ),
    ]
