# Generated by Django 5.0.14 on 2026-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0005_alter_cliente_aplica_retefuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aplica_retefuente',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención en la Fuente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='aplica_reteica',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención de ICA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='aplica_reteiva',
            field=models.BooleanField(default=False, verbose_name='Aplica Retención de IVA'),
        ),
    ]
