# Generated by Django 5.0.14 on 2026-05-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0006_alter_cliente_aplica_retefuente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cuenta_contable_uuid',
        ),
    ]
