# Generated by Django 5.2.13 on 2026-06-03 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_clientes", "0007_remove_cliente_cuenta_contable_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        help_text="Numero de factura de venta", max_length=50
                    ),
                ),
                (
                    "factura_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID de la factura de venta (referencia blanda)",
                        null=True,
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(help_text="Fecha de emision de la factura"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        db_index=True, help_text="Fecha de vencimiento de la obligacion"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto total de la deuda",
                        max_digits=18,
                    ),
                ),
                (
                    "valor_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto pagado",
                        max_digits=18,
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Saldo pendiente",
                        max_digits=18,
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("SIN_PAGO", "Sin pago"),
                            ("PARCIAL", "Pago parcial"),
                            ("PAGADA", "Pagada"),
                        ],
                        db_index=True,
                        default="SIN_PAGO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteras",
                        to="tenant_clientes.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carteras",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartera",
                "verbose_name_plural": "Carteras",
                "ordering": ["fecha_vencimiento", "numero_factura"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "estado_pago"],
                        name="tenant_clie_empresa_e1896f_idx",
                    ),
                    models.Index(
                        fields=["empresa", "cliente", "estado_pago"],
                        name="tenant_clie_empresa_609725_idx",
                    ),
                    models.Index(
                        fields=["numero_factura"], name="tenant_clie_numero__159437_idx"
                    ),
                    models.Index(
                        fields=["fecha_vencimiento"],
                        name="tenant_clie_fecha_v_f377bd_idx",
                    ),
                    models.Index(
                        fields=["factura_uuid"], name="tenant_clie_factura_673143_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "cliente", "numero_factura"),
                        name="uniq_cartera_factura_cliente",
                    )
                ],
            },
        ),
    ]
