# Generated by Django 5.0.14 on 2026-09-11 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_clientes', '0009_contactocliente_es_representante_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('SEGUIMIENTO', 'Seguimiento'), ('PROMESA_PAGO', 'Promesa de pago'), ('DISPUTA', 'Disputa/Reclamo'), ('OTRO', 'Otro')], default='SEGUIMIENTO', max_length=20)),
                ('texto', models.TextField()),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenant_clientes.cartera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartera_notas', to='empresa.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartera_notas', to='perfil.tenantprofile')),
            ],
            options={
                'verbose_name': 'Nota de Cartera',
                'verbose_name_plural': 'Notas de Cartera',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'cartera'], name='tenant_clie_empresa_eb6cfd_idx')],
            },
        ),
    ]
