# Generated by Django 5.0.14 on 2026-03-23 18:36

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("paid_until", models.DateField(blank=True, null=True)),
                ("on_trial", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactiva para suspender el servicio. El tenant no recibirá tráfico.",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("STAFF", "Staff"), ("USER", "User")],
                        default="ADMIN",
                        max_length=10,
                    ),
                ),
                ("is_primary_admin", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactiva para revocar el acceso del usuario a este tenant.",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía de Tenant",
                "verbose_name_plural": "Membresías de Tenants",
            },
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("tenant",),
                name="unique_primary_domain_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["client", "user"], name="tenants_ten_client__ad90d9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("client", "user")},
        ),
    ]
