# Generated by Django 5.0.14 on 2026-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTenantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID de Tarea')),
                ('task_name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre de Tarea')),
                ('args', models.JSONField(blank=True, default=dict, verbose_name='Argumentos Posicionales')),
                ('kwargs', models.JSONField(blank=True, default=dict, verbose_name='Argumentos Nombrados')),
                ('exception', models.TextField(verbose_name='Excepción')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=63, null=True, verbose_name='Esquema del Tenant')),
                ('status', models.CharField(default='FAILED', max_length=20, verbose_name='Estado')),
                ('retries', models.PositiveIntegerField(default=0, verbose_name='Reintentos Realizados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Fallo')),
            ],
            options={
                'verbose_name': 'Tarea Fallida',
                'verbose_name_plural': 'Tareas Fallidas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', 'created_at'], name='tenants_fai_task_na_382c56_idx'), models.Index(fields=['tenant_schema', 'created_at'], name='tenants_fai_tenant__8e303a_idx')],
            },
        ),
    ]
