# Generated by Django 5.0.14 on 2026-09-26 20:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("perfil", "0008_add_alcance_and_sede_area_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudAprobacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("REQUISICION", "Requisicion de Compra")],
                        db_index=True,
                        max_length=30,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "objeto_uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="Soft-reference al documento real (resuelto via registry + empresa_id, nunca GenericForeignKey).",
                        verbose_name="Documento de Origen",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[("BAJA", "Baja"), ("MEDIA", "Media"), ("ALTA", "Alta")],
                        default="MEDIA",
                        help_text="Calculo de riesgo/prioridad real es responsabilidad del Dashboard (Fase 8, DEFERRED) -- aqui es solo un campo de datos.",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Envio"),
                ),
                (
                    "fecha_decision",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Decision"),
                ),
                ("motivo_rechazo", models.TextField(blank=True, default="")),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "snapshot_financiero",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resumen de control al momento de enviar (valor, numero, tipo, documento origen, cotizacion, proyecto, cantidad de lineas, hash/version) -- usado para revalidar antes de aprobar, ver #13 del plan.",
                    ),
                ),
                (
                    "aprobador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_aprobacion_decididas",
                        to="perfil.tenantprofile",
                        verbose_name="Aprobador",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_aprobacion_enviadas",
                        to="perfil.tenantprofile",
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Aprobacion",
                "verbose_name_plural": "Solicitudes de Aprobacion",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudAprobacionHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("CREADA", "Creada"),
                            ("ENVIADA", "Enviada"),
                            ("VISTA", "Vista"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estado_anterior", models.CharField(blank=True, default="", max_length=20)),
                ("estado_nuevo", models.CharField(max_length=20)),
                ("observacion", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="tenant_approvals.solicitudaprobacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="perfil.tenantprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Solicitud de Aprobacion",
                "verbose_name_plural": "Historiales de Solicitud de Aprobacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="solicitudaprobacion",
            index=models.Index(
                fields=["empresa", "estado", "-fecha_envio"], name="tenant_appr_empresa_8ccf39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudaprobacion",
            index=models.Index(
                fields=["empresa", "tipo_documento", "objeto_uuid"],
                name="tenant_appr_empresa_5c70cd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitudaprobacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "PENDIENTE")),
                fields=("empresa", "tipo_documento", "objeto_uuid"),
                name="unique_solicitud_pendiente_por_documento",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudaprobacionhistorial",
            index=models.Index(
                fields=["empresa", "solicitud", "-created_at"],
                name="tenant_appr_empresa_cb9c95_idx",
            ),
        ),
    ]
