# Generated by Django 5.0.14 on 2026-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaprobacion',
            name='tipo_documento',
            field=models.CharField(choices=[('REQUISICION', 'Requisicion de Compra'), ('PROYECTO_INICIO', 'Inicio de Proyecto (Viabilidad)')], db_index=True, max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
