# Generated by Django 5.0.14 on 2026-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('tenant_gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentosoporte',
            name='tenant_gast_activo_5624b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentosoporte',
            name='tenant_gast_anulado_0a96cb_idx',
        ),
        migrations.AddField(
            model_name='gasto',
            name='codigo_contable',
            field=models.CharField(blank=True, choices=[('510506', '510506 - Honorarios'), ('510515', '510515 - Servicios Tecnicos'), ('510518', '510518 - Servicios de Aseo y Vigilancia'), ('510521', '510521 - Arrendamientos'), ('510524', '510524 - Contribuciones y Afiliaciones'), ('510527', '510527 - Seguros'), ('510530', '510530 - Servicios Publicos'), ('510533', '510533 - Gastos de Viaje'), ('510536', '510536 - Transporte, Fletes y Acarreos'), ('510545', '510545 - Publicidad, Propaganda y Promocion'), ('510554', '510554 - Utiles y Papeleria'), ('510557', '510557 - Combustibles y Lubricantes'), ('510560', '510560 - Envases y Empaques'), ('510563', '510563 - Elementos de Aseo y Cafeteria'), ('510566', '510566 - Costos y Gastos de Sistemas'), ('510569', '510569 - Mantenimiento y Reparaciones'), ('510595', '510595 - Gastos Legales'), ('510598', '510598 - Amortizaciones'), ('519595', '519595 - Gastos Diversos'), ('520506', '520506 - Honorarios (Ventas)'), ('520521', '520521 - Arrendamientos (Ventas)'), ('520530', '520530 - Servicios Publicos (Ventas)'), ('520545', '520545 - Publicidad, Propaganda y Promocion (Ventas)'), ('520554', '520554 - Utiles y Papeleria (Ventas)'), ('520569', '520569 - Mantenimiento y Reparaciones (Ventas)'), ('530501', '530501 - Financieros'), ('530506', '530506 - Perdida en Venta y Retiro de Bienes'), ('530520', '530520 - Gastos Extraordinarios'), ('530530', '530530 - Comisiones Bancarias'), ('110505', '110505 - Caja General'), ('111005', '111005 - Bancos - Cuenta Corriente'), ('111006', '111006 - Bancos - Cuenta de Ahorros')], db_index=True, help_text='Codigo del PUC (ej: 510506) para vinculacion con CuentaContable del tenant. Si se configura, el asiento contable usara esta cuenta como debito de gastos.', max_length=10, null=True, verbose_name='Codigo Contable NIIF'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria_contable',
            field=models.CharField(blank=True, choices=[('ARRENDAMIENTOS', 'Arrendamientos'), ('SERVICIOS_PUBLICOS', 'Servicios Publicos'), ('PAPELERIA_UTILES', 'Papeleria y Utiles'), ('MANTENIMIENTO_REPARACIONES', 'Mantenimiento y Reparaciones'), ('EQUIPOS_HERRAMIENTAS', 'Equipos y Herramientas'), ('LICENCIAS_SOFTWARE', 'Licencias y Software'), ('HOSTING_DOMINIO', 'Hosting y Dominios'), ('TRANSPORTE_FLETES', 'Transporte y Fletes'), ('COMBUSTIBLE', 'Combustible'), ('VIATICOS', 'Viaticos'), ('PUBLICIDAD_MARKETING', 'Publicidad y Marketing'), ('SEGUROS', 'Seguros'), ('IMPUESTOS_TASAS', 'Impuestos, Tasas y Contribuciones'), ('HONORARIOS', 'Honorarios'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('ASEO_CAFETERIA', 'Aseo y Cafeteria'), ('VIGILANCIA_SEGURIDAD', 'Vigilancia y Seguridad'), ('CAPACITACION', 'Capacitacion'), ('GASTOS_FINANCIEROS', 'Gastos Financieros'), ('COMISIONES_BANCARIAS', 'Comisiones Bancarias'), ('SUSCRIPCIONES', 'Suscripciones'), ('ELEMENTOS_PROTECCION', 'Elementos de Proteccion'), ('MATERIALES_INSUMOS', 'Materiales e Insumos'), ('ADECUACIONES_INSTALACIONES', 'Adecuaciones e Instalaciones'), ('COMUNICACIONES', 'Comunicaciones'), ('ENERGIA', 'Energia'), ('LIMPEZA_ASEO', 'Limpieza y Aseo'), ('TECNOLOGIA_INFORMATICA', 'Tecnologia e Informatica'), ('GASTOS_LEGALES', 'Gastos Legales'), ('TRIBUTARIOS', 'Gastos Tributarios'), ('OTROS', 'Otros Gastos')], help_text='Categoria contable del gasto (excluye personal)', max_length=100, null=True, verbose_name='Categoria Contable'),
        ),
        migrations.AddIndex(
            model_name='documentosoporte',
            index=models.Index(condition=models.Q(('activo', True), ('anulado', False)), fields=['fecha'], name='idx_gastos_activos'),
        ),
    ]
