# Generated by Django 5.0.14 on 2026-05-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_tenantprofile_rol'),
        ('tenant_gastos', '0002_remove_documentosoporte_tenant_gast_activo_5624b1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Razón por la cual se anula el documento (Requerido por DIAN)', null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, help_text='Operador que realizó la acción de anulación', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_anulados', to='perfil.tenantprofile', verbose_name='Usuario que Anuló'),
        ),
    ]
