# Generated by Django 5.2.13 on 2026-05-06 20:42

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('perfil', '0005_tenantprofile_rol'),
        ('tenant_gastos', '0002_remove_documentosoporte_tenant_gast_activo_5624b1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resoluciondian',
            options={'ordering': ['-vigente', '-fecha_resolucion'], 'verbose_name': 'Resolucion DIAN', 'verbose_name_plural': 'Resoluciones DIAN'},
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Razon legal/administrativa por la cual se anula el documento.', null=True, verbose_name='Motivo de Anulacion'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, help_text='Funcionario responsable de la anulacion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_anulados_gastos', to='perfil.tenantprofile', verbose_name='Usuario que Anulo'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el documento soporte esta activo. Debe estar desactivado para poder anular.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='anulado',
            field=models.BooleanField(default=False, help_text='Indica si el documento fue anulado legalmente. No se puede deshacer.', verbose_name='Anulado'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='consecutivo',
            field=models.IntegerField(db_index=True, editable=False, help_text='Numero consecutivo del documento (dentro del rango de la resolucion)', verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='fecha',
            field=models.DateField(help_text='Fecha de emision del documento soporte', verbose_name='Fecha del Documento'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulacion'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='numero_factura_proveedor',
            field=models.CharField(blank=True, db_index=True, help_text='Numero de factura o comprobante emitido por el proveedor (referencia)', max_length=100, null=True, verbose_name='Numero Factura Proveedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='resolucion_dian',
            field=models.ForeignKey(help_text='Resolucion DIAN que autoriza este documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_soporte', to='tenant_gastos.resoluciondian', verbose_name='Resolucion DIAN'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor calculado de retencion en la fuente (subtotal * porcentaje)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Retefuente'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Sin Retefuente'), ('0.04', '4% - Servicios (Declarantes)'), ('0.06', '6% - Servicios (No Declarantes)'), ('0.10', '10% - Honorarios y Consultoria (Persona Natural no declarante)'), ('0.11', '11% - Honorarios y Consultoria (Persona Juridica o declarante)')], default='0.00', help_text='Porcentaje de retencion en la fuente aplicado', max_length=10, verbose_name='Porcentaje Retefuente'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor calculado de retencion ICA (subtotal * porcentaje)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ReteICA'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Exento'), ('0.0069', '0.69% - Tarifa 0.69% (6.9/1000)'), ('0.00966', '0.966% - Tarifa 0.966% (9.66/1000)'), ('0.01104', '1.104% - Tarifa 1.104% (11.04/1000)')], default='0.00', help_text='Porcentaje de retencion ICA aplicado', max_length=10, verbose_name='Porcentaje ReteICA'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Valor neto antes de retenciones', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_direccion',
            field=models.CharField(blank=True, help_text='Direccion del vendedor (snapshot historico)', max_length=500, null=True, verbose_name='Direccion Vendedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_nit',
            field=models.CharField(help_text='Identificacion tributaria del vendedor (snapshot historico)', max_length=20, verbose_name='NIT/ID Vendedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_nombre',
            field=models.CharField(help_text='Persona o empresa que emitio la factura/cuenta', max_length=255, verbose_name='Nombre del Vendedor/Proveedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_telefono',
            field=models.CharField(blank=True, help_text='Telefono del vendedor (snapshot historico)', max_length=20, null=True, verbose_name='Telefono Vendedor'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVOS', 'Administrativos'), ('MATERIA_PRIMA', 'Materia Prima'), ('MANUTENCION', 'Mantenimiento'), ('VIATICOS', 'Viaticos'), ('SERVICIOS_PUBLICOS', 'Servicios Publicos'), ('TRANSPORTE', 'Transporte'), ('COMUNICACIONES', 'Comunicaciones'), ('SEGUROS', 'Seguros'), ('ARRIENDOS', 'Arriendos'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('PUBLICIDAD', 'Publicidad y Marketing'), ('CAPACITACION', 'Capacitacion'), ('HERRAMIENTAS', 'Herramientas y Equipos'), ('INSUMOS', 'Insumos y Materiales'), ('ENERGIA', 'Energia y Combustibles'), ('LIMPEZA', 'Limpieza y Aseo'), ('SEGURIDAD', 'Seguridad'), ('TECNOLOGIA', 'Tecnologia e Informatica'), ('LEGALES', 'Gastos Legales'), ('TRIBUTARIOS', 'Gastos Tributarios'), ('OTROS', 'Otros Gastos')], help_text='Centro de costo para clasificacion contable', max_length=100, null=True, verbose_name='Centro de Costo'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion adicional del gasto', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha de vencimiento de la resolucion', verbose_name='Fecha Final Aplicacion'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, help_text='Fecha desde la cual se empezara a usar en el sistema', verbose_name='Fecha Inicio Aplicacion'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='fecha_resolucion',
            field=models.DateField(help_text='Fecha en la que la DIAN emitio la resolucion', verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='numero_resolucion',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Numero Resolucion DIAN'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='vigente',
            field=models.BooleanField(db_index=True, default=True, help_text='Solo una resolucion puede estar vigente para ser usada por defecto.', verbose_name='Vigente (Prestablecida)'),
        ),
        migrations.RemoveConstraint(
            model_name='documentosoporte',
            name='unique_ds_resolucion_consecutivo',
        ),
        migrations.AddConstraint(
            model_name='documentosoporte',
            constraint=models.UniqueConstraint(fields=('resolucion_dian', 'consecutivo'), name='unique_ds_resolucion_consecutivo', violation_error_message='Ya existe un Documento Soporte con este consecutivo en esta resolucion.'),
        ),
        migrations.RemoveConstraint(
            model_name='documentosoporte',
            name='unique_ds_vendedor_factura',
        ),
        migrations.AddConstraint(
            model_name='documentosoporte',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empresa', 'vendedor_nit', 'numero_factura_proveedor'), name='unique_ds_vendedor_factura', violation_error_message='Ya existe un Documento Soporte activo con este vendedor y numero de factura.'),
        ),
    ]
