# Generated by Django 5.0.14 on 2026-05-07 00:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('perfil', '0005_tenantprofile_rol'),
        ('tenant_gastos', '0003_alter_resoluciondian_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentosoporte',
            name='unique_ds_resolucion_consecutivo',
        ),
        migrations.RemoveConstraint(
            model_name='documentosoporte',
            name='unique_ds_vendedor_factura',
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='documentos_soporte/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='consecutivo',
            field=models.IntegerField(db_index=True, editable=False, verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Documento'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='numero_factura_proveedor',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='prefijo',
            field=models.CharField(max_length=10, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='resolucion_dian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_soporte', to='tenant_gastos.resoluciondian', verbose_name='Resolucion DIAN'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Sin Retefuente'), ('0.04', '4% - Servicios (Declarantes)'), ('0.06', '6% - Servicios (No Declarantes)'), ('0.10', '10% - Honorarios y Consultoria (No declarante)'), ('0.11', '11% - Honorarios y Consultoria (Declarante)')], default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Exento'), ('0.0069', '0.69%'), ('0.00966', '0.966%'), ('0.01104', '1.104%')], default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_anulados_gastos', to='perfil.tenantprofile'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_nit',
            field=models.CharField(max_length=20, verbose_name='NIT Vendedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Vendedor'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='vendedor_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria_contable',
            field=models.CharField(blank=True, choices=[('ARRENDAMIENTOS', 'Arrendamientos'), ('SERVICIOS_PUBLICOS', 'Servicios Publicos'), ('PAPELERIA_UTILES', 'Papeleria y Utiles'), ('MANTENIMIENTO_REPARACIONES', 'Mantenimiento y Reparaciones'), ('EQUIPOS_HERRAMIENTAS', 'Equipos y Herramientas'), ('LICENCIAS_SOFTWARE', 'Licencias y Software'), ('HOSTING_DOMINIO', 'Hosting y Dominios'), ('TRANSPORTE_FLETES', 'Transporte y Fletes'), ('COMBUSTIBLE', 'Combustible'), ('VIATICOS', 'Viaticos'), ('PUBLICIDAD_MARKETING', 'Publicidad y Marketing'), ('SEGUROS', 'Seguros'), ('IMPUESTOS_TASAS', 'Impuestos, Tasas y Contribuciones'), ('HONORARIOS', 'Honorarios'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('ASEO_CAFETERIA', 'Aseo y Cafeteria'), ('VIGILANCIA_SEGURIDAD', 'Vigilancia y Seguridad'), ('CAPACITACION', 'Capacitacion'), ('GASTOS_FINANCIEROS', 'Gastos Financieros'), ('COMISIONES_BANCARIAS', 'Comisiones Bancarias'), ('SUSCRIPCIONES', 'Suscripciones'), ('ELEMENTOS_PROTECCION', 'Elementos de Proteccion'), ('MATERIALES_INSUMOS', 'Materiales e Insumos'), ('ADECUACIONES_INSTALACIONES', 'Adecuaciones e Instalaciones'), ('COMUNICACIONES', 'Comunicaciones'), ('ENERGIA', 'Energia'), ('LIMPEZA_ASEO', 'Limpieza y Aseo'), ('TECNOLOGIA_INFORMATICA', 'Tecnologia e Informatica'), ('GASTOS_LEGALES', 'Gastos Legales'), ('TRIBUTARIOS', 'Gastos Tributarios'), ('OTROS', 'Otros Gastos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVOS', 'Administrativos'), ('MATERIA_PRIMA', 'Materia Prima'), ('MANUTENCION', 'Mantenimiento'), ('VIATICOS', 'Viaticos'), ('SERVICIOS_PUBLICOS', 'Servicios Publicos'), ('TRANSPORTE', 'Transporte'), ('COMUNICACIONES', 'Comunicaciones'), ('SEGUROS', 'Seguros'), ('ARRIENDOS', 'Arriendos'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('PUBLICIDAD', 'Publicidad y Marketing'), ('CAPACITACION', 'Capacitacion'), ('HERRAMIENTAS', 'Herramientas y Equipos'), ('INSUMOS', 'Insumos y Materiales'), ('ENERGIA', 'Energia y Combustibles'), ('LIMPEZA', 'Limpieza y Aseo'), ('SEGURIDAD', 'Seguridad'), ('TECNOLOGIA', 'Tecnologia e Informatica'), ('LEGALES', 'Gastos Legales'), ('TRIBUTARIOS', 'Gastos Tributarios'), ('OTROS', 'Otros Gastos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='codigo_contable',
            field=models.CharField(blank=True, choices=[('510506', '510506 - Honorarios'), ('510515', '510515 - Servicios Tecnicos'), ('510518', '510518 - Servicios de Aseo y Vigilancia'), ('510521', '510521 - Arrendamientos'), ('510524', '510524 - Contribuciones y Afiliaciones'), ('510527', '510527 - Seguros'), ('510530', '510530 - Servicios Publicos'), ('510533', '510533 - Gastos de Viaje'), ('510536', '510536 - Transporte, Fletes y Acarreos'), ('510545', '510545 - Publicidad, Propaganda y Promocion'), ('510554', '510554 - Utiles y Papeleria'), ('510557', '510557 - Combustibles y Lubricantes'), ('510560', '510560 - Envases y Empaques'), ('510563', '510563 - Elementos de Aseo y Cafeteria'), ('510566', '510566 - Costos y Gastos de Sistemas'), ('510569', '510569 - Mantenimiento y Reparaciones'), ('510595', '510595 - Gastos Legales'), ('510598', '510598 - Amortizaciones'), ('519595', '519595 - Gastos Diversos'), ('520506', '520506 - Honorarios (Ventas)'), ('520521', '520521 - Arrendamientos (Ventas)'), ('520530', '520530 - Servicios Publicos (Ventas)'), ('520545', '520545 - Publicidad, Propaganda y Promocion (Ventas)'), ('520554', '520554 - Utiles y Papeleria (Ventas)'), ('520569', '520569 - Mantenimiento y Reparaciones (Ventas)'), ('530501', '530501 - Financieros'), ('530506', '530506 - Perdida en Venta y Retiro de Bienes'), ('530520', '530520 - Gastos Extraordinarios'), ('530530', '530530 - Comisiones Bancarias'), ('110505', '110505 - Caja General'), ('111005', '111005 - Bancos - Cuenta Corriente'), ('111006', '111006 - Bancos - Cuenta de Ahorros')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='documento_soporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gasto', to='tenant_gastos.documentosoporte', verbose_name='Documento Soporte'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='periodo',
            field=models.CharField(max_length=7, verbose_name='Periodo Contable'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
        migrations.AddConstraint(
            model_name='documentosoporte',
            constraint=models.UniqueConstraint(fields=('resolucion_dian', 'consecutivo'), name='unique_ds_resolucion_consecutivo'),
        ),
        migrations.AddConstraint(
            model_name='documentosoporte',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empresa', 'vendedor_nit', 'numero_factura_proveedor'), name='unique_ds_vendedor_factura'),
        ),
    ]
