# Generated by Django 6.0.5 on 2026-05-06 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0003_documentosoporte_motivo_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal (Lookup Field)', unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal (Lookup Field)', unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='resoluciondian',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal (Lookup Field)', unique=True, verbose_name='UUID'),
        ),
    ]
