# Generated by Django 5.0.14 on 2026-05-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('perfil', '0005_tenantprofile_rol'),
        ('tenant_gastos', '0007_remove_gasto_tenant_gast_centro__968db9_idx_and_more'),
        ('tenant_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentosoporte',
            name='unique_ds_vendedor_documento',
        ),
        migrations.RemoveIndex(
            model_name='documentosoporte',
            name='tenant_gast_vendedo_19f9db_idx',
        ),
        migrations.RemoveField(
            model_name='documentosoporte',
            name='vendedor_direccion',
        ),
        migrations.RemoveField(
            model_name='documentosoporte',
            name='vendedor_nit',
        ),
        migrations.RemoveField(
            model_name='documentosoporte',
            name='vendedor_nombre',
        ),
        migrations.RemoveField(
            model_name='documentosoporte',
            name='vendedor_telefono',
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_soporte', to='tenant_proveedores.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='documentosoporte',
            index=models.Index(fields=['proveedor', 'numero_documento_proveedor'], name='tenant_gast_proveed_e80c16_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentosoporte',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empresa', 'proveedor', 'numero_documento_proveedor'), name='unique_ds_vendedor_documento'),
        ),
    ]
