# Generated by Django 5.2.13 on 2026-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('tenant_gastos', '0008_remove_documentosoporte_unique_ds_vendedor_documento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gasto',
            name='tenant_gast_empresa_d06d8d_idx',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa'], name='tenant_gast_empresa_1ed92b_idx'),
        ),
    ]
