# Generated by Django 5.0.14 on 2026-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('perfil', '0005_tenantprofile_rol'),
        ('tenant_gastos', '0009_remove_gasto_tenant_gast_empresa_d06d8d_idx_and_more'),
        ('tenant_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='documento_soporte',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='empresa',
        ),
        migrations.RemoveIndex(
            model_name='documentosoporte',
            name='tenant_gast_prefijo_2889a4_idx',
        ),
        migrations.RemoveField(
            model_name='documentosoporte',
            name='prefijo',
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='categoria_contable',
            field=models.CharField(blank=True, choices=[('ARRENDAMIENTOS', 'Arrendamientos'), ('SERVICIOS_PUBLICOS', 'Servicios Publicos'), ('PAPELERIA_UTILES', 'Papeleria y Utiles'), ('MANTENIMIENTO_REPARACIONES', 'Mantenimiento y Reparaciones'), ('EQUIPOS_HERRAMIENTAS', 'Equipos y Herramientas'), ('LICENCIAS_SOFTWARE', 'Licencias y Software'), ('HOSTING_DOMINIO', 'Hosting y Dominios'), ('TRANSPORTE_FLETES', 'Transporte y Fletes'), ('COMBUSTIBLE', 'Combustible'), ('VIATICOS', 'Viaticos'), ('PUBLICIDAD_MARKETING', 'Publicidad y Marketing'), ('SEGUROS', 'Seguros'), ('IMPUESTOS_TASAS', 'Impuestos, Tasas y Contribuciones'), ('HONORARIOS', 'Honorarios'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('ASEO_CAFETERIA', 'Aseo y Cafeteria'), ('VIGILANCIA_SEGURIDAD', 'Vigilancia y Seguridad'), ('CAPACITACION', 'Capacitacion'), ('GASTOS_FINANCIEROS', 'Gastos Financieros'), ('COMISIONES_BANCARIAS', 'Comisiones Bancarias'), ('SUSCRIPCIONES', 'Suscripciones'), ('ELEMENTOS_PROTECCION', 'Elementos de Proteccion'), ('MATERIALES_INSUMOS', 'Materiales e Insumos'), ('ADECUACIONES_INSTALACIONES', 'Adecuaciones e Instalaciones'), ('COMUNICACIONES', 'Comunicaciones'), ('ENERGIA', 'Energia'), ('LIMPEZA_ASEO', 'Limpieza y Aseo'), ('TECNOLOGIA_INFORMATICA', 'Tecnologia e Informatica'), ('GASTOS_LEGALES', 'Gastos Legales'), ('TRIBUTARIOS', 'Gastos Tributarios'), ('OTROS', 'Otros Gastos')], max_length=50, null=True, verbose_name='Categoria Contable'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resoluciondian',
            name='consecutivo',
            field=models.IntegerField(db_index=True, default=1, editable=False, verbose_name='Siguiente Consecutivo'),
        ),
        migrations.AddIndex(
            model_name='documentosoporte',
            index=models.Index(fields=['categoria_contable'], name='tenant_gast_categor_d6ac75_idx'),
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
