# Generated by Django 5.0.14 on 2026-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0010_remove_gasto_documento_soporte_remove_gasto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Sin Retefuente'), ('0', '0% - Sin Retefuente'), ('0.0', '0% - Sin Retefuente'), ('0.04', '4% - Servicios (Declarantes)'), ('0.06', '6% - Servicios (No Declarantes)'), ('0.10', '10% - Honorarios y Consultoria (No declarante)'), ('0.11', '11% - Honorarios y Consultoria (Declarante)')], default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Exento'), ('0', '0% - Exento'), ('0.0', '0% - Exento'), ('0.0069', '0.69%'), ('0.00966', '0.966%'), ('0.01104', '1.104%')], default='0.00', max_length=10),
        ),
    ]
