# Generated by Django 5.2.13 on 2026-05-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_gastos", "0011_alter_documentosoporte_retefuente_porcentaje_and_more"),
        ("tenant_proveedores", "0005_alter_proveedor_nombre_comercial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentosoporte",
            name="proveedor",
            field=models.ForeignKey(
                help_text="Cuando se elimina el proveedor, se eliminan en cascada todos sus documentos soporte",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_soporte",
                to="tenant_proveedores.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
