# Generated by Django 5.0.14 on 2026-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0012_alter_documentosoporte_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='cuenta_contrapartida_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID de la CuentaContable de balance (ej. 2205 Cuentas por Pagar). Usado por contabilidad como contrapartida del gasto.', null=True, verbose_name='Cuenta de Contrapartida (UUID)'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='cuenta_gasto_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID de la CuentaContable de resultado (ej. 5105 Gastos). Usado por contabilidad para asientos automaticos.', null=True, verbose_name='Cuenta de Gasto/Egreso (UUID)'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
