# Generated by Claude Code on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0013_add_cuenta_contable_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosoporte',
            name='cuenta_contrapartida_uuid',
        ),
    ]
