# Generated by Django 5.0.14 on 2026-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0014_remove_cuenta_contrapartida_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosoporte',
            name='cuenta_gasto_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID de la CuentaContable de resultado (ej. 5105 Gastos). Contabilidad determina la contrapartida segun tipo de transaccion.', null=True, verbose_name='Cuenta de Gasto/Egreso (UUID)'),
        ),
    ]
