# Generated by Django 5.0.14 on 2026-05-17 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0016_add_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Monto Retefuente [DEPRECATED v3.7.1]'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='retefuente_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Sin Retefuente'), ('0', '0% - Sin Retefuente'), ('0.0', '0% - Sin Retefuente'), ('0.04', '4% - Servicios (Declarantes)'), ('0.06', '6% - Servicios (No Declarantes)'), ('0.10', '10% - Honorarios y Consultoria (No declarante)'), ('0.11', '11% - Honorarios y Consultoria (Declarante)')], default='0.00', editable=False, max_length=10, verbose_name='% Retefuente [DEPRECATED v3.7.1]'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Monto ReteICA [DEPRECATED v3.7.1]'),
        ),
        migrations.AlterField(
            model_name='documentosoporte',
            name='reteica_porcentaje',
            field=models.CharField(choices=[('0.00', '0% - Exento'), ('0', '0% - Exento'), ('0.0', '0% - Exento'), ('0.0069', '0.69%'), ('0.00966', '0.966%'), ('0.01104', '1.104%')], default='0.00', editable=False, max_length=10, verbose_name='% ReteICA [DEPRECATED v3.7.1]'),
        ),
    ]
