# Generated by Django 5.0.14 on 2026-05-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0017_alter_documentosoporte_retefuente_and_more'),
        ('tenant_inventario', '0007_add_factura_vinculacion_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='activo_relacionado',
            field=models.ForeignKey(blank=True, help_text='Activo Fijo opcional asociado a este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_soporte', to='tenant_inventario.activofijo', verbose_name='Activo Fijo Relacionado'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='producto_relacionado',
            field=models.ForeignKey(blank=True, help_text='Producto opcional de inventario asociado a este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_soporte', to='tenant_inventario.producto', verbose_name='Producto Relacionado'),
        ),
        migrations.AddField(
            model_name='documentosoporte',
            name='servicio_relacionado',
            field=models.ForeignKey(blank=True, help_text='Servicio opcional de inventario asociado a este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_soporte', to='tenant_inventario.servicio', verbose_name='Servicio Relacionado'),
        ),
    ]
