# Generated by Django 5.2.13 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_gastos", "0018_documentosoporte_activo_relacionado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentosoporte",
            name="activo_relacionado",
        ),
        migrations.RemoveField(
            model_name="documentosoporte",
            name="producto_relacionado",
        ),
        migrations.RemoveField(
            model_name="documentosoporte",
            name="servicio_relacionado",
        ),
        migrations.AddField(
            model_name="documentosoporte",
            name="movimiento_inventario_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Vinculacion transaccional al Kardex de Inventario",
                null=True,
            ),
        ),
    ]
