# Generated by Django 5.0.14 on 2026-05-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0019_remove_documentosoporte_activo_relacionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosoporte',
            name='cuenta_gasto_uuid',
        ),
    ]
