# Generated by Django 5.2.13 on 2026-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_gastos", "0020_remove_documentosoporte_cuenta_gasto_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentosoporte",
            name="retefuente",
        ),
        migrations.RemoveField(
            model_name="documentosoporte",
            name="retefuente_porcentaje",
        ),
        migrations.RemoveField(
            model_name="documentosoporte",
            name="reteica",
        ),
        migrations.RemoveField(
            model_name="documentosoporte",
            name="reteica_porcentaje",
        ),
    ]
