# Generated by Django 5.0.14 on 2026-06-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_gastos', '0021_remove_deprecated_retencion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede de la empresa donde se origina el gasto. Opcional — si no se asigna aplica a toda la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='empresa.sede', verbose_name='Sede'),
        ),
    ]
