# Generated by Django 5.0.14 on 2026-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_gastos', '0023_documentosoporte_proyecto_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosoporte',
            name='facturable',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si este gasto se factura al cliente (impacta el valor cotizado) o es un costo interno no facturable.', verbose_name='Facturable'),
        ),
    ]
