# Generated by Django 5.2.13 on 2026-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_proveedores", "0002_add_uuid_to_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="aplica_retefuente",
            field=models.BooleanField(
                default=False, verbose_name="Aplica Retención en la Fuente"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="aplica_reteica",
            field=models.BooleanField(
                default=False, verbose_name="Aplica Retención de ICA"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="aplica_reteiva",
            field=models.BooleanField(
                default=False, verbose_name="Aplica Retención de IVA"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="es_retenedor",
            field=models.BooleanField(
                default=False, verbose_name="Es Agente Retenedor"
            ),
        ),
    ]
