# Generated by Django 5.2.13 on 2026-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenant_proveedores",
            "0003_proveedor_aplica_retefuente_proveedor_aplica_reteica_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="retefuente_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Porcentaje Retefuente",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="reteica_porcentaje",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=5,
                verbose_name="Porcentaje ReteICA",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="reteiva_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Porcentaje ReteIVA",
            ),
        ),
    ]
