# Generated by Django 5.0.14 on 2026-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0004_proveedor_retefuente_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre de marca o fantasía', max_length=200),
        ),
    ]
