# Generated by Django 5.0.14 on 2026-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0005_alter_proveedor_nombre_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_contable_uuid',
            field=models.UUIDField(blank=True, help_text='Cuenta PUC nivel 6 (Pasivos/Proveedores)', null=True),
        ),
    ]
