# Generated by Django 5.0.14 on 2026-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0006_proveedor_cuenta_contable_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='codigo_contable',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cuenta_contable_uuid',
        ),
    ]
