# Generated by Django 5.0.14 on 2026-06-02 22:05 (amended: removed cuenta_contable_uuid, codigo_contable)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0007_remove_proveedor_codigo_contable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='actividad_economica_ciiu',
            field=models.CharField(blank=True, help_text='Codigo CIIU Principal', max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='aplica_retefuente',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion en la Fuente'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='aplica_reteica',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion de ICA'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='aplica_reteiva',
            field=models.BooleanField(default=False, verbose_name='Aplica Retencion de IVA'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(
                help_text='SSoT Empresa del tenant',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='proveedores',
                to='empresa.empresa',
            ),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre de marca o fantasia', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_documento',
            field=models.CharField(help_text='Sin digito de verificacion', max_length=32),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=30, help_text='Dias de credito estandar'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_tributario',
            field=models.CharField(
                choices=[
                    ('SIMPLE', 'Regimen Simple'),
                    ('ORDINARIO', 'Regimen Ordinario'),
                    ('NO_RESP', 'No responsable de IVA'),
                ],
                default='ORDINARIO',
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(
                choices=[
                    ('NIT', 'NIT'),
                    ('CC', 'Cedula de ciudadania'),
                    ('CE', 'Cedula de extranjeria'),
                    ('PA', 'Pasaporte'),
                ],
                default='NIT',
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_persona',
            field=models.CharField(
                choices=[
                    ('NATURAL', 'Persona natural'),
                    ('JURIDICA', 'Persona juridica'),
                ],
                default='JURIDICA',
                max_length=10,
            ),
        ),
    ]
