# Generated by Django 5.0.14 on 2026-06-02 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0008_add_contable_ubicacion_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='proveedor',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
                ),
                migrations.AlterField(
                    model_name='proveedor',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
                ),
            ],
            database_operations=[]
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('factura_origen_uuid', models.UUIDField(db_index=True, help_text='Referencia blanda a Factura (naturaleza=COMPRA). Sin FK directa.')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la factura de compra al momento de registrar.', max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, help_text='Saldo aun no pagado. Se reduce con cada abono registrado.', max_digits=15)),
                ('fecha_vencimiento', models.DateField(db_index=True, help_text='Fecha limite de pago segun plazo acordado.')),
                ('estado_pago', models.CharField(choices=[('NO_PAGADA', 'No Pagada'), ('PAGO_PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada')], db_index=True, default='NO_PAGADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(help_text='Proveedor titular de esta cuenta por pagar.', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='tenant_proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['empresa', 'estado_pago'], name='tenant_prov_empresa_54c74e_idx'), models.Index(fields=['empresa', 'proveedor', 'estado_pago'], name='tenant_prov_empresa_c792a2_idx'), models.Index(fields=['factura_origen_uuid'], name='tenant_prov_factura_a3e009_idx')],
            },
        ),
    ]
