# Generated by Django 5.0.14 on 2026-06-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0009_alter_proveedor_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaPorPagar',
        ),
    ]
