# Generated by Django 5.0.14 on 2026-06-03 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0011_recreate_cuentaporpagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_factura', models.CharField(help_text='Numero de factura de compra o documento equivalente', max_length=50)),
                ('factura_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID de la Factura COMPRA de origen (soft reference, sin FK).', null=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de expedicion de la factura de compra')),
                ('fecha_vencimiento', models.DateField(db_index=True, help_text='Fecha limite pactada para el pago')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total de la factura incluyendo impuestos y retenciones', max_digits=18)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto acumulado de abonos o pagos realizados', max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Saldo remanente = valor_total - valor_pagado (calculado automaticamente)', max_digits=18)),
                ('estado_pago', models.CharField(choices=[('SIN_PAGO', 'Sin pago'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada')], db_index=True, default='SIN_PAGO', max_length=15)),
                ('fecha_ultimo_pago', models.DateField(blank=True, help_text='Fecha del ultimo abono registrado', null=True)),
                ('referencia_pago', models.CharField(blank=True, help_text='Numero de comprobante o referencia del ultimo pago', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(help_text='SSoT Empresa del tenant', on_delete=django.db.models.deletion.PROTECT, related_name='carteras', to='empresa.empresa')),
                ('proveedor', models.ForeignKey(help_text='Proveedor acreedor de la deuda', on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='tenant_proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cartera',
                'verbose_name_plural': 'Carteras',
                'ordering': ['fecha_vencimiento', 'numero_factura'],
                'indexes': [models.Index(fields=['empresa', 'estado_pago'], name='tenant_prov_empresa_fe58d6_idx'), models.Index(fields=['empresa', 'proveedor', 'estado_pago'], name='tenant_prov_empresa_3ad3f5_idx'), models.Index(fields=['numero_factura'], name='tenant_prov_numero__970137_idx'), models.Index(fields=['fecha_vencimiento'], name='tenant_prov_fecha_v_267142_idx'), models.Index(fields=['factura_uuid'], name='tenant_prov_factura_297882_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartera',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'numero_factura'), name='uniq_cartera_factura_proveedor'),
        ),
    ]
