# Generated by Django 5.0.14 on 2026-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0012_add_cartera_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaPorPagar',
        ),
    ]
