# Generated by Django 5.0.14 on 2026-06-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0013_remove_cuentaporpagar_unify_cartera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartera',
            new_name='CuentasPagar',
        ),
        migrations.RenameIndex(
            model_name='cuentaspagar',
            new_name='tenant_prov_empresa_43a306_idx',
            old_name='tenant_prov_empresa_fe58d6_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaspagar',
            new_name='tenant_prov_empresa_e67b7c_idx',
            old_name='tenant_prov_empresa_3ad3f5_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaspagar',
            new_name='tenant_prov_numero__e7dff6_idx',
            old_name='tenant_prov_numero__970137_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaspagar',
            new_name='tenant_prov_fecha_v_b1cdda_idx',
            old_name='tenant_prov_fecha_v_267142_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaspagar',
            new_name='tenant_prov_factura_70efe5_idx',
            old_name='tenant_prov_factura_297882_idx',
        ),
    ]
