# Generated by Django 5.0.14 on 2026-06-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proveedores', '0014_rename_cartera_cuentaspagar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentaspagar',
            options={'ordering': ['fecha_vencimiento', 'numero_factura'], 'verbose_name': 'Cuentas por Pagar', 'verbose_name_plural': 'Cuentas por Pagar'},
        ),
    ]
