# Generated by Django 5.0.14 on 2026-06-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0015_update_cuentaspagar_verbose_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuentaspagar',
            name='uniq_cartera_factura_proveedor',
        ),
        migrations.AlterField(
            model_name='cuentaspagar',
            name='empresa',
            field=models.ForeignKey(help_text='SSoT Empresa del tenant', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_pagar', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentaspagar',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor acreedor de la deuda', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_pagar', to='tenant_proveedores.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='cuentaspagar',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'numero_factura'), name='uniq_cuentas_pagar_factura_proveedor'),
        ),
    ]
