# Generated by Django 5.0.14 on 2026-06-10 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_proveedores', '0017_drop_contable_columns_from_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], default='CC', help_text='Tipo de documento de identificacion', max_length=5)),
                ('numero_documento', models.CharField(help_text='Numero de documento (sin digito verificador)', max_length=32)),
                ('nombre_completo', models.CharField(help_text='Nombre completo de la persona', max_length=255)),
                ('email_contacto', models.EmailField(blank=True, help_text='Email de contacto directo', max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, help_text='Numero de telefono de contacto', max_length=50)),
                ('cargo', models.CharField(default='Representante Legal', help_text='Titulo o rol en la organizacion', max_length=100)),
                ('es_principal', models.BooleanField(default=True, help_text='Si es True, es el representante principal para correspondencia oficial')),
                ('empresa', models.ForeignKey(help_text='SSoT Empresa del tenant', on_delete=django.db.models.deletion.PROTECT, related_name='representantes_proveedor', to='empresa.empresa')),
                ('proveedor', models.ForeignKey(help_text='Proveedor al que representa', on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='tenant_proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['-es_principal', 'nombre_completo'],
                'indexes': [models.Index(fields=['empresa', 'proveedor'], name='tenant_prov_empresa_33dc16_idx'), models.Index(fields=['empresa', 'es_principal'], name='tenant_prov_empresa_622d86_idx'), models.Index(fields=['numero_documento'], name='tenant_prov_numero__2a69dd_idx'), models.Index(fields=['email_contacto'], name='tenant_prov_email_c_aefc24_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='representante',
            constraint=models.UniqueConstraint(fields=('empresa', 'proveedor', 'numero_documento'), name='uniq_representante_empresa_proveedor_doc'),
        ),
    ]
