# Generated by Django 5.0.14 on 2026-03-23 18:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailIngestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Servidor')),
                ('port', models.PositiveIntegerField(default=993, verbose_name='Puerto')),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=10, verbose_name='Protocolo')),
                ('ssl', models.BooleanField(default=True, verbose_name='Usar SSL/TLS')),
                ('username', models.CharField(max_length=255, verbose_name='Usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('mailbox', models.CharField(default='INBOX', max_length=255, verbose_name='Carpeta')),
                ('mark_as_seen', models.BooleanField(default=True, verbose_name='Marcar como leído')),
                ('move_processed_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mover procesados a')),
                ('max_attachment_mb', models.PositiveIntegerField(default=50, verbose_name='Límite adjuntos (MB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Ingesta por Correo (DEPRECADO)',
                'verbose_name_plural': 'Configuraciones de Ingesta por Correo (DEPRECADO)',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('numero', models.CharField(help_text='Ej: FST354', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo')),
                ('consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('tipo', models.CharField(choices=[('FE', 'Factura Electrónica'), ('NC', 'Nota Crédito'), ('ND', 'Nota Débito')], default='FE', max_length=2, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('naturaleza', models.CharField(blank=True, choices=[('VENTA', 'Venta (emitida por el tenant)'), ('COMPRA', 'Compra (recibida por el tenant)')], help_text='VENTA si el tenant es emisor; COMPRA si el tenant es receptor. Se calcula automáticamente en importación UBL comparando NITs normalizados.', max_length=10, null=True, verbose_name='Naturaleza (venta/compra)')),
                ('categoria', models.CharField(choices=[('PRODUCTO', 'Productos'), ('SERVICIO', 'Servicios'), ('MIXTO', 'Mixto')], default='SERVICIO', max_length=10, verbose_name='Categoría (producto/servicio/mixto)')),
                ('ubl_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='UBL Version')),
                ('customization_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomizationID')),
                ('profile_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='ProfileID')),
                ('profile_execution_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ProfileExecutionID')),
                ('invoice_type_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='InvoiceTypeCode')),
                ('fecha_emision', models.DateTimeField(verbose_name='Fecha/hora de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('emisor_nit', models.CharField(max_length=20, verbose_name='NIT Emisor')),
                ('emisor_razon_social', models.CharField(max_length=200, verbose_name='Razón Social Emisor')),
                ('emisor_direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección Emisor')),
                ('emisor_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email Emisor')),
                ('emisor_telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono Emisor')),
                ('emisor_actividad_ciiu', models.CharField(blank=True, max_length=10, null=True, verbose_name='CIIU Emisor')),
                ('receptor_nit', models.CharField(max_length=20, verbose_name='NIT Receptor')),
                ('receptor_razon_social', models.CharField(max_length=200, verbose_name='Razón Social Receptor')),
                ('receptor_direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección Receptor')),
                ('receptor_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email Receptor')),
                ('receptor_telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono Receptor')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forma_pago', models.CharField(blank=True, max_length=30, null=True, verbose_name='Forma de pago')),
                ('medio_pago_codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='PaymentMeansCode')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago')),
                ('cufe', models.CharField(blank=True, db_index=True, help_text='Código Único de Facturación Electrónica (clave legal de la DIAN para idempotencia). Usado para pre-validación rápida en batch processing.', max_length=128, null=True, unique=True, verbose_name='CUFE')),
                ('qr_code', models.TextField(blank=True, help_text='Texto multilínea del código QR', null=True, verbose_name='QR raw')),
                ('qr_url', models.URLField(blank=True, help_text='URL del código QR (puede ser muy larga)', max_length=1024, null=True, verbose_name='URL QR DIAN')),
                ('autorizacion_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Autorización DIAN')),
                ('autorizacion_prefijo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo autorizado')),
                ('autorizacion_rango_desde', models.IntegerField(blank=True, null=True, verbose_name='Rango desde')),
                ('autorizacion_rango_hasta', models.IntegerField(blank=True, null=True, verbose_name='Rango hasta')),
                ('autorizacion_vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigencia inicio')),
                ('autorizacion_vigencia_fin', models.DateField(blank=True, null=True, verbose_name='Vigencia fin')),
                ('dian_validation_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Validación DIAN')),
                ('dian_validation_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Validación')),
                ('dian_validation_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Validación')),
                ('dian_validation_hora', models.TimeField(blank=True, null=True, verbose_name='Hora Validación')),
                ('dian_response_xml', models.TextField(blank=True, null=True, verbose_name='ApplicationResponse XML')),
                ('xml_content', models.TextField(blank=True, null=True, verbose_name='XML UBL completo (Deprecado)')),
                ('xml_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta XML')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='FacturaAnexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubl_xml', models.TextField(blank=True, help_text='Contenido completo del XML UBL de la factura', null=True, verbose_name='XML UBL completo')),
                ('application_response_xml', models.TextField(blank=True, help_text='XML de respuesta de la DIAN (ApplicationResponse)', null=True, verbose_name='ApplicationResponse XML')),
                ('pdf_file', models.FileField(blank=True, help_text='Archivo PDF de la factura (representación gráfica)', null=True, upload_to='facturas/pdfs/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.OneToOneField(help_text='Factura asociada', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='facturas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Anexo de Factura',
                'verbose_name_plural': 'Anexos de Factura',
                'db_table': 'facturas_factura_anexos',
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('linea_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID línea UBL')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del ítem')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad_medida', models.CharField(default='UND', help_text='Ej: UN, ZZ, UND', max_length=10, verbose_name='Unidad de Medida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('es_servicio', models.BooleanField(default=False, verbose_name='¿Es servicio?')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
                'ordering': ['factura', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='MailInboxState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_uid', models.BigIntegerField(blank=True, db_index=True, help_text='Último UID IMAP procesado. NULL = primera ejecución (histórico completo)', null=True, verbose_name='Último UID procesado')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Fecha/hora de la última ejecución exitosa', null=True, verbose_name='Última ejecución')),
                ('total_processed', models.PositiveIntegerField(default=0, help_text='Total acumulado de mensajes procesados', verbose_name='Total procesados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('mailbox_config', models.ForeignKey(help_text='Configuración de correo asociada', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_states', to='empresa.mailinboxconfig', verbose_name='Configuración de buzón')),
            ],
            options={
                'verbose_name': 'Estado de Buzón IMAP',
                'verbose_name_plural': 'Estados de Buzón IMAP',
            },
        ),
        migrations.CreateModel(
            name='MailIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('task_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID Tarea Celery')),
                ('naturaleza', models.CharField(choices=[('VENTA', 'Venta (emitida por el tenant)'), ('COMPRA', 'Compra (recibida por el tenant)')], default='VENTA', max_length=10, verbose_name='Naturaleza')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCEL_REQUESTED', 'CANCEL_REQUESTED'), ('CANCELED', 'CANCELED'), ('ABORTED', 'ABORTED')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('counts', models.JSONField(blank=True, default=dict, help_text='Métricas: xml_detected, imported, duplicates, errors', verbose_name='Conteos')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Detalles de ejecución (JSON)', verbose_name='Resumen')),
                ('started_by', models.ForeignKey(blank=True, help_text='Operador del tenant que inició la ingesta de correo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_ingestion_runs', to='perfil.tenantprofile', verbose_name='Iniciado por')),
            ],
            options={
                'verbose_name': 'Ejecución de Ingesta por Correo',
                'verbose_name_plural': 'Ejecuciones de Ingesta por Correo',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ej: NC135', max_length=50, unique=True, verbose_name='Número de Nota Crédito')),
                ('cude', models.CharField(help_text='Código Único de Documento Electrónico (identificador legal de la nota)', max_length=128, unique=True, verbose_name='CUDE')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/hora de Emisión')),
                ('moneda', models.CharField(default='COP', max_length=8, verbose_name='Moneda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo de la nota crédito', verbose_name='Motivo')),
                ('ref_factura_numero', models.CharField(blank=True, default='', help_text='Número de la factura a la que aplica esta nota crédito', max_length=50, verbose_name='Número Factura Referenciada')),
                ('ref_factura_cufe', models.CharField(blank=True, default='', help_text='CUFE de la factura a la que aplica esta nota crédito', max_length=128, verbose_name='CUFE Factura Referenciada')),
                ('xml_content', models.TextField(blank=True, default='', help_text='Contenido completo del XML UBL de la nota crédito', verbose_name='XML UBL completo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.OneToOneField(help_text='Factura a la que aplica esta Nota Crédito (1:1).', on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito', to='facturas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota Crédito',
                'verbose_name_plural': 'Notas Crédito',
                'ordering': ['-fecha_emision', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='facturas_fa_numero_46a66e_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='facturas_fa_fecha_e_6a1db1_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturas_fa_estado_de2e38_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['naturaleza'], name='facturas_fa_natural_981d53_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa'], name='facturas_fa_empresa_ae2718_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinboxstate',
            index=models.Index(fields=['mailbox_config', 'last_seen_uid'], name='facturas_ma_mailbox_1ecb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='mailinboxstate',
            index=models.Index(fields=['last_run_at'], name='facturas_ma_last_ru_0840fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailinboxstate',
            unique_together={('mailbox_config',)},
        ),
        migrations.AddIndex(
            model_name='mailingestionrun',
            index=models.Index(fields=['task_id'], name='facturas_ma_task_id_ee8c31_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingestionrun',
            index=models.Index(fields=['status'], name='facturas_ma_status_67ef56_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingestionrun',
            index=models.Index(fields=['started_at'], name='facturas_ma_started_866f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['cude'], name='facturas_no_cude_714a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['numero'], name='facturas_no_numero_0c3300_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['fecha_emision'], name='facturas_no_fecha_e_e078ac_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['factura'], name='facturas_no_factura_79b173_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['empresa'], name='facturas_no_empresa_719a37_idx'),
        ),
    ]
