# Generated by Django 5.0.14 on 2026-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cufe',
            field=models.CharField(blank=True, db_index=True, help_text='Código Único de Facturación Electrónica (clave legal de la DIAN para idempotencia). Usado para pre-validación rápida en batch processing.', max_length=128, null=True, unique=True, verbose_name='CUFE'),
        ),
    ]
