# Generated by Django 5.0 on 2026-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaanexos',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Archivo PDF de la factura (representación gráfica)', null=True, upload_to='facturas/pdfs/', verbose_name='Archivo PDF'),
        ),
    ]
