# Generated by Django 5.0 on 2026-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_add_pdf_file_to_factura_anexos'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='factura',
            name='facturas_fa_cufe_5bbd51_idx',
        ),
        migrations.AlterField(
            model_name='factura',
            name='cufe',
            field=models.CharField(blank=True, db_index=True, help_text='Código Único de Facturación Electrónica (clave legal de la DIAN para idempotencia)', max_length=128, null=True, unique=True, verbose_name='CUFE'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='naturaleza',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta (emitida por el tenant)'), ('COMPRA', 'Compra (recibida por el tenant)')], help_text='VENTA si el tenant es emisor; COMPRA si el tenant es receptor. Se calcula automáticamente en importación UBL comparando NITs normalizados.', max_length=10, null=True, verbose_name='Naturaleza (venta/compra)'),
        ),
    ]
