# Generated by Django 5.0.14 on 2026-03-27 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_empresa_empresa'),
        ('facturas', '0002_factura_idx_fact_aceptadas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinboxstate',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailingestionconfig',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailingestionrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailingestionrun',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailingestionrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado'),
        ),
    ]
