# Generated by Django 5.0.14 on 2026-03-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_mailinboxstate_empresa_mailingestionconfig_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='factura',
            name='facturas_fa_empresa_ae2718_idx',
        ),
        migrations.RemoveIndex(
            model_name='notacredito',
            name='facturas_no_empresa_719a37_idx',
        ),
    ]
