# Generated by Django 5.2.13 on 2026-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturas",
            "0005_factura_retefuente_factura_reteica_factura_reteiva_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("NO_PAGADA", "No Pagada"),
                    ("PAGO_PARCIAL", "Pago Parcial"),
                    ("PAGADA", "Pagada"),
                ],
                default="NO_PAGADA",
                max_length=20,
                verbose_name="Estado de Pago",
            ),
        ),
    ]
