# Generated by Django 5.2.13 on 2026-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0006_factura_estado_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cuenta_contable_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Cartera/Ingreso/Gasto)",
                null=True,
            ),
        ),
    ]
