# Generated by Django 5.2.13 on 2026-05-13 16:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0007_factura_cuenta_contable_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfactura",
            name="porcentaje_reteiva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="valor_reteiva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
