# Generated by Django 5.0.14 on 2026-05-13 18:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_deprecate_retention_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='retefuente',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='[DEPRECATED v3.7.1] Leer desde Contabilidad.Retencion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Retención en la Fuente [DEPRECATED v3.7.1]'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='reteica',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='[DEPRECATED v3.7.1] Leer desde Contabilidad.Retencion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ReteICA [DEPRECATED v3.7.1]'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='reteiva',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='[DEPRECATED v3.7.1] Leer desde Contabilidad.Retencion', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ReteIVA [DEPRECATED v3.7.1]'),
        ),
    ]
