# Generated by Django 5.0.14 on 2026-05-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_factura_uuid'),
        ('contabilidad', '0007_migrate_retenciones_from_facturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='retefuente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='reteica',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='reteiva',
        ),
    ]
