# Generated by Django 5.0.14 on 2026-05-13 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_remove_factura_retefuente_remove_factura_reteica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único universal (usado en API URLs)', unique=True, verbose_name='UUID'),
        ),
    ]
