# Generated by Django 5.0.14 on 2026-05-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0015_add_uuid_itemfactura_notacredito'),
        ('tenant_cotizaciones', '0004_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Cotización opcional asociada a esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_asociadas', to='tenant_cotizaciones.cotizacion', verbose_name='Cotización vinculada'),
        ),
    ]
