# Generated by Django 5.2.13 on 2026-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0016_factura_cotizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factura",
            name="cotizacion",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="notacredito",
            name="uuid",
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="item_inventario_codigo",
            field=models.CharField(
                blank=True,
                help_text="Snapshot del codigo de inventario al momento de vincular.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="item_inventario_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRODUCTO", "Producto de Inventario"),
                    ("SERVICIO", "Servicio de Inventario"),
                ],
                help_text="Tipo de item de inventario referenciado.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="item_inventario_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID del Producto o Servicio de Inventario. Referencia soft, sin FK.",
                null=True,
            ),
        ),
    ]
