# Generated by Django 5.2.13 on 2026-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0017_remove_factura_cotizacion_remove_itemfactura_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cotizacion_uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID de cotización vinculada (soft reference, permite orfandad)",
                null=True,
            ),
        ),
    ]
