# Generated by Django 5.0.14 on 2026-05-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0019_factura_cotizacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cotizacion_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID de cotizacion vinculada (soft reference, permite orfandad)', null=True),
        ),
    ]
