# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0021_factura_cliente_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedor_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID del proveedor vinculado para facturas de compra', null=True),
        ),
    ]
