# Generated by Django 5.0.14 on 2026-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0023_restore_itemfactura_notacredito_uuid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa_id', 'cliente_uuid'], name='idx_fact_empresa_cliente_uuid'),
        ),
    ]
