# Generated by Django 5.0.14 on 2026-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0025_add_idx_empresa_proveedor_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cuenta_contable_uuid',
        ),
    ]
