# Generated by Django 5.2.13 on 2026-06-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0026_remove_factura_cuenta_contable_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailIngestionConfig",
        ),
    ]
