# Generated by Django 5.0.14 on 2026-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0028_factura_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cufe',
            field=models.CharField(blank=True, db_index=True, help_text='Código Único de Facturación Electrónica (clave legal de la DIAN para idempotencia). Usado para pre-validación rápida en batch processing.', max_length=200, null=True, unique=True, verbose_name='CUFE'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='dian_validation_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción Validación'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(help_text='Numero UBL: puede ser alfanumerico (FAxxxx) o hash SHA256 (96 chars). Max real encontrado: 96.', max_length=200, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='cude',
            field=models.CharField(help_text='Código Único de Documento Electrónico (identificador legal de la nota)', max_length=200, unique=True, verbose_name='CUDE'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='numero',
            field=models.CharField(help_text='Ej: NC135', max_length=200, unique=True, verbose_name='Número de Nota Crédito'),
        ),
    ]
