# Generated by Django 5.2.13 on 2026-06-03 19:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("facturas", "0029_expand_varchar_limits_from_xml_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaImpuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA"),
                            ("INC", "Impuesto Nacional al Consumo"),
                            ("RETEFUENTE", "Retencion en la Fuente"),
                            ("RETEIVA", "Retencion de IVA"),
                            ("RETEICA", "Retencion de ICA"),
                            ("OTRO", "Otro Impuesto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Impuesto",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Porcentaje",
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Base Imponible",
                    ),
                ),
                (
                    "valor_impuesto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Valor Impuesto",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos_desglosados",
                        to="facturas.factura",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto Desglosado",
                "verbose_name_plural": "Impuestos Desglosados",
                "db_table": "factura_impuestos",
            },
        ),
    ]
