# Generated by Django 5.0.14 on 2026-08-10 19:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0030_facturaimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador publico del item de nota credito', unique=True, verbose_name='UUID')),
                ('linea_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID linea UBL')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo del item')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('item_inventario_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID del Producto o Servicio de Inventario. Referencia soft, sin FK.', null=True)),
                ('item_inventario_tipo', models.CharField(blank=True, choices=[('PRODUCTO', 'Producto de Inventario'), ('SERVICIO', 'Servicio de Inventario')], help_text='Tipo de item de inventario referenciado.', max_length=10, null=True)),
                ('item_inventario_codigo', models.CharField(blank=True, help_text='Snapshot del codigo de inventario al momento de vincular.', max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad_medida', models.CharField(default='UND', max_length=10, verbose_name='Unidad de Medida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('es_servicio', models.BooleanField(default=False, verbose_name='Es servicio?')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturas.notacredito', verbose_name='Nota Credito')),
            ],
            options={
                'verbose_name': 'Item de Nota Credito',
                'verbose_name_plural': 'Items de Nota Credito',
                'ordering': ['nota_credito', 'orden'],
            },
        ),
    ]
