# Generated by Django 5.0.14 on 2026-08-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0031_itemnotacredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='xml_file_path',
        ),
    ]
