# Generated by Django 5.0.14 on 2026-08-24 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0034_alter_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmisionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('transmission_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador propio del intento (SSoT interno, independiente del track_id del proveedor).', unique=True)),
                ('environment', models.CharField(choices=[('TEST', 'Prueba / Simulado'), ('PRODUCTION', 'Producción')], max_length=20)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de respuesta'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR_TRANSMISION', 'Error de transmisión'), ('AMBIGUO', 'Ambiguo (timeout/error de red, sin confirmar)')], db_index=True, default='PENDIENTE', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('track_id', models.CharField(blank=True, help_text='track_id/XmlDocumentKey del proveedor, si aplica.', max_length=128, null=True)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_message', models.TextField(blank=True, default='')),
                ('raw_response', models.TextField(blank=True, default='', help_text='Cuerpo crudo de la respuesta -- nunca secretos.')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmisiones', to='facturas.factura')),
            ],
            options={
                'verbose_name': 'Transmisión de Factura',
                'verbose_name_plural': 'Transmisiones de Factura',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['empresa', 'factura', '-submitted_at'], name='facturas_tr_empresa_d327bf_idx')],
            },
        ),
    ]
