# Generated by Django 5.0.14 on 2026-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0035_transmisionfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='origen',
            field=models.CharField(choices=[('INTERNO', 'Interno (generado por Ventas en SINTEL)'), ('EXTERNO', 'Externo (importado desde XML)')], db_index=True, default='EXTERNO', help_text='INTERNO si se generó desde una Venta de SINTEL; EXTERNO si se importó desde un XML.', max_length=10, verbose_name='Origen del documento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='source_system',
            field=models.CharField(choices=[('SINTEL', 'SINTEL (generado internamente)'), ('SIIGO', 'Siigo'), ('OTRO_FACTURADOR', 'Otro facturador electrónico'), ('MANUAL', 'Cargado manualmente'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', help_text='Solo informativo/trazabilidad -- nunca se usa como regla fiscal.', max_length=20, verbose_name='Sistema de origen'),
        ),
    ]
