# Generated by Django 5.0.14 on 2026-08-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('facturas', '0038_partial_success_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('document_id', models.CharField(db_index=True, help_text='document_id del ReceivedDocument (uuid4)', max_length=64, verbose_name='ID de documento')),
                ('source', models.CharField(choices=[('EMAIL', 'EMAIL'), ('UPLOAD', 'UPLOAD'), ('API', 'API'), ('IMPORT', 'IMPORT')], default='EMAIL', max_length=10, verbose_name='Canal')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo')),
                ('document_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo documental')),
                ('handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='Handler')),
                ('domain', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dominio consumidor')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('DUPLICATE', 'DUPLICATE'), ('INVALID', 'INVALID'), ('REQUIRES_REVIEW', 'REQUIRES_REVIEW'), ('FAILED', 'FAILED'), ('PARTIAL', 'PARTIAL')], db_index=True, max_length=20, verbose_name='Estado')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número del documento creado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facturas.mailingestionrun', verbose_name='Ejecución de ingesta')),
            ],
            options={
                'verbose_name': 'Procesamiento de Documento',
                'verbose_name_plural': 'Procesamientos de Documento',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['run', 'status'], name='facturas_do_run_id_f57407_idx'), models.Index(fields=['document_id'], name='facturas_do_documen_1354ae_idx')],
            },
        ),
    ]
