# Generated by Django 5.0 on 2026-03-06 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la actividad económica', max_length=10, unique=True, verbose_name='Código CIIU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CodigoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código tributario según DIAN', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(help_text='Tipo de código (Responsabilidad, Régimen, etc.)', max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Vigencia')),
            ],
            options={
                'verbose_name': 'Código Tributario',
                'verbose_name_plural': 'Códigos Tributarios',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del concepto según DIAN', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo_retencion', models.CharField(choices=[('ica', 'ICA - Impuesto de Industria y Comercio'), ('iva', 'IVA - Impuesto al Valor Agregado'), ('renta', 'Renta'), ('cree', 'CREE - Impuesto sobre la Renta para la Equidad'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Retención')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de retención (puede variar según actividad)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)')),
                ('base_minima', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo sobre el cual se aplica la retención', max_digits=15, verbose_name='Base Mínima')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Vigencia')),
            ],
            options={
                'verbose_name': 'Concepto de Retención',
                'verbose_name_plural': 'Conceptos de Retención',
                'ordering': ['tipo_retencion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TarifaIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la tarifa según DIAN', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de IVA (ej: 19.00 para 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)')),
                ('tipo_tarifa', models.CharField(choices=[('general', 'General'), ('reducida', 'Reducida'), ('excluido', 'Excluido'), ('exento', 'Exento')], default='general', max_length=20, verbose_name='Tipo de Tarifa')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Vigencia')),
            ],
            options={
                'verbose_name': 'Tarifa de IVA',
                'verbose_name_plural': 'Tarifas de IVA',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tipo de impuesto', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Vigencia')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuestos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContribuyenteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de contribuyente', max_length=120, unique=True, verbose_name='Nombre')),
                ('clase', models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], help_text='Clase de contribuyente (Persona Natural o Persona Jurídica)', max_length=2, verbose_name='Clase')),
                ('segmento_dian', models.CharField(choices=[('GRAN_CONTRIBUYENTE', 'Gran contribuyente'), ('MEDIANO_ALTO', 'Contribuyente mediano alto'), ('MEDIANO', 'Contribuyente mediano'), ('PEQUENO', 'Contribuyente pequeño'), ('MICRO', 'Contribuyente micro'), ('OTRO', 'Otro / No aplica')], default='OTRO', help_text='Segmento según clasificación DIAN', max_length=32, verbose_name='Segmento DIAN')),
                ('base_legal', models.TextField(blank=True, help_text='Referencia a la normativa legal que establece este tipo', verbose_name='Base Legal')),
                ('vigente_desde', models.DateField(blank=True, help_text='Fecha desde la cual este tipo está vigente', null=True, verbose_name='Vigente Desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual este tipo está vigente (null si vigente indefinidamente)', null=True, verbose_name='Vigente Hasta')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Contribuyente',
                'verbose_name_plural': 'Tipos de Contribuyente',
                'ordering': ('clase', 'segmento_dian', 'nombre'),
                'indexes': [models.Index(fields=['clase', 'activo'], name='impuestos_c_clase_ada382_idx'), models.Index(fields=['segmento_dian', 'activo'], name='impuestos_c_segment_c9f120_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, help_text='Archivo subido para procesamiento', null=True, upload_to='impuestos/ingesta/%Y/%m/%d', verbose_name='Archivo')),
                ('url_origen', models.URLField(blank=True, help_text='URL del documento a descargar', null=True, verbose_name='URL Origen')),
                ('fuente', models.CharField(help_text='Fuente del documento (DIAN/DOF/SUIN/DiarioOficial/...)', max_length=100, verbose_name='Fuente')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('XML', 'XML'), ('XLS', 'XLS/XLSX'), ('CSV', 'CSV'), ('OTRO', 'OTRO')], db_index=True, default='OTRO', max_length=10, verbose_name='Tipo')),
                ('content_type', models.CharField(blank=True, default='', help_text='Tipo MIME del archivo', max_length=100, verbose_name='Content Type')),
                ('extension', models.CharField(blank=True, default='', help_text='Extensión del archivo (ej: .pdf, .xlsx)', max_length=10, verbose_name='Extensión')),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes', verbose_name='Tamaño (bytes)')),
                ('hash_sha256', models.CharField(blank=True, db_index=True, help_text='Hash SHA256 del documento para deduplicación', max_length=64, verbose_name='Hash SHA256')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'RECIBIDO'), ('EN_PROCESO', 'EN_PROCESO'), ('PROCESADO', 'PROCESADO'), ('ERROR', 'ERROR')], default='RECIBIDO', max_length=12, verbose_name='Estado')),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent usado para el crawling', max_length=200, verbose_name='User Agent')),
                ('robots_observado', models.BooleanField(default=False, help_text='Indica si se respetó robots.txt', verbose_name='Robots.txt Observado')),
                ('crawl_delay_s', models.PositiveIntegerField(default=0, help_text='Delay configurado en robots.txt', verbose_name='Crawl Delay (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Documento Fuente',
                'verbose_name_plural': 'Documentos Fuente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'created_at'], name='impuestos_d_estado_0c41c3_idx'), models.Index(fields=['hash_sha256'], name='impuestos_d_hash_sh_2bc943_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegimenRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ORDINARIO', 'Régimen Ordinario'), ('ESPECIAL', 'Régimen Tributario Especial (RTE)'), ('SIMPLE', 'Régimen Simple de Tributación (SIMPLE)')], help_text='Código del régimen según DIAN', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del régimen', max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del régimen', verbose_name='Descripción')),
                ('tarifa_base_pj', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa base para personas jurídicas (porcentaje)', max_digits=5, null=True, verbose_name='Tarifa Base PJ (%)')),
                ('requiere_facturacion_electronica', models.BooleanField(default=True, help_text='Indica si este régimen requiere facturación electrónica', verbose_name='Requiere Facturación Electrónica')),
                ('aplica_retenciones', models.BooleanField(default=True, help_text='Indica si este régimen aplica retenciones', verbose_name='Aplica Retenciones')),
                ('base_legal', models.TextField(blank=True, help_text='Referencia a la normativa legal que establece este régimen', verbose_name='Base Legal')),
                ('vigente_desde', models.DateField(blank=True, help_text='Fecha desde la cual este régimen está vigente', null=True, verbose_name='Vigente Desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual este régimen está vigente (null si vigente indefinidamente)', null=True, verbose_name='Vigente Hasta')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este régimen está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Régimen de Renta',
                'verbose_name_plural': 'Regímenes de Renta',
                'ordering': ('codigo',),
                'indexes': [models.Index(fields=['codigo', 'activo'], name='impuestos_r_codigo_c285da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponsabilidadRUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de responsabilidad según DIAN (ej: 48, 49, 47, 52, 13)', max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la responsabilidad', max_length=160, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la responsabilidad', verbose_name='Descripción')),
                ('es_responsable_iva', models.BooleanField(default=False, help_text='Indica si esta responsabilidad implica ser responsable de IVA', verbose_name='Es Responsable de IVA')),
                ('es_no_responsable_iva', models.BooleanField(default=False, help_text='Indica si esta responsabilidad implica NO ser responsable de IVA', verbose_name='Es No Responsable de IVA')),
                ('es_simple', models.BooleanField(default=False, help_text='Indica si esta responsabilidad está relacionada con el régimen SIMPLE', verbose_name='Es SIMPLE')),
                ('es_facturador_electronico', models.BooleanField(default=False, help_text='Indica si esta responsabilidad implica ser facturador electrónico', verbose_name='Es Facturador Electrónico')),
                ('es_gran_contribuyente', models.BooleanField(default=False, help_text='Indica si esta responsabilidad implica ser gran contribuyente', verbose_name='Es Gran Contribuyente')),
                ('base_legal', models.TextField(blank=True, help_text='Referencia a la normativa legal que establece esta responsabilidad', verbose_name='Base Legal')),
                ('vigente_desde', models.DateField(blank=True, help_text='Fecha desde la cual esta responsabilidad está vigente', null=True, verbose_name='Vigente Desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual esta responsabilidad está vigente (null si vigente indefinidamente)', null=True, verbose_name='Vigente Hasta')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta responsabilidad está activa', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Responsabilidad RUT (DIAN)',
                'verbose_name_plural': 'Responsabilidades RUT (DIAN)',
                'ordering': ('codigo',),
                'indexes': [models.Index(fields=['codigo', 'activo'], name='impuestos_r_codigo_f52d79_idx'), models.Index(fields=['es_responsable_iva', 'activo'], name='impuestos_r_es_resp_d24976_idx'), models.Index(fields=['es_facturador_electronico', 'activo'], name='impuestos_r_es_fact_c75cdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del perfil tributario', max_length=160, unique=True, verbose_name='Nombre')),
                ('recomendado_desde', models.DateField(blank=True, help_text='Fecha desde la cual este perfil es recomendado', null=True, verbose_name='Recomendado Desde')),
                ('recomendado_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual este perfil es recomendado (null si vigente indefinidamente)', null=True, verbose_name='Recomendado Hasta')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este perfil está activo', verbose_name='Activo')),
                ('tipo_contribuyente', models.ForeignKey(help_text='Tipo de contribuyente asociado a este perfil', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='impuestos.contribuyentetipo', verbose_name='Tipo de Contribuyente')),
                ('regimen_renta', models.ForeignKey(help_text='Régimen de renta asociado a este perfil', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='impuestos.regimenrenta', verbose_name='Régimen de Renta')),
                ('responsabilidades', models.ManyToManyField(blank=True, help_text='Responsabilidades RUT asociadas a este perfil', related_name='perfiles', to='impuestos.responsabilidadrut', verbose_name='Responsabilidades RUT')),
            ],
            options={
                'verbose_name': 'Perfil Tributario (público)',
                'verbose_name_plural': 'Perfiles Tributarios (público)',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='IngestaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(help_text='Etapa del procesamiento (descarga, parseo, normalizacion, indexado)', max_length=50, verbose_name='Etapa')),
                ('nivel', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('payload', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True, verbose_name='Payload')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='impuestos.documentofuente', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Log de Ingesta',
                'verbose_name_plural': 'Logs de Ingesta',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['documento', 'etapa', 'ts'], name='impuestos_i_documen_cbcbca_idx')],
            },
        ),
        migrations.CreateModel(
            name='NormaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(blank=True, help_text="Número o referencia del artículo (ej: 'Artículo 1', 'Art. 2.1')", max_length=50, null=True, verbose_name='Artículo')),
                ('tema', models.CharField(blank=True, help_text='Tema o categoría de la norma', max_length=200, null=True, verbose_name='Tema')),
                ('impuesto', models.CharField(blank=True, help_text='Tipo de impuesto relacionado (IVA, Retención, ICA, etc.)', max_length=100, null=True, verbose_name='Impuesto')),
                ('vigencia_desde', models.DateField(blank=True, help_text='Fecha de inicio de vigencia', null=True, verbose_name='Vigencia Desde')),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Fecha de fin de vigencia (null si vigente indefinidamente)', null=True, verbose_name='Vigencia Hasta')),
                ('texto_html', models.TextField(blank=True, help_text='Texto de la norma en formato HTML', null=True, verbose_name='Texto HTML')),
                ('texto_plano', models.TextField(help_text='Texto de la norma en formato plano', verbose_name='Texto Plano')),
                ('referencias', models.JSONField(blank=True, default=list, help_text='Lista de referencias a otras normas/artículos', verbose_name='Referencias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('documento_fuente', models.ForeignKey(help_text='Documento del cual se extrajo esta norma', on_delete=django.db.models.deletion.CASCADE, related_name='normas', to='impuestos.documentofuente', verbose_name='Documento Fuente')),
            ],
            options={
                'verbose_name': 'Norma Tributaria',
                'verbose_name_plural': 'Normas Tributarias',
                'ordering': ['documento_fuente', 'articulo', 'vigencia_desde'],
                'indexes': [models.Index(fields=['articulo', 'impuesto'], name='impuestos_n_articul_8b38d4_idx'), models.Index(fields=['vigencia_desde', 'vigencia_hasta'], name='impuestos_n_vigenci_88b173_idx'), models.Index(fields=['documento_fuente'], name='impuestos_n_documen_38fb50_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='normatributaria',
            constraint=models.UniqueConstraint(condition=models.Q(('articulo__isnull', False)), fields=('documento_fuente', 'articulo', 'tema', 'impuesto'), name='unique_norma_por_documento'),
        ),
        migrations.AddIndex(
            model_name='perfiltributario',
            index=models.Index(fields=['nombre', 'activo'], name='impuestos_p_nombre_3375be_idx'),
        ),
        migrations.AddIndex(
            model_name='perfiltributario',
            index=models.Index(fields=['tipo_contribuyente', 'activo'], name='impuestos_p_tipo_co_01076d_idx'),
        ),
        migrations.AddIndex(
            model_name='perfiltributario',
            index=models.Index(fields=['regimen_renta', 'activo'], name='impuestos_p_regimen_60d3e5_idx'),
        ),
    ]
