# Generated by Django 5.0.14 on 2026-03-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asignacionpersonal',
            name='tenant_proy_empresa_1d37f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoproyecto',
            name='tenant_proy_empresa_1e5ce6_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='tenant_proy_empresa_4462c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='tenant_proy_respons_c78364_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='tenant_proy_respons_c4f77b_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='tenant_proy_respons_1f988c_idx',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='tenant_proy_respons_f6c06f_idx',
        ),
    ]
