# Generated by Django 5.2.13 on 2026-05-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturas",
            "0005_factura_retefuente_factura_reteica_factura_reteiva_and_more",
        ),
        (
            "tenant_proyectos",
            "0002_remove_asignacionpersonal_tenant_proy_empresa_1d37f7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="factura_costo",
            field=models.ForeignKey(
                blank=True,
                help_text="Factura que actúa como centro de costos para este proyecto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_asociados",
                to="facturas.factura",
                verbose_name="Factura (Centro de Costos)",
            ),
        ),
    ]
