# Generated by Django 5.2.13 on 2026-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_proyectos", "0003_proyecto_factura_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="factura_costo_numero",
            field=models.CharField(
                blank=True,
                help_text="Snapshot del número de la factura para evitar FK en listados",
                max_length=50,
                verbose_name="Número Factura (Snapshot)",
            ),
        ),
    ]
