# Generated by Django 5.2.13 on 2026-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0007_empresa_owner_email"),
        (
            "facturas",
            "0005_factura_retefuente_factura_reteica_factura_reteiva_and_more",
        ),
        ("tenant_proyectos", "0004_proyecto_factura_costo_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="proveedor_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID referencial del sistema de proveedores (Soft Reference)",
                null=True,
                verbose_name="ID Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="proveedor_nombre",
            field=models.CharField(
                blank=True,
                help_text="Snapshot del nombre del proveedor para evitar FK",
                max_length=200,
                verbose_name="Nombre Proveedor",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(
                fields=["proveedor_id"], name="tenant_proy_proveed_16354d_idx"
            ),
        ),
    ]
