# Generated by Django 5.0.14 on 2026-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('tenant_proyectos', '0005_proyecto_proveedor_id_proyecto_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedido'},
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(condition=models.Q(('material_ref__gt', '')), fields=('pedido', 'material_ref'), name='uniq_itempedido_pedido_material_ref'),
        ),
    ]
