# Generated by Django 5.0.14 on 2026-05-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_owner_email'),
        ('tenant_proyectos', '0008_proyecto_costo_planeado_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDiariaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('fecha', models.DateField(help_text='DEBE estar entre fecha_inicio_real y fecha_fin_estimada del proyecto', verbose_name='Fecha')),
                ('titulo', models.CharField(help_text='Descripción breve de la tarea', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles completos de la tarea', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('asignado_a', models.CharField(blank=True, help_text='Snapshot del nombre del empleado (no FK)', max_length=150, verbose_name='Asignado a')),
                ('notas_progreso', models.TextField(blank=True, help_text='Actualizaciones diarias sobre la ejecución', verbose_name='Notas de Progreso')),
                ('empresa', models.ForeignKey(help_text='DSV: valida que tarea pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_diarias', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_diarias', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarea Diaria',
                'verbose_name_plural': 'Tareas Diarias',
                'ordering': ['fecha', 'created_at'],
                'indexes': [models.Index(fields=['proyecto', 'fecha'], name='tenant_proy_proyect_076e08_idx'), models.Index(fields=['empresa', 'estado'], name='tenant_proy_empresa_099f9a_idx'), models.Index(fields=['fecha'], name='tenant_proy_fecha_f50a61_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tareadiariaproyecto',
            constraint=models.UniqueConstraint(fields=('proyecto', 'fecha', 'titulo'), name='unique_tarea_por_proyecto_fecha_titulo'),
        ),
    ]
