# Generated by Django 5.0.14 on 2026-05-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proyectos', '0009_tareadiariaproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareadiariaproyecto',
            name='fecha',
            field=models.DateField(help_text='DEBE estar entre fecha_inicio y fecha_fin_estimada del proyecto', verbose_name='Fecha'),
        ),
    ]
