# Generated by Django 5.0.14 on 2026-05-20 23:21

from django.db import migrations, models


def _copy_fecha_to_periodo(apps):
    """Data migration: copy existing 'fecha' values to 'fecha_inicio' and 'fecha_fin'."""
    TareaDiariaProyecto = apps.get_model('tenant_proyectos', 'TareaDiariaProyecto')
    for tarea in TareaDiariaProyecto.objects.all():
        if hasattr(tarea, 'fecha') and tarea.fecha:
            tarea.fecha_inicio = tarea.fecha
            tarea.fecha_fin = tarea.fecha
            tarea.save(update_fields=['fecha_inicio', 'fecha_fin'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proyectos', '0010_alter_tareadiariaproyecto_fecha'),
    ]

    operations = [
        # Remove old unique constraint (it uses 'fecha' field which we're removing)
        migrations.RemoveConstraint(
            model_name='tareadiariaproyecto',
            name='unique_tarea_por_proyecto_fecha_titulo',
        ),
        # Add new fecha_inicio field (nullable initially to handle existing data)
        migrations.AddField(
            model_name='tareadiariaproyecto',
            name='fecha_inicio',
            field=models.DateField(
                help_text='Primer dia de la tarea. DEBE estar entre fecha_inicio y fecha_fin_estimada del proyecto',
                verbose_name='Fecha Inicio',
                null=True,
                blank=True
            ),
        ),
        # Add new fecha_fin field (nullable initially to handle existing data)
        migrations.AddField(
            model_name='tareadiariaproyecto',
            name='fecha_fin',
            field=models.DateField(
                help_text='ultimo dia de la tarea. DEBE ser >= fecha_inicio y dentro del rango del proyecto',
                verbose_name='Fecha Fin',
                null=True,
                blank=True
            ),
        ),
        # Data migration: copy fecha values to fecha_inicio and fecha_fin
        migrations.RunPython(
            code=lambda apps, schema_editor: _copy_fecha_to_periodo(apps),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Remove old 'fecha' field
        migrations.RemoveField(
            model_name='tareadiariaproyecto',
            name='fecha',
        ),
        # Alter fecha_inicio to be non-nullable
        migrations.AlterField(
            model_name='tareadiariaproyecto',
            name='fecha_inicio',
            field=models.DateField(
                help_text='Primer dia de la tarea. DEBE estar entre fecha_inicio y fecha_fin_estimada del proyecto',
                verbose_name='Fecha Inicio'
            ),
        ),
        # Alter fecha_fin to be non-nullable
        migrations.AlterField(
            model_name='tareadiariaproyecto',
            name='fecha_fin',
            field=models.DateField(
                help_text='ultimo dia de la tarea. DEBE ser >= fecha_inicio y dentro del rango del proyecto',
                verbose_name='Fecha Fin'
            ),
        ),
        # Add new unique constraint (uses 'fecha_inicio' instead of 'fecha')
        migrations.AddConstraint(
            model_name='tareadiariaproyecto',
            constraint=models.UniqueConstraint(
                fields=['proyecto', 'fecha_inicio', 'titulo'],
                name='unique_tarea_por_proyecto_fecha_inicio_titulo'
            ),
        ),
        # Add new indexes
        migrations.AddIndex(
            model_name='tareadiariaproyecto',
            index=models.Index(fields=['proyecto', 'fecha_inicio'], name='proyectos_tarea_proyecto_fecha_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='tareadiariaproyecto',
            index=models.Index(fields=['fecha_inicio'], name='proyectos_tarea_fecha_inicio_idx'),
        ),
        # Update Meta.ordering (from ['fecha', 'created_at'] to ['fecha_inicio', 'created_at'])
        migrations.AlterModelOptions(
            name='tareadiariaproyecto',
            options={'ordering': ['fecha_inicio', 'created_at'], 'verbose_name': 'Tarea Diaria', 'verbose_name_plural': 'Tareas Diarias'},
        ),
    ]
