# Generated by Django 5.0.14 on 2026-05-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_proyectos', '0011_tareas_periodo_support'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tareadiariaproyecto',
            name='tenant_proy_proyect_076e08_idx',
        ),
        migrations.RemoveIndex(
            model_name='tareadiariaproyecto',
            name='tenant_proy_fecha_f50a61_idx',
        ),
        migrations.RenameIndex(
            model_name='tareadiariaproyecto',
            new_name='tenant_proy_proyect_7fee9b_idx',
            old_name='proyectos_tarea_proyecto_fecha_inicio_idx',
        ),
        migrations.RenameIndex(
            model_name='tareadiariaproyecto',
            new_name='tenant_proy_fecha_i_57e3c7_idx',
            old_name='proyectos_tarea_fecha_inicio_idx',
        ),
    ]
