# Generated by Django 5.2.13 on 2026-05-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_inventario", "0007_add_factura_vinculacion_movimiento"),
        (
            "tenant_proyectos",
            "0012_remove_tareadiariaproyecto_tenant_proy_proyect_076e08_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="servicio_asociado",
            field=models.ForeignKey(
                blank=True,
                help_text="Servicio del catálogo/portafolio vinculado a este proyecto (DSV: debe pertenecer a empresa_id)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_ejecucion",
                to="tenant_inventario.servicio",
                verbose_name="Servicio Asociado",
            ),
        ),
    ]
