# Generated by Django 5.0.14 on 2026-05-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_inventario', '0008_historialservicio_proyecto_nombre_and_more'),
        ('tenant_proyectos', '0013_proyecto_servicio_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='movimiento_inventario_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID del MovimientoInventario vinculado (Soft Reference Kardex).', null=True, verbose_name='Movimiento de Inventario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='servicio_asociado',
            field=models.ForeignKey(blank=True, help_text='Servicio del catalogo/portafolio (campo legacy, no usar en formularios nuevos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_ejecucion', to='tenant_inventario.servicio', verbose_name='Servicio Asociado'),
        ),
    ]
