# Generated by Django 5.2.13 on 2026-05-27 19:07 (original applied schema)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("perfil", "0007_tenantprofile_areas_asignadas_and_more"),
        ("tenant_proyectos", "0014_add_movimiento_inventario_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TareaCorta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Primer dia de la tarea.", verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Ultimo dia de la tarea. DEBE ser >= fecha_inicio",
                        verbose_name="Fecha Fin",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Descripcion breve de la tarea",
                        max_length=200,
                        verbose_name="Titulo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles completos de la tarea",
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "notas_progreso",
                    models.TextField(
                        blank=True,
                        help_text="Notas de avance de la tarea",
                        verbose_name="Notas de Progreso",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="DSV: valida que tarea pertenezca al tenant",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas_cortas",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operador asignado a la tarea corta",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas_cortas",
                        to="perfil.tenantprofile",
                        verbose_name="Operador",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas_cortas",
                        to="tenant_proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea Corta",
                "verbose_name_plural": "Tareas Cortas",
                "ordering": ["fecha_inicio", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["proyecto", "fecha_inicio"],
                        name="tenant_proy_proyect_9b170d_idx",
                    ),
                    models.Index(
                        fields=["empresa", "estado"],
                        name="tenant_proy_empresa_858624_idx",
                    ),
                    models.Index(
                        fields=["fecha_inicio"], name="tenant_proy_fecha_i_a2e92f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proyecto", "fecha_inicio", "titulo"),
                        name="unique_tarea_corta_por_proyecto_fecha_inicio_titulo",
                    )
                ],
            },
        ),
    ]
