# Generated by Django 5.0.14 on 2026-05-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_clientes', '0007_remove_cliente_cuenta_contable_uuid'),
        ('tenant_proyectos', '0017_tareacorta_cliente_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacorta',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente destino de la tarea corta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_cortas', to='tenant_clientes.cliente', verbose_name='Cliente'),
        ),
    ]
