# Generated by Django 5.0.14 on 2026-09-17 20:21

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_proyectos', '0020_itempresupuesto_tareadiaria_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadiariaproyecto',
            name='avance',
            field=models.PositiveIntegerField(blank=True, help_text='Porcentaje de avance reportado para esta tarea (0-100), opcional', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Avance (%)'),
        ),
        migrations.AddField(
            model_name='tareadiariaproyecto',
            name='bloqueos',
            field=models.TextField(blank=True, default='', help_text='Impedimentos u obstaculos reportados en el dia', verbose_name='Bloqueos'),
        ),
        migrations.AddField(
            model_name='tareadiariaproyecto',
            name='incidencias',
            field=models.TextField(blank=True, default='', help_text='Incidentes o eventos relevantes reportados en el dia', verbose_name='Incidencias'),
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fase', models.CharField(choices=[('BORRADOR', '0. Borrador / Oportunidad'), ('INICIO', '1. Inicio (Comercial y Legal)'), ('PLANEACION', '2. Planeacion (Diseno y Tecnica)'), ('EJECUCION', '3. Ejecucion (Operativa)'), ('CIERRE', '4. Cierre (Administrativa)')], help_text='Fase del ciclo de vida a la que corresponde este documento', max_length=20, verbose_name='Fase')),
                ('tipo_documento', models.CharField(choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('ORDEN_PEDIDO', 'Orden de Pedido'), ('AUTORIZACION', 'Autorizacion'), ('COTIZACION_APROBADA', 'Cotizacion Aprobada'), ('ACTA_INICIO', 'Acta de Inicio'), ('CRONOGRAMA', 'Cronograma'), ('DOCUMENTO_EJECUCION', 'Documento de Ejecucion'), ('ACTA_ENTREGA', 'Acta de Entrega'), ('INFORME_FINAL', 'Informe Final')], max_length=30, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/media_private'), upload_to='proyectos/documentos/%Y/%m/', verbose_name='Archivo')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha del Documento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(help_text='DSV: valida que el documento pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_proyecto', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_proyecto_subidos', to='perfil.tenantprofile', verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de Proyecto',
                'verbose_name_plural': 'Documentos de Proyecto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'proyecto', 'tipo_documento', 'activo'], name='tenant_proy_empresa_44a0ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialFaseProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fase_anterior', models.CharField(blank=True, default='', max_length=20, verbose_name='Fase Anterior')),
                ('fase_nueva', models.CharField(max_length=20, verbose_name='Fase Nueva')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('empresa', models.ForeignKey(help_text='DSV: valida que el historial pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='historial_fases_proyecto', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_fases', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_fase_proyecto', to='perfil.tenantprofile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Fase',
                'verbose_name_plural': 'Historial de Fases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'proyecto', '-created_at'], name='tenant_proy_empresa_6e6380_idx')],
            },
        ),
    ]
