# Generated by Django 5.0.14 on 2026-10-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('tenant_cotizaciones', '0010_alter_cotizacion_estado_cotizacionestadoconfig_and_more'),
        ('tenant_proyectos', '0022_proyecto_costo_gastos_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempresupuestoproyecto',
            name='cotizacion_item_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID del CotizacionItem origen cuando origen=COTIZACION.', null=True),
        ),
        migrations.AddField(
            model_name='itempresupuestoproyecto',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COTIZACION', 'Cotizacion')], db_index=True, default='MANUAL', help_text='MANUAL (captura directa) o COTIZACION (sincronizado).', max_length=20, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Cotizacion APROBADA vinculada como fuente de recursos/presupuesto de la fase de Planeacion. Solo se asigna via las acciones vincular-cotizacion/desvincular-cotizacion (nunca PATCH directo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_asociado', to='tenant_cotizaciones.cotizacion', unique=True, verbose_name='Cotizacion'),
        ),
        migrations.AddIndex(
            model_name='itempresupuestoproyecto',
            index=models.Index(fields=['proyecto', 'origen'], name='tenant_proy_proyect_24e7ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempresupuestoproyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('cotizacion_item_uuid__isnull', False)), fields=('proyecto', 'cotizacion_item_uuid'), name='uniq_item_presupuesto_proyecto_cotizacion_item'),
        ),
    ]
