# Generated by Django 5.0.14 on 2026-10-05 15:28

import uuid

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_proyectos', '0023_itempresupuestoproyecto_cotizacion_item_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='supervisor_id',
            field=models.IntegerField(blank=True, help_text='ID referencial del empleado supervisor (Soft Reference)', null=True, verbose_name='ID Supervisor'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='supervisor_nombre',
            field=models.CharField(blank=True, help_text='Snapshot del nombre del supervisor para evitar FK', max_length=200, verbose_name='Nombre Supervisor'),
        ),
        migrations.CreateModel(
            name='CotizacionCostoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('categoria', models.CharField(choices=[('MANO_OBRA', 'Mano de Obra'), ('EQUIPOS', 'Equipos'), ('MATERIALES', 'Materiales')], max_length=20, verbose_name='Categoria')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripcion')),
                ('proveedor_id', models.IntegerField(blank=True, help_text='Soft Reference', null=True, verbose_name='ID Proveedor')),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre Proveedor')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='Numero de Documento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor antes de IVA segun la cotizacion del proveedor.', max_digits=15, verbose_name='Valor')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('archivo_pdf', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/media_private'), upload_to='proyectos/cotizaciones_costo/%Y/%m/', verbose_name='PDF de la cotizacion')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='DSV: valida que la cotizacion de costo pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_costo_proyecto', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_costo', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Cotizacion de Costo',
                'verbose_name_plural': 'Cotizaciones de Costo',
                'ordering': ['categoria', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'proyecto'], name='tenant_proy_empresa_dad90c_idx'), models.Index(fields=['proyecto', 'categoria'], name='tenant_proy_proyect_41a4d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InversionProyectoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('categoria', models.CharField(choices=[('MANO_OBRA', 'Mano de Obra'), ('EQUIPOS', 'Equipos'), ('MATERIALES', 'Materiales')], max_length=20, verbose_name='Categoria')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripcion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('proveedor_id', models.IntegerField(blank=True, help_text='Soft Reference', null=True, verbose_name='ID Proveedor')),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre Proveedor')),
                ('documento_referencia', models.CharField(blank=True, max_length=200, verbose_name='Documento / Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='DSV: valida que la inversion pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='inversiones_inicio_proyecto', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_inicio', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Inversion de Inicio',
                'verbose_name_plural': 'Inversiones de Inicio',
                'ordering': ['categoria', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'proyecto'], name='tenant_proy_empresa_4b4b80_idx'), models.Index(fields=['proyecto', 'categoria'], name='tenant_proy_proyect_e739ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProyectoFacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('factura_uuid', models.UUIDField(db_index=True, help_text='Soft reference a facturas.Factura (naturaleza=VENTA, estado=ACEPTADA).', verbose_name='Factura de Venta')),
                ('factura_numero', models.CharField(blank=True, help_text='Snapshot del numero de factura para listados rapidos.', max_length=200, verbose_name='Numero Factura (Snapshot)')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(help_text='DSV: valida que el vinculo pertenezca al tenant', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_venta_proyecto', to='empresa.empresa', verbose_name='Empresa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_venta_proyecto', to='tenant_proyectos.proyecto', verbose_name='Proyecto')),
                ('vinculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta_vinculadas', to='perfil.tenantprofile', verbose_name='Vinculado por')),
            ],
            options={
                'verbose_name': 'Factura de Venta del Proyecto',
                'verbose_name_plural': 'Facturas de Venta del Proyecto',
                'ordering': ['-fecha_vinculacion'],
                'indexes': [models.Index(fields=['empresa', 'proyecto'], name='tenant_proy_empresa_7dbf93_idx'), models.Index(fields=['factura_uuid'], name='tenant_proy_factura_0d4dac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyectofacturaventa',
            constraint=models.UniqueConstraint(fields=('proyecto', 'factura_uuid'), name='uniq_proyecto_factura_venta'),
        ),
    ]
