# Generated by Django 5.0.14 on 2026-05-23 16:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotMetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True)),
                ('total_facturas', models.IntegerField(default=0)),
                ('facturas_pendientes', models.IntegerField(default=0)),
                ('facturas_vencidas', models.IntegerField(default=0)),
                ('ingresos_mes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_productos', models.IntegerField(default=0)),
                ('productos_bajo_stock', models.IntegerField(default=0)),
                ('valor_inventario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_empleados', models.IntegerField(default=0)),
                ('empleados_activos', models.IntegerField(default=0)),
                ('nominas_pendientes', models.IntegerField(default=0)),
                ('generado_por', models.CharField(default='celery-beat', help_text='Origen del snapshot', max_length=50)),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Snapshot de Métrica Diaria',
                'verbose_name_plural': 'Snapshots de Métricas Diarias',
                'db_table': 'dashboard_snapshot_metrica_diaria',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa_id', 'fecha'], name='dashboard_s_empresa_0ada12_idx')],
            },
        ),
    ]
