# Generated by Django 5.2.13 on 2026-06-09 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("empresa", "0009_sedes_areas_explicit_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotmetricadiaria",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="snapshotmetricadiaria",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_snapshots",
                to="empresa.empresa",
                verbose_name="Empresa",
            ),
        ),
    ]
