# Generated by Django 5.2.13 on 2026-06-09 21:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_snapshotmetricadiaria_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotmetricadiaria",
            name="cartera_pendiente",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="snapshotmetricadiaria",
            name="total_gastos",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="snapshotmetricadiaria",
            name="total_provedores",
            field=models.IntegerField(default=0),
        ),
    ]
