# Generated by Django 5.2.13 on 2026-06-02 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("banco", models.CharField(max_length=100, verbose_name="Banco")),
                (
                    "tipo",
                    models.CharField(max_length=50, verbose_name="Tipo de Cuenta"),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, verbose_name="Numero de Cuenta"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria",
                "verbose_name_plural": "Cuentas Bancarias",
                "db_table": "bancos_cuenta_bancaria",
            },
        ),
        migrations.CreateModel(
            name="ExtractoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Anio")),
                (
                    "archivo_s3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="extractos/",
                        verbose_name="Archivo de Extracto",
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractos",
                        to="bancos.cuentabancaria",
                        verbose_name="Cuenta Bancaria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracto Bancario",
                "verbose_name_plural": "Extractos Bancarios",
                "db_table": "bancos_extracto_bancario",
            },
        ),
        migrations.CreateModel(
            name="TransaccionBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("descripcion", models.TextField(verbose_name="Descripcion")),
                (
                    "sucursal",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sucursal"
                    ),
                ),
                (
                    "dcto",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Documento"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Saldo"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa propietaria (SSoT por tenant). Requerido.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="empresa.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "extracto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="bancos.extractobancario",
                        verbose_name="Extracto Bancario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaccion Bancaria",
                "verbose_name_plural": "Transacciones Bancarias",
                "db_table": "bancos_transaccion_bancaria",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cuentabancaria",
            index=models.Index(
                fields=["empresa", "numero"], name="bancos_cuen_empresa_ff5651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractobancario",
            index=models.Index(
                fields=["empresa", "cuenta", "anio", "mes"],
                name="bancos_extr_empresa_59d3f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaccionbancaria",
            index=models.Index(
                fields=["empresa", "extracto"], name="bancos_tran_empresa_c8ae35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaccionbancaria",
            index=models.Index(
                fields=["empresa", "fecha"], name="bancos_tran_empresa_0ce026_idx"
            ),
        ),
    ]
