# Generated by Django 5.2.13 on 2026-06-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractobancario",
            name="saldo_final",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, verbose_name="Saldo Final"
            ),
        ),
        migrations.AddField(
            model_name="extractobancario",
            name="saldo_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Saldo Inicial",
            ),
        ),
    ]
