# Generated by Django 5.0.14 on 2026-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_extractobancario_saldo_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionbancaria',
            name='conciliado',
            field=models.BooleanField(default=False, help_text='True cuando la transaccion fue vinculada manualmente con un documento.', verbose_name='Conciliado'),
        ),
        migrations.AddField(
            model_name='transaccionbancaria',
            name='factura_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Referencia soft a Factura asociada a esta transaccion.', null=True, verbose_name='UUID Factura'),
        ),
        migrations.AddField(
            model_name='transaccionbancaria',
            name='proveedor_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Referencia soft a Proveedor asociado a esta transaccion.', null=True, verbose_name='UUID Proveedor'),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes'),
        ),
    ]
