# Generated by Django 5.0.14 on 2026-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_add_conciliacion_and_mes_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionbancaria',
            name='cliente_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Referencia soft a Cliente asociado a esta transaccion.', null=True, verbose_name='UUID Cliente'),
        ),
    ]
