# Generated by Django 5.0.14 on 2026-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_transaccion_add_cliente_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionbancaria',
            name='notas_conciliacion',
            field=models.TextField(blank=True, help_text='Observaciones o comentarios sobre la conciliacion de esta transaccion.', null=True, verbose_name='Notas de Conciliacion'),
        ),
    ]
