# Generated by Django 5.0.14 on 2026-09-14 13:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0006_extractobancario_uniq_extracto_bancario_empresa_cuenta_periodo'),
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBancarioAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_referencia', models.CharField(choices=[('FACTURA_VENTA', 'Factura de Venta'), ('FACTURA_COMPRA', 'Factura de Compra'), ('CARTERA', 'Cartera (Cliente)'), ('CUENTA_POR_PAGAR', 'Cuenta por Pagar (Proveedor)'), ('GASTO', 'Gasto'), ('NOMINA', 'Nomina'), ('IMPUESTO', 'Impuesto'), ('TRANSFERENCIA_INTERNA', 'Transferencia entre Cuentas Propias'), ('ANTICIPO', 'Anticipo'), ('OTRO_INGRESO', 'Otro Ingreso'), ('OTRO_EGRESO', 'Otro Egreso'), ('AJUSTE', 'Ajuste'), ('OTRO', 'Otro / Sin clasificar')], max_length=30, verbose_name='Tipo de Referencia')),
                ('referencia_uuid', models.UUIDField(blank=True, db_index=True, help_text='Soft ref al documento/concepto aplicado (Factura, Gasto, PeriodoNomina, etc.).', null=True, verbose_name='UUID Referencia')),
                ('tercero_tipo', models.CharField(blank=True, help_text='CLIENTE | PROVEEDOR | EMPLEADO, cuando aplica.', max_length=20, null=True, verbose_name='Tipo de Tercero')),
                ('tercero_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID Tercero')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Aplicado')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de Aplicacion')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('origen_matching', models.CharField(choices=[('MANUAL', 'Manual'), ('SUGERIDO', 'Sugerido por el sistema')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, help_text='Score 0-1 cuando origen_matching=SUGERIDO.', max_digits=5, null=True, verbose_name='Confianza del Matching')),
                ('empresa', models.ForeignKey(help_text='Empresa propietaria (SSoT por tenant). Requerido.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='empresa.empresa', verbose_name='Empresa')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='bancos.transaccionbancaria', verbose_name='Transaccion Bancaria')),
            ],
            options={
                'verbose_name': 'Aplicacion de Movimiento Bancario',
                'verbose_name_plural': 'Aplicaciones de Movimientos Bancarios',
                'db_table': 'bancos_movimiento_aplicacion',
                'ordering': ['-fecha_aplicacion', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'transaccion'], name='bancos_movi_empresa_075cbc_idx'), models.Index(fields=['empresa', 'tipo_referencia', 'referencia_uuid'], name='bancos_movi_empresa_e7bdfe_idx')],
            },
        ),
    ]
