# Generated by Django 5.0.14 on 2026-09-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0007_movimientobancarioaplicacion'),
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractobancario',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede de la empresa a la que pertenece este extracto. Opcional -- si no se asigna aplica a toda la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractos_bancarios', to='empresa.sede', verbose_name='Sede'),
        ),
    ]
