# Generated by Django 5.0.14 on 2026-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0008_extractobancario_sede'),
        ('empresa', '0009_sedes_areas_explicit_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['empresa', 'activo'], name='bancos_cuen_empresa_64117d_idx'),
        ),
    ]
