# Generated by Django 5.0.14 on 2026-03-23 18:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('FIJO', 'Término Fijo'), ('INDEF', 'Indefinido'), ('OBRA', 'Obra o Labor'), ('PRESTACION', 'Prestación de Servicios')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_mensual', models.DecimalField(decimal_places=2, help_text='Salario mensual en COP (Pesos Colombianos)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, help_text='Auxilio de transporte mensual pactado en COP', max_digits=12)),
                ('prestamos_empresa', models.DecimalField(decimal_places=2, default=0, help_text='Préstamos o deudas que la empresa tiene con el empleado en COP (puede ser 0)', max_digits=12)),
                ('cargo', models.CharField(max_length=120)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Copia digital del contrato firmado (PDF)', null=True, upload_to='empleados/contratos/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('HISTORICO', 'Histórico')], default='ACTIVO', help_text='Estado del contrato: ACTIVO, INACTIVO o HISTORICO', max_length=12)),
                ('activo', models.BooleanField(default=True, help_text="Campo legacy - usar estado='ACTIVO' en su lugar")),
                ('empresa', models.ForeignKey(help_text='SSoT Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'PPT')], max_length=5)),
                ('numero_documento', models.CharField(db_index=True, max_length=32)),
                ('primer_nombre', models.CharField(max_length=80)),
                ('segundo_nombre', models.CharField(blank=True, max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('eps', models.CharField(choices=[('EPS001', 'Nueva EPS'), ('EPS002', 'Salud Total'), ('EPS003', 'Sanitas'), ('EPS004', 'Sura'), ('EPS005', 'Compensar'), ('EPS006', 'Coosalud'), ('EPS007', 'Mutual Ser'), ('EPS008', 'Famisanar'), ('EPS009', 'Ecopetrol (Régimen Especial)'), ('EPS010', 'Salud Mía')], max_length=10, verbose_name='EPS')),
                ('afp', models.CharField(choices=[('AFP001', 'Protección'), ('AFP002', 'Porvenir'), ('AFP003', 'Colfondos'), ('AFP004', 'Skandia'), ('AFP005', 'Colpensiones (Régimen de Prima Media)')], max_length=10, verbose_name='Fondo de Pensión')),
                ('arl', models.CharField(choices=[('ARL001', 'Positiva ARL'), ('ARL002', 'ARL Sura'), ('ARL003', 'ARL Seguros Bolívar'), ('ARL004', 'ARL Colmena'), ('ARL005', 'ARL AXA Colpatria'), ('ARL006', 'ARL La Equidad'), ('ARL007', 'ARL Liberty Seguros')], max_length=10, verbose_name='ARL Contratada')),
                ('nivel_riesgo_arl', models.CharField(choices=[('I', 'Clase I (Riesgo Mínimo)'), ('II', 'Clase II (Riesgo Bajo)'), ('III', 'Clase III (Riesgo Medio)'), ('IV', 'Clase IV (Riesgo Alto)'), ('V', 'Clase V (Riesgo Máximo)')], default='I', max_length=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=12)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Devengo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('periodo_mes', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('fecha_pago', models.DateField()),
                ('dias_laborados', models.DecimalField(decimal_places=2, default=30, help_text='Días laborados en el periodo (0.5-30, permite decimales para medio día)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario base proporcional calculado en COP (según días laborados)', max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, help_text='Auxilio de transporte proporcional calculado en COP', max_digits=12)),
                ('otros_devengos', models.DecimalField(decimal_places=2, default=0, help_text='Otros devengos adicionales del periodo en COP (valor fijo, no proporcional)', max_digits=12)),
                ('salud_empleado', models.DecimalField(decimal_places=2, help_text='4% Ley - Deducción en COP', max_digits=12)),
                ('pension_empleado', models.DecimalField(decimal_places=2, help_text='4% Ley - Deducción en COP', max_digits=12)),
                ('prestamos', models.DecimalField(decimal_places=2, default=0, help_text='Préstamos descontados en COP', max_digits=12)),
                ('descuentos_operativos', models.DecimalField(decimal_places=2, default=0, help_text='Descuentos operativos varios en COP', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la nómina')),
                ('neto_pagar', models.DecimalField(decimal_places=2, editable=False, help_text='Neto a pagar en COP', max_digits=12)),
                ('anulado', models.BooleanField(default=False, help_text='Nómina anulada (no se puede editar)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_nomina', to='tenant_empleados.contrato')),
                ('empresa', models.ForeignKey(help_text='SSoT Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='empresa.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='tenant_empleados.empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='tenant_empleados.empleado'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_empl_empresa_10bc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['numero_documento'], name='tenant_empl_numero__3f90c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='uniq_empleado_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['empresa', 'fecha_pago'], name='tenant_empl_empresa_93ff26_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['empleado', 'fecha_pago'], name='tenant_empl_emplead_30949d_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['empleado', 'anulado'], name='tenant_empl_emplead_1ec067_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['contrato'], name='tenant_empl_contrat_7f91f0_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['periodo_mes'], name='tenant_empl_periodo_6d5222_idx'),
        ),
        migrations.AddConstraint(
            model_name='devengo',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empleado', 'periodo_mes', 'fecha_pago'), name='uniq_nomina_per_empleado_periodo_fecha'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_empl_empresa_ed2ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empleado', 'estado'], name='tenant_empl_emplead_c7ad34_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empleado', 'activo'], name='tenant_empl_emplead_e81a80_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('empleado',), name='uniq_contrato_activo_per_empleado'),
        ),
    ]
