# Generated by Django 5.0.14 on 2026-03-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('tenant_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='SSoT Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresa.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devengo',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='SSoT Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='empresa.empresa'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_empl_empresa_ed2ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['empresa', 'fecha_pago'], name='tenant_empl_empresa_93ff26_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('empleado',), name='uniq_contrato_activo_per_empleado'),
        ),
        migrations.AddConstraint(
            model_name='devengo',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empleado', 'periodo_mes'), name='uniq_nomina_per_empleado_periodo'),
        ),
    ]
