# Generated by Django 5.0 on 2026-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('tenant_empleados', '0002_contrato_empresa_devengo_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devengo',
            name='uniq_nomina_per_empleado_periodo',
        ),
        migrations.AddConstraint(
            model_name='devengo',
            constraint=models.UniqueConstraint(condition=models.Q(('anulado', False)), fields=('empleado', 'periodo_mes', 'fecha_pago'), name='uniq_nomina_per_empleado_periodo_fecha'),
        ),
    ]
