# Generated by Django 5.2.13 on 2026-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_empleados", "0002_add_uuid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="cuenta_contable_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Cuenta PUC nivel 6 (Salarios/Prestaciones por pagar)",
                null=True,
            ),
        ),
    ]
