# Generated by Django 5.0.14 on 2026-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0003_empleado_cuenta_contable_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cuenta_contable_uuid',
        ),
        migrations.AddField(
            model_name='devengo',
            name='cuenta_contable_uuid',
            field=models.UUIDField(blank=True, help_text='Cuenta PUC nivel 6 (Salarios/Prestaciones por pagar)', null=True),
        ),
    ]
