# Generated by Django 5.0.14 on 2026-05-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0005_devengo_horas_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='devengo',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Ultimo dia del periodo laborado', null=True),
        ),
        migrations.AddField(
            model_name='devengo',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Primer dia del periodo laborado', null=True),
        ),
    ]
