# Generated by Django 5.0.14 on 2026-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0006_devengo_fecha_inicio_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(choices=[(36, '36 h/semana'), (40, '40 h/semana'), (42, '42 h/semana — Estándar Colombia 2026 (Ley 2101/2021)'), (44, '44 h/semana'), (48, '48 h/semana')], default=42, help_text='Horas laborales semanales pactadas. Referencia para calculo de H.E. y recargos.'),
        ),
    ]
