# Generated by Django 5.0.14 on 2026-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0007_contrato_horas_semanales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil del empleado (opcional)', null=True, upload_to='empleados/fotos/', verbose_name='Foto'),
        ),
    ]
