# Generated by Django 5.2.13 on 2026-05-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_empleados", "0008_foto_empleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="empresa.area",
                verbose_name="Area",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="empresa.sede",
                verbose_name="Sede",
            ),
        ),
    ]
