# Generated by Django 5.2.13 on 2026-05-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_empleados", "0009_empleado_area_empleado_sede"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devengo",
            name="cuenta_contable_uuid",
        ),
    ]
