# Generated by Django 5.2.13 on 2026-06-03 20:23

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0009_sedes_areas_explicit_fk"),
        ("tenant_empleados", "0010_remove_devengo_cuenta_contable_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolucionDIAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "numero_resolucion",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        verbose_name="Numero Resolucion DIAN",
                    ),
                ),
                (
                    "rango_desde",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rango Desde",
                    ),
                ),
                (
                    "rango_hasta",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rango Hasta",
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateField(
                        help_text="Fecha en la que la DIAN emitio la resolucion",
                        verbose_name="Fecha de Emision",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Fecha desde la cual se empezara a usar en el sistema",
                        verbose_name="Fecha Inicio Aplicacion",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Fecha de vencimiento de la resolucion",
                        verbose_name="Fecha Final Aplicacion",
                    ),
                ),
                (
                    "clave_tecnica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vigente",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Solo una resolucion puede estar vigente para ser usada por defecto.",
                        verbose_name="Vigente (Prestablecida)",
                    ),
                ),
                ("prefijo", models.CharField(max_length=10, verbose_name="Prefijo")),
                (
                    "consecutivo",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        verbose_name="Siguiente Consecutivo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resoluciones_dian_empleados",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolucion DIAN",
                "verbose_name_plural": "Resoluciones DIAN",
                "ordering": ["-vigente", "-fecha_resolucion"],
            },
        ),
        migrations.CreateModel(
            name="TransmisionNominaDIAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("numero_documento", models.CharField(db_index=True, max_length=64)),
                (
                    "cune",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "estado_dian",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADO", "Aceptado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("xml_enviado", models.TextField(blank=True, null=True)),
                ("xml_respuesta", models.TextField(blank=True, null=True)),
                (
                    "devengo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmision",
                        to="tenant_empleados.devengo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmisiones_nomina",
                        to="empresa.empresa",
                    ),
                ),
                (
                    "resolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmisiones",
                        to="tenant_empleados.resoluciondian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmision Nomina DIAN",
                "verbose_name_plural": "Transmisiones Nomina DIAN",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionPrestacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp auto-asignado al crear el registro.",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp auto-actualizado al modificar.",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("PRIMA_SERVICIOS", "Prima de Servicios"),
                            ("CESANTIAS", "Cesantias"),
                            ("VACACIONES", "Vacaciones"),
                            ("LIQUIDACION_DEFINITIVA", "Liquidacion Definitiva"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha_corte", models.DateField()),
                ("dias_base_calculo", models.IntegerField()),
                ("base_salarial", models.DecimalField(decimal_places=2, max_digits=14)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[("PROYECTADO", "Proyectado"), ("PAGADO", "Pagado")],
                        default="PROYECTADO",
                        max_length=20,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="tenant_empleados.contrato",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="tenant_empleados.empleado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones_prestaciones",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidacion de Prestacion",
                "verbose_name_plural": "Liquidaciones de Prestaciones",
                "indexes": [
                    models.Index(
                        fields=["empresa", "empleado"],
                        name="tenant_empl_empresa_900eb6_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="resoluciondian",
            index=models.Index(
                fields=["empresa", "vigente"], name="tenant_empl_empresa_8224a2_idx"
            ),
        ),
    ]
