# Generated by Django 5.0.14 on 2026-06-04 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0011_resoluciondian_transmisionnominadian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='resolucion_dian',
            field=models.ForeignKey(blank=True, help_text='Resolución DIAN asignada para generar documentos de nómina electrónica (DSPNE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_asignados', to='tenant_empleados.resoluciondian', verbose_name='Resolución DIAN Nómina Electrónica'),
        ),
        migrations.AlterField(
            model_name='resoluciondian',
            name='consecutivo',
            field=models.IntegerField(db_index=True, default=1, editable=False, help_text='Se inicializa automaticamente desde rango_desde al crear la resolucion.', verbose_name='Siguiente Consecutivo'),
        ),
    ]
