# Generated by Django 5.0.14 on 2026-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0012_empleado_resolucion_dian_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionprestacion',
            name='desglose_conceptos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionprestacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
