# Generated by Django 5.0.14 on 2026-08-21 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sedes_areas_explicit_fk'),
        ('perfil', '0008_add_alcance_and_sede_area_context'),
        ('tenant_empleados', '0013_liquidacionprestacion_desglose_conceptos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp auto-asignado al crear el registro.', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp auto-actualizado al modificar.', verbose_name='Actualizado')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('periodo_mes', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField(help_text='Fecha de pago planeada para el periodo')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PRELIQUIDADO', 'Preliquidado'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ABIERTO', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago_real', models.DateField(blank=True, help_text='Fecha en que se marcó como pagado (registro manual)', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina_aprobados', to='perfil.tenantprofile')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina_creados', to='perfil.tenantprofile')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_nomina', to='empresa.empresa')),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina_pagados', to='perfil.tenantprofile')),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'verbose_name_plural': 'Periodos de Nómina',
            },
        ),
        migrations.AddField(
            model_name='devengo',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Periodo de nomina al que pertenece (nullable por compatibilidad historica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devengos', to='tenant_empleados.periodonomina'),
        ),
        migrations.AddIndex(
            model_name='periodonomina',
            index=models.Index(fields=['empresa', 'estado'], name='tenant_empl_empresa_182a66_idx'),
        ),
        migrations.AddIndex(
            model_name='periodonomina',
            index=models.Index(fields=['periodo_mes'], name='tenant_empl_periodo_f5b848_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodonomina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ANULADO'), _negated=True), fields=('empresa', 'periodo_mes'), name='uniq_periodo_nomina_activo_per_empresa_mes'),
        ),
    ]
