# Generated by Django 5.0.14 on 2026-09-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_empleados', '0014_periodonomina_devengo_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('RENUNCIA', 'Renuncia Voluntaria'), ('MUTUO_ACUERDO', 'Mutuo Acuerdo'), ('VENCIMIENTO_TERMINO', 'Vencimiento del Término Pactado'), ('TERMINACION_OBRA', 'Terminación de Obra o Labor'), ('JUSTA_CAUSA', 'Justa Causa (Empleador, Art. 62 CST)'), ('SIN_JUSTA_CAUSA', 'Sin Justa Causa (Empleador, Art. 64 CST)'), ('MUERTE', 'Fallecimiento del Trabajador'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Motivo de Retiro'),
        ),
    ]
